# The Rules of Discipline {-} 

## 30. Discipline—Its Nature, Subjects, and Ends {-}

[](){#chapter-slug-30-discipline-its-nature-subjects-and-ends}

1. [](){#30}Discipline is the exercise of authority given the Church by the Lord Jesus Christ to instruct and guide its members and to promote its purity and welfare. The term has two senses:
    a.  [](){#30.1.a}the one referring to the whole government, inspection, training, guardianship, and control which the Church maintains over its members, its officers, and its courts;
    b.  the other a restricted and technical sense, signifying judicial process.
2. In the first and broader sense, all communing, non-communing, and associate members of the Church are subject to its discipline and entitled to the benefits thereof; but in the second and narrower sense the term discipline refers only to those who have made a profession of their faith in Christ.
3. In its proper usage discipline maintains: a) the glory of God; b) the purity of His Church,; and c) the keeping and reclaiming of disobedient sinners. Discipline is for the purpose of godliness;[^rulesOfDiscipline.01] therefore it demands a self-examination under Scripture. 
    
    The ends of discipline, so far as it involves judicial action, are the spiritual good of the offender, the rebuke of offenses, the removal of scandal, the promotion of the purity and welfare of the Church, and the vindication of the honor of Christ.

[^rulesOfDiscipline.01]: 1 Timothy 4:7.

4. [](){#30.4}The power which Christ has given the Church is for building up, and not for destruction, and is to be exercised as under a dispensation of mercy and not of wrath. As in the preaching of the Word the wicked are doctrinally separated from the good, so by discipline the Church authoritatively separates between the holy and the profane. The Church is to act as a mother who corrects her children for their good, that every one of them may be presented faultless in the day of Christ.


## 31. Discipline of Non-communing Members {-}

[](){#chapter-slug-31-discipline-of-non-communing-members}

1. [](){#31}The spiritual nurture, instruction, and training of the children of the Church are committed by God primarily to their parents who are responsible to the Church for the faithful discharge of their obligations, and it is a principal duty of the Church to promote true religion in the home.
2. The Church should also make special provision for instructing the children in the Bible and in the church Catechisms, and to this end Sessions should establish and conduct under their authority Sunday Schools and Bible classes, and should adopt such other methods as may be found helpful. The Session shall encourage parents of the Church to guide their children in the catechising and disciplining of them in the Christian religion.
3. The Church should maintain constant and sympathetic relations with the children, and should encourage them on coming to years of discretion[^rulesOfDiscipline.02] to make confession of the Lord Jesus Christ and to enter upon all the privileges of full church membership. Even if they are wayward they should be cherished by the Church and all diligent means used to reclaim them.

[^rulesOfDiscipline.02]: Isaiah 7:15-16.

4. Adult non-communing members[^rulesOfDiscipline.03] who receive with meekness and appreciation the oversight and instruction of the Church are entitled to special attention. Their rights and privileges under the covenant should be frequently and fully explained, and they should be warned of the sin and danger of neglecting their covenant obligations. When a non-communing member neglects the ongoing exhortation of the session to profess faith in Christ and rejects the covenantal responsibility of submission to home or church, the session may upon prior notification erase his name from the roll. This is an act of discipline without full process.

[^rulesOfDiscipline.03]: From Trinity Reformed Church of Bloomington’s Practice of Admitting Children to the Sacraments (adopted December 11, 2014): “In cases when disability renders a profession of faith unclear, it is the responsibility of the elders to make a determination on a case-by-case basis, praying and trusting God for guidance in this exercise of the power of the keys” (Matthew 16:19). In cases when it is impossible for a person to communicate a verbal or nonverbal profession of faith, since knowledge, assent, and trust cannot be established, admittance to the sacrament of the Lord's Supper shall not be granted. These cases may include severe autism, severe Down's syndrome, or other debilitating conditions. It is not clear that the souls who, in the providence of God, suffer these conditions are able to benefit from the grace that attends this meal. Not being able to demonstrate any capacity to remember Christ's death or to examine themselves, it is impossible to establish the faith that qualifies us for participation in the sacraments. Thus in Christian love we will trust God with His dispensation toward these children and adults, asking our heavenly Father to confer on them every saving grace.”

5. All non-communing members shall be deemed under the care of the church to which their parents belong, if they live under the parental roof and are minors; otherwise, under that of the church where they reside, or with which they ordinarily worship.


## 32. Offenses {-}

[](){#chapter-slug-32-offenses}

1. [](){#32}[](){#32.1}An offense, the proper object of judicial process, is anything in the principles or practice of a church member professing faith in Christ, which is contrary to the Word of God. The *Confession of Faith* and the *Larger* and *Shorter Catechisms* of the Westminster Assembly, together with the formularies of government, discipline, and worship, are accepted by Evangel Presbytery as standard expositions of the teachings of Scripture in relation to both faith and practice. Nothing, therefore, ought to be considered by any court as an offense, or admitted as a matter of accusation, which cannot be proved to be such from Scripture, as interpreted in these Standards.
2. Offenses are either personal or general, private or public; but all of them being sins against God, are therefore grounds of discipline.
3. Personal offenses are violations of the divine law, considered in the special relation of wrongs or injuries to particular individuals. General offenses are heresies or immoralities having no such relation, or considered apart from it.
4. Private offenses are those which are known only to a few persons. Public offenses are those which are notorious.


## 33. Church Censures {-}

[](){#chapter-slug-33-church-censures}

1. [](){#33}The censures which may be inflicted by church courts are admonition, suspension from the Sacraments, suspension from office, deposition from office, and excommunication. When a lower censure fails to reclaim the delinquent, it may become the duty of the court to proceed to the infliction of a higher censure.
2. Admonition is the formal reproof of an offender by a church court, warning him of his guilt and danger, and exhorting him to be more circumspect and watchful in the future.
3. Suspension is a censure which may be inflicted on either a private member or an officer of the Church. In respect to the former, it is a temporary exclusion from the Sacraments; and to the latter, from the exercise of office, and, in ordinary cases, from Sacraments also. This censure becomes necessary when very gross offenses have been committed; or when, notwithstanding admonition or rebuke, an offense is repeated or persisted in; or when probation is necessary to attest repentance and reformation, or to restore to the offender a sense of solemnity and fear when coming to the Lord’s Supper. Suspension may be for a definite time, but generally it should be indefinite in duration, and its removal depends upon evidence of repentance.
4. Excommunication is the excision of an offender from the communion of the Church. This censure is to be inflicted only on account of gross sin or heresy and when the offender shows himself incorrigible and contumacious. The design of this censure is to operate on the offender as a means of reclaiming him, to deliver the Church from the scandal of his offense, and to inspire all with fear by the example of his discipline.
5. Deposition is the removal of an officer from his office, and may or may not be accompanied with the infliction of other censure.


## 34. The Parties in Cases of Process {-}

[](){#chapter-slug-34-the-parties-in-cases-of-process}

1. [](){#34}Original jurisdiction in relation to Ministers of the Gospel pertains exclusively to the Presbytery, and in relation to other church members to the Session, unless the Session shall be unable to try the person or persons accused, in which case the Presbytery shall have the right of jurisdiction.
2. [](){#34.2}It is the duty of all church Sessions and Presbyteries to exercise care over those subject to their authority; and they shall, with due diligence and great discretion, demand from such persons satisfactory explanations concerning reports regarding their Christian character. This duty is more imperative when those who deem themselves aggrieved by injurious reports shall request an investigation. If such investigation, however originating, should result in raising a strong presumption of the guilt of the party involved, the court shall institute process, and shall appoint a prosecutor to prepare the indictment and to conduct the case. This prosecutor shall be a member of the court, except that, in a case before the Session, he may be any communing member of the same congregation with the accused.
3. The original and only parties in a case of process are the accuser and the accused. The accuser is always Evangel Presbytery, whose honor and purity are to be maintained. The prosecutor, whether voluntary or appointed, is always the representative of the Church, and as such has all its rights in the case. In appellate courts the parties are known as appellant and appellee.
4. Every indictment shall begin: “In the name of Evangel Presbytery” and shall conclude, “against the peace, unity and purity of the Church, and the honor and majesty of the Lord Jesus Christ as the King and Head thereof.” In every case the Church is the injured and accusing party, against the accused.
5. An injured party shall not become a prosecutor of personal offenses without having tried the means of reconciliation and of reclaiming the offender, required by Christ: “If your brother sins, go and show him his fault in private; if he listens to you, you have won your brother. But if he does not listen to you, take one or two more with you, so that BY THE MOUTH OF TWO OR THREE WITNESSES EVERY FACT MAY BE CONFIRMED.”[^rulesOfDiscipline.04]

[^rulesOfDiscipline.04]: Matthew 18:15-16.

6. A church court, however, may judicially investigate personal offenses as if general, when the interests of religion seem to demand it. So, also, those to whom private offenses are known cannot become prosecutors, without having previously endeavored to remove the scandal by private means.
7. When the offense is general, the cause may be conducted either by any person appearing as prosecutor, or by a prosecutor appointed by the court.
8. When the prosecution is instituted by the court, the previous steps required by our Lord in the case of personal offenses are not necessary. There are many cases, however, in which it will promote the interests of religion to send a committee to converse in a private manner with the offender, and endeavor to bring him to a sense of his guilt, before instituting actual process.
9. Great caution ought to be exercised in receiving accusations from any person who is known to indulge a malignant spirit towards the accused; who is not of good character; who is himself under censure or process; who is deeply interested in any respect in the conviction of the accused; or who is known to be litigious, rash, or highly imprudent.
10. Every voluntary prosecutor shall be previously warned, that if he fail to show probable cause of the charges, he must himself be censured as a slanderer of the brethren, in proportion to the malignity or rashness manifested in the prosecution.
11. When a member of a church court is under process, all his official functions may be suspended, at its discretion; but this shall never be done in the way of censure.
12. In the discussion of all questions arising when a member of a church court is under process, the accused shall exercise the rights of defendant only, not of judge.


## 35. General Provisions Applicable to All Cases of Process {-}

[](){#chapter-slug-35-general-provisions-applicable-to-all-cases-of-process}

1. [](){#35}It is incumbent on every member of a court of Jesus Christ engaged in a trial of offenders, to bear in mind the inspired injunction: “Brethren, even if anyone is caught in any trespass, you who are spiritual, restore such a one in a spirit of gentleness; each one looking to yourself, so that you too will not be tempted.”[^rulesOfDiscipline.05]

[^rulesOfDiscipline.05]: Galatians 6:1.

2. Process against an offender shall not be commenced unless some person or persons undertake to make out the charge; or unless the court finds it necessary, for the honor of religion, itself to take the step provided for in BCO [34.2](#34.2).
3. It is appropriate that with each citation the moderator or clerk call the attention of the parties to the Rules of Discipline and assist the parties to obtain access to them. When a charge is laid before the Session or Presbytery, it shall be reduced to writing, and nothing shall be done at the first meeting of the court, unless by consent of parties, except to appoint a prosecutor, and order the indictment to be drawn, a copy of which, with the witnesses then known to support it, shall be served on the accused, and to cite all parties and their witnesses to appear and be heard at another meeting, which shall not be sooner than ten days after such citation. At the second meeting of the court the charges shall be read to the accused, if present, and he shall be called upon to say whether he be guilty or not. If he confess, the court may deal with him according to its discretion; if he plead and take issue, the trial shall be scheduled and all parties and their witnesses cited to appear. The trial shall not be sooner than fourteen (14) days after such citation. Accused parties may plead in writing when they cannot be personally present. Parties necessarily absent should have counsel assigned to them.
4. The citation shall be issued and signed by the Moderator or Clerk, by order and in the name of the court; he shall also issue citations to such witnesses as either party shall nominate to appear on his behalf. Indictments and citations shall be delivered in person or in another manner providing verification of the date of receipt. Compliance with these requirements shall be deemed to have been fulfilled if a party cannot be located after diligent inquiry or if a party refuses to accept delivery.
5. In drawing the indictment, the times, places, and circumstances should, if possible, be particularly stated, that the accused may have an opportunity to make his defense.
6. When an accused person shall refuse to obey a citation, he shall be cited a second time; and this second citation shall be accompanied with a notice that if he does not appear at the time appointed (unless providentially hindered, which fact he must make known to the court), or that if he appear and refuse to plead, he shall be dealt with for his contumacy, as hereinafter provided (see BCO [36.2](#36.2), [36.3](#36.3); [37.4](#37.4)).
7. The time which must elapse between the serving of the first citation on the accused person, and the meeting of the court at which he is to appear, shall be at least ten days. But the time allotted for his appearance on the subsequent citation shall be left to the discretion of the court, provided that it be not less than is quite sufficient for a seasonable and convenient compliance with the citation.
8. [](){#35.8}When the offense with which an accused person stands charged took place at a distance, and it is inconvenient for the witnesses to appear before the court having jurisdiction, that court may either appoint a commission of its body, or request the coordinate court[^rulesOfDiscipline.06] contiguous to the place where the facts occurred, to take the testimony for it. The accused shall always have reasonable notice of the time and place of the meeting of this commission or coordinate court.

[^rulesOfDiscipline.06]: A coordinate court is a member church of the Presbytery, or any church or presbytery holding to the Westminster Standards.

9. When an offense, alleged to have been committed at a distance, is not likely otherwise to become known to the court having jurisdiction, it shall be the duty of the court nearest to where the facts occurred, after satisfying itself that there is probable ground of accusation, to send notice to the court having jurisdiction, which shall at once proceed against the accused; or the whole case may be remitted for trial to the court nearest to where the offense is alleged to have been committed.
10. Before proceeding to trial, courts ought to ascertain that their citations have been duly served.
11. In every process, if deemed expedient, there may be a committee appointed, which shall be called the Judicial Committee, and whose duty it shall be to digest and arrange all the papers, and to prescribe, under the direction of the court, the whole order of the proceedings. The members of this committee shall be entitled, notwithstanding their performance of this duty, to sit and vote in the case as members of the court.
12. When the trial is about to begin, it shall be the duty of the Moderator solemnly to announce from the chair that the court is about to pass to the consideration of the cause, and to enjoin on the members to recollect and regard their high character as judges of a court of Jesus Christ, and the solemn duty in which they are about to engage.
13. In order that the trial may be fair and impartial, the witnesses shall be examined in the presence of the accused, or at least after he shall have received due citation to attend. Witnesses may be cross-examined by both parties, and any questions asked which are pertinent to the issue.
14. On all questions arising in the progress of a trial, the discussion shall first be between the parties; and when they have been heard, they may be required to withdraw from the court until the members deliberate upon and decide the point.
15. When a court of first resort proceeds to the trial of a cause, the following order shall be observed: 1, The Moderator shall charge the court. 2, The indictment shall be read, and the answer of the accused heard. 3, The witnesses for the prosecutor and then those for the accused shall be examined. 4, The parties shall be heard; first, the prosecutor, and then the accused, and the prosecutor shall close. 5, The roll shall be called, and the members may express their opinion in the cause. 6, The vote shall be taken, the verdict announced and judgment entered on the records.
16. Either party may, for cause, challenge the right of any member to sit in the trial of the case, which question shall be decided by the members of the court other than the one challenged.
17. Pending the trial of a case, any member of the court who shall express his opinion of its merits to either party, or to any person not a member of the court; or who shall absent himself from any sitting without the permission of the court, or satisfactory reasons rendered, shall be thereby disqualified from taking part in the subsequent proceedings.
18. Minutes of the trial shall be kept by the Clerk, which shall exhibit the charges, the answer, all the testimony, and all such acts, orders, and decisions of the court relating to the case, as either party may desire, and also the judgment. The Clerk shall, without delay, assemble the Record of the Case which shall consist of the charges, the answer, the citations and returns thereto, and the minutes herein required to be kept. The parties shall be allowed copies of the Record of the Case at their own expense when they demand them. When a case is removed by appeal or complaint, the lower court shall transmit “the record” thus prepared to the higher court with the addition of the notice of appeal or complaint, and the reasons thereof, if any shall have been filed. Nothing which is not contained in this “record” shall be taken into consideration in the higher court. On the final decision of a case in a higher court, its judgment shall be sent down to the court in which the case originated.
19. No professional counsel shall be permitted as such to appear and plead in cases of process in any court; but an accused person may, if he desires it, be represented before the Session by any communing member of the same particular church; or before any other court, by any member of the court. A member of the court so employed shall not be allowed to sit in judgment in the case.
20. Process, in case of scandal, shall commence within the space of one year after the offense was committed or from the court’s discovery of the offense. When, however, a church member shall commit an offense, after removing to a place far distant from his former residence, and where his connection with the church is unknown, in consequence of which circumstances process cannot be instituted within the time above specified, the recent discovery of the church membership of the individual shall be considered as equivalent to the recent discovery of the offense itself. The same principle, in like circumstances, shall also apply to Ministers.


## 36. Special Rules Pertaining to Process before Sessions {-}

[](){#chapter-slug-36-special-rules-pertaining-to-process-before-sessions}

1. [](){#36}Process against all church members, other than Ministers of the Gospel, shall be entered before the Session of the church to which such members belong, except in cases of appeal. However, if the Session refuses to act in doctrinal cases or instances of public scandal and two other Sessions of churches in the same Presbytery request the Presbytery of which the church is a member to initiate proper or appropriate action in a case of process and thus assume jurisdiction and authority, the Presbytery shall do so.
2. [](){#36.2}When an accused person is found contumacious, he shall be immediately suspended from the sacraments (and if an officer from his office) for his contumacy. Record shall be made of that fact and of the charges under which he was arraigned, and the censure may be made public, should this be deemed expedient by the Session. The censure shall in no case be removed until the offender has not only repented of his contumacy, but has also given satisfaction in relation to the charges against him.
3. [](){#36.3}If after further endeavor by the court to bring the accused to a sense of his guilt, he persists in his contumacy, he shall be excommunicated from the Church.
4. When it is not feasible immediately to commence process against an accused church member, the Session may, if it thinks the edification of the Church requires it, prevent the accused from approaching the Lord’s table until the charges against him can be examined.


## 37. Special Rules Pertaining to Process against a Minister {-}

[](){#chapter-slug-37-special-rules-pertaining-to-process-against-a-minister}

1. [](){#37}Process against a Minister shall be entered before the Presbytery of which he is a member.
2. As no Minister ought, on account of his office, to be screened in his sin, or slightly censured, so scandalous charges ought not to be received against him on slight grounds.
3. If anyone knows a Minister to be guilty of a private offense, he should warn him in private. But if the offense be persisted in, or become public, he should bring the case to the attention of some other Minister of the Presbytery for his advice.
4. [](){#37.4}When a minister accused of an offense is found contumacious, he shall be immediately suspended from the sacraments and his office for his contumacy. Record shall be made of the fact and of the charges under which he was arraigned, and the censure shall be made public. The censure shall in no case be removed until the offender has not only repented of his contumacy, but has also given satisfaction in relation to the charges against him.
    
    If after further endeavor by the court to bring the accused to a sense of his guilt, he persists in his contumacy, he shall be deposed and excommunicated from the Church.
    
5. Heresy and schism may be of such a nature as to warrant deposition; but errors ought to be carefully considered, whether they strike at the vitals of religion, and are industriously spread, or whether they arise from the weakness of the human understanding, and are not likely to do much injury.
6. If the Presbytery finds on trial that the matter complained of amounts to no more than such acts of infirmity as may be amended, so that little or nothing remains to hinder the Minister’s usefulness, it shall take all prudent measures to remove the scandal.
7. When a Minister, pending a trial, shall make confession, if the matter be base, flagitious, and of a disqualifying nature, however penitent he may appear to the satisfaction of all, the court shall, without delay, impose definite suspension or depose him from the ministry.
8. [](){#37.8}A Minister under indefinite suspension from his office or deposed for scandalous conduct shall not be restored, even on the deepest sorrow for his sin, until he shall exhibit for a considerable time such an eminently exemplary, humble, and edifying walk and testimony as shall heal the wound made by his scandal. A deposed Minister shall in no case be restored until it shall appear that the general sentiment of the Church is strongly in his favor, and demands his restoration; and then only by the court inflicting the censure, or with its consent. The removal of deposition requires a three-fourths (3/4) vote of the court inflicting the censure, or a three-fourths (3/4) vote of the court to which the majority of the original court delegates that authority.
9. When a Minister is deposed his pastoral relation shall be dissolved; but when he is suspended from office, it shall be left to the discretion of the Presbytery whether the censure shall include the dissolution of the pastoral relation.
10. [](){#37.10}Whenever a Minister of the Gospel shall habitually fail to be engaged in the regular discharge of his official functions, it shall be the duty of the Presbytery, at a stated meeting, to inquire into the cause of such dereliction, and if necessary, to institute judicial proceedings against him for breach of his covenant engagement. If it shall appear that his neglect proceeds only from his lack of acceptance by the church (i.e., the people do not accept him), Presbytery may, upon the same principle upon which it withdraws license from a licentiate for want of evidence of the divine call, divest him of his office without censure, even against his will, a majority of two-thirds being necessary for this purpose.
    
    In such a case, the Clerk shall, under the order of the Presbytery, forthwith deliver to the individual concerned a written notice that, at the next stated meeting, the question of his being so dealt with is to be considered. This notice shall distinctly state the grounds for this proceeding. The party thus notified shall be heard in his own defense; and if the decision pass against him he may appeal, as if he had been tried after the usual forms.
    
    This principle may apply, with any necessary changes, to Ruling Elders and Deacons.


## 38. Evidence {-}

[](){#chapter-slug-38-evidence}

1. [](){#38}All persons of proper age and intelligence are competent witnesses, except such as do not believe in the existence of God, or a future state of rewards and punishments. The accused party may be allowed, but shall not be compelled, to testify; but the accuser shall be required to testify, on the demand of the accused. Either party has the right to challenge a witness whom he believes to be incompetent, and the court shall examine and decide upon his competency. It belongs to the court to judge of the degree of credibility to be attached to all evidence.
2. A husband or wife shall not be compelled to bear testimony the one against the other in any court.
3. The testimony of more than one witness shall be necessary in order to establish any charge; yet if, in addition to the testimony of one witness, corroborative evidence be produced, the offense may be considered to be proved.
4. No witness afterwards to be examined, except a member of the court, shall be present during the examination of another witness on the same case, if either party object.
5. Witnesses shall be examined first by the party introducing them; then cross-examined by the opposite party; after which any member of the court, or either party, may put additional interrogatories. But no question shall be put or answered except by permission of the Moderator, subject to an appeal to the court; and the court shall not permit questions frivolous or irrelevant to the charge at issue.
6. The oath or affirmation to a witness shall be administered by the Moderator in the following or like terms: “Do you solemnly swear, in the presence of God, that you will declare the truth, the whole truth, and nothing but the truth, according to the best of your knowledge in the matter in which you are called to witness, as you shall answer it to the great Judge of the living and the dead?” If, however, at any time a witness should present himself before a court, who for conscientious reasons prefers to swear or affirm in any other manner, he should be allowed to do so.
7. All testimony shall be recorded (transcription, audio or video recording, or some other electronic means) and witnesses informed of such prior to testifying. Such recording becomes part of the Record of the Case. However, in order to be referenced in written or oral briefs, such recording must be transcribed and the transcription authenticated by the trial court. The court of final appeal may assess the cost of transcription equitably among the parties.
8. The records of a court, or any part of them, whether original or transcribed, if regularly authenticated by the Moderator and Clerk, or by either of them, shall be deemed good and sufficient evidence in every other court.
9. In like manner, testimony taken by one court, and regularly certified, shall be received by every other court as no less valid than if it had been taken by itself.
10. When it is not convenient for a court to have the whole, or perhaps any part of the testimony in any particular case, taken in its presence, a commission shall be appointed, or coordinate court, as described in BCO [35.8](#35.8), requested, to take the testimony in question, which shall be considered as if taken in the presence of the court; of which commission or coordinate court, and of the time and place of its meeting, due notice shall be given to the opposite party, that he may have an opportunity of attending. And if the accused shall desire, on his part, to take testimony at a distance, for his own exculpation, he shall give notice to the court of the time and place at which it is proposed to take it that a commission or coordinate court, as in the former case, may be appointed for the purpose. Or the testimony may be taken on written interrogatories, by filing the same with the Clerk of the court having jurisdiction of the case, and giving two weeks’ notice thereof to the adverse party, during which time he may file cross-interrogatories, if he desire it; and the testimony shall then be taken by the commission or coordinate court in answer to the direct and cross-interrogatories, if such are filed, and no notice need be given of the time and place of taking the testimony.
11. A member of the court who has given testimony in a case becomes disqualified for sitting as a judge if either party makes objection.
12. An officer or private member of the church refusing to testify may be censured for contumacy.
13. If after trial before any court new testimony be discovered which the accused believes important, it shall be his right to ask a new trial and it shall be within the power of the court to grant his request.
14. [](){#38.14}If in the prosecution of an appeal, new evidence is offered, which, in the judgment of the appellate court, has an important bearing on the case, it shall be competent for that court to refer the case to the lower court for a new trial; or, with the consent of parties, to admit the evidence and proceed with the case.


## 39. The Infliction of Church Censures {-}

[](){#chapter-slug-39-the-infliction-of-church-censures}

1. [](){#39}When any member or officer of the church shall be found guilty of an offense the court shall proceed with all tenderness and shall deal with its offending brother in the spirit of meekness, the members considering themselves lest they also be tempted.
2. Church censures and the modes of administering them should be suited to the nature of the offenses; for private offenses censure should be administered in the presence of the court alone, or in private by one or more members of the court, but in the case of public offenses, the degree of censure and mode of administering it shall be within the discretion of the court, acting in accordance with paragraphs below which deal with particular censures.
3. The censure of admonition should be administered in private by one or more members of the court if the offense is known only to a few and is not aggravated in character. If the offense is public the admonition should be administered by the Moderator in presence of the court and may also be announced in public should the court deem it expedient.
4. Definite suspension from Sacraments or office should be administered in the presence of the court alone, or in open session of the court, as it may deem best, and public announcement thereof shall be at the court’s discretion.
5. Indefinite suspension from Sacraments or office should be administered after the manner prescribed for definite suspension, but with added solemnity, that it may be the means of impressing the mind of the delinquent with a proper sense of his danger, and under the blessing of God of leading him to repentance. When the court has resolved to pass this sentence, the Moderator shall address the offending brother to the following purpose:  
    
    > “Whereas, You, _______________________(here describe the person as a Minister, Ruling Elder, Deacon, or private member of the church), are convicted by sufficient proof [or, are guilty by your own confession], of the sin of ________________________________(here insert the offense), we, the ______________________ Presbytery [or church Session] , in the name and by the authority of the Lord Jesus Christ, do now declare you suspended from the sacraments of the Church [and from the exercise of your office], until you give satisfactory evidence of repentance.”
    
    To this shall be added such advice or admonition as may be judged necessary, and the whole shall be concluded with prayer to Almighty God that He would follow this act of discipline with His blessing.
    
6. Excommunication shall be administered with a public announcement to the church. In administering this censure the Moderator or a member of the Session shall make a statement of the several steps which have been taken with respect to the offending brother, and of the decision to cut him off from the communion of the Church. He shall then show from Matthew 18:15-18, and I Cor. 5:1-5, the authority of the Church to cast out unworthy members, and shall explain the nature, use, and consequences of this censure. He shall then administer the censure in the following or like words:  
    
    > “Whereas, ____________________, a member of this church, has been, by sufficient proof, convicted of the sin of ___________________________, and after much admonition and prayer, obstinately refuses to hear the Church, and has manifested no evidence of repentance: Therefore, in the name and by the authority of the Lord Jesus Christ, we, the Session of ____________________., do pronounce him to be excluded from the sacraments, and cut off from the fellowship of the Church.”
    
    Prayer shall then be made that by God’s blessing this solemn action of the court may issue in the repentance and restoration of the offender, and in the establishment of all true believers. The members of the church shall be instructed in how to relate to the excommunicated member as defined by Scripture.[^rulesOfDiscipline.07]
    
[^rulesOfDiscipline.07]: 1 Corinthians 5:9-13; Matthew 18:17.
    
7. The censure of deposition shall be administered by the Moderator in the following or like words:  
    
    > “Whereas, ________________________, a Minister of this Presbytery [or a Ruling Elder or Deacon of this church], has been proved, by sufficient evidence to be guilty of the sin of ____________________________, we, the Presbytery [or church Session], of ___________________________, do adjudge him disqualified for the office of the Christian ministry [or Ruling Eldership, or Deaconship], and therefore we do hereby, in the name and by the authority of the Lord Jesus Christ, depose from the office of a Christian Minister [or Ruling Elder, or Deacon], the said __________________, and do prohibit him from exercising any of the functions thereof.”
    
    If the censure include suspension or excommunication, the Moderator shall proceed to say:
    
    > “We do moreover, by the same authority, suspend the said ___________________, from the sacraments of the Church, until he shall exhibit satisfactory evidence of sincere repentance,” or “exclude the said ______________________, from the sacraments, and cut him off from the fellowship of the Church.”
    
    The sentence of deposition ought to be inflicted with solemnities similar to those already prescribed in the case of excommunication.


## 40. The Removal of Censure {-}

[](){#chapter-slug-40-the-removal-of-censure}

1. [](){#40}A person who has been definitely suspended from Sacraments or office shall be restored by the court at the end of the term of his suspension by declaring words of the following import to him:  
    
    > “Whereas, You, ____________________, have been debarred from the Sacraments of the Church [and/or from the office of Minister or Ruling Elder or Deacon], but have now fulfilled the time of your censure, we, of the __________________ [Presbytery *or* Church Session] do hereby, in the name and by the authority of the Lord Jesus Christ, absolve you from the sentence of suspension and do restore you to participation in the Sacraments [and/or the exercise of your said office, and all the functions thereof].”
    
2. After any person has been indefinitely suspended from the sacraments, it is proper that the rulers of the church should frequently converse with him as well as pray with him and for him, that it would please God to give him repentance.
3. When the court shall be satisfied as to the reality of the repentance of an indefinitely suspended offender, he shall be admitted to profess his repentance, either in the presence of the court alone, or publicly, and be restored to the sacraments of the Church, and, if appropriate, to his office, if such be the judgment of the court, which restoration shall be declared to the penitent in words of the following import:  
    
    > “Whereas, You, _____________, have been debarred from the sacraments of the Church [and/or from the office of the Gospel Ministry *or* Ruling Eldership *or* Deaconship], but have now manifested such repentance as satisfies the church, we, the Session [*or* Presbytery] of ________________, do hereby, with great joy, in the name and by the authority of the Lord Jesus Christ absolve you from the said sentence of suspension from the Sacraments [and/or your office], and do restore you to the full communion of the Church [and/or the exercise of your said office, and all the functions thereof].”
    
    After which there shall be prayer and thanksgiving.
    
4. When an excommunicated person shall be so affected with his state as to be brought to repentance, and to desire to be readmitted to the communion of the Church, the Session, having obtained sufficient evidence of his sincere penitence, shall proceed to restore him. This may be done in the presence of the court, or of the congregation as seems best to the Session.
    
    On the day appointed for his restoration, the Minister shall call upon the excommunicated person, and propose to him in the presence of the court, or of the congregation, the following questions:
    
    > “Do you, from a deep sense of your great wickedness, freely confess your sin in thus rebelling against God, and in refusing to hear His Church; and do you acknowledge that you have been in justice and mercy cut off from the communion of the Church? Answer.—I do.” 
    > 
    > “Do you now voluntarily profess your sincere repentance and contrition for your sin and obstinacy; and do you humbly ask the forgiveness of God and His Church? Answer.—I do.” 
    > 
    > “Do you sincerely promise, through divine grace, to live in all humbleness of mind and circumspection; and to endeavor to adorn by a holy life the doctrine of God our Savior? Answer.—I do.”
    
    Here the Minister shall give the penitent a suitable exhortation, encouraging and comforting him. Then he shall pronounce the sentence of restoration in the following or like words:
    
    > “Whereas, You, _______________, have been shut out from the communion of the Church, but have now manifested such repentance as satisfies the Church; in the name of the Lord Jesus Christ, and by His authority, we, the Session of this church, do declare you absolved from the sentence of excommunication formerly pronounced against you; and with great joy we do restore you to the communion of the Church, that you may be a partaker of all the benefits of the Lord Jesus to your eternal salvation.”
    
    The whole shall be concluded with prayer and thanksgiving.
    
5. The restoration of a deposed officer, after public confession has been made in a manner similar to that prescribed in the case, of the removal of censure from an excommunicated person, shall be announced to him by the Moderator in the following form, namely:  
    
    > “Whereas, You, ______________, formerly a Minister of this Presbytery [or a Ruling Elder, or Deacon of this church], have been deposed from your office, but have now manifested such repentance as satisfies the Church; in the name of the Lord Jesus Christ, and by His authority, we, the Presbytery of __________________, [or the Session of this church], do with great joy declare you absolved from the said sentence of deposition formerly pronounced against you; and we do furthermore restore you to your said office, and to the exercise of all the functions thereof, whenever you may be orderly called thereto.”
    
    After which there shall be prayer and thanksgiving, and the members of the court shall extend to him the right hand of fellowship.
    
6. When a Ruling Elder or Deacon has been absolved from the censure of deposition, he cannot be allowed to resume the exercise of his office in the church without re-election by the people. The removal of deposition requires a three-fourths (3/4) vote of the court inflicting the censure, or a three-fourths (3/4) vote of the court to which the majority of the original court delegates that authority.
7. When a person under censure shall remove to a part of the country remote from the court by which he was sentenced, and shall desire to profess repentance and obtain restoration, it shall be lawful for the court, if it deems it expedient, to transmit a certified copy of its proceedings to the Session (or Presbytery) where the delinquent resides, which shall take up the case and proceed with it as though it had originated with itself.
8. In the restoration of a Minister who is under indefinite suspension from the Sacraments, and/or his office, or has been deposed, it is the duty of the Presbytery to proceed with great caution. It should first admit him to the sacraments, if he has been debarred from them, and afterwards should grant him the privilege of preaching on probation for a time, so as to test the sincerity of his repentance and the prospect of his usefulness, and when satisfied in these respects the Presbytery shall take steps to restore him to his office. But the case shall always be under judicial consideration until the sentence of restoration has been pronounced.
9. In the case of the removal of censures from, or the restoration of, a minister, jurisdiction shall be as follows:
    a.  If the censure(s) does not include excommunication, the presbytery inflicting the censure(s) shall retain the authority to remove the censure(s) and, at its discretion, restore him to office. This authority is retained by the presbytery even when a divested or deposed minister is assigned, under the provisions of BCO [49.7](#49.7), to a session.
    b.  If the censure includes excommunication, the penitent may only be restored to the communion of the church through a session (BCO [1.3](#1.3); [7](#7); [62](#62), [63](#63)). Once the penitent is restored, and therefore a member of a local church, the authority to remove any other censure(s) in respect to office, concurrently imposed with that of excommunication shall belong to the court originally imposing such censure(s).


## 41. Cases without Process {-}

[](){#chapter-slug-41-cases-without-process}

1. [](){#41}When any person shall come forward and make his offense known to the court, a full statement of the facts shall be recorded and judgment rendered without process.
2. A Minister of the Gospel against whom there are no charges, if fully satisfied in his own conscience that God has not called him to the ministry, or if he has satisfactory evidence of his inability to serve the Church with acceptance, may report these facts at a stated meeting of Presbytery. At the next stated meeting, if after full deliberation the Presbytery shall concur with him in judgment, it may divest him of his office without censure. This provision shall in like manner apply with any necessary changes to the case of Ruling Elders and Deacons; but in all such cases the Session of the church to which the Ruling Elder or the Deacon who seeks demission belongs shall act as the Presbytery acts in similar cases where a Minister is concerned.
3. When a member or officer shall renounce the communion of this Church by joining some other branch of the visible Church, if in good standing, the irregularity shall be recorded, his new membership acknowledged, and his name erased from the roll. But if there is a record of an investigation in process, or there are charges concerning the member or minister, the court of original jurisdiction may retain his name on the roll and conduct the case, communicating the outcome upon completion of the proceedings to that member or minister. If the court does not conduct the case, his new membership shall be acknowledged, his name removed from the roll, and, at the request of the receiving branch, the matters under investigation or the charges shall be communicated to them.
    
    When a member or minister of this Church shall attempt to withdraw from the communion of this branch of the visible Church by affiliating with a body judged by the court of original jurisdiction as failing to maintain the Word and Sacraments in their fundamental integrity, that member or minister shall be warned of his danger and if he persists, his name shall be erased from the roll, thereby, so far as this Church is concerned, he is deemed no longer to be a member in any body which rightly maintains the Word and Sacraments in their fundamental integrity, and if an officer, thereby withdrawing from him all authority to exercise his office as derived from this Church. When so acting the court shall make full record of the matter and shall notify the offender of its action.
    
4. [](){#41.4}When a member of a particular church has willfully neglected the church for an extended period of time, or has made it known that he has no intention of fulfilling the church vows, then the Session, continuing to exercise pastoral discipline (BCO [30.1.a](#30.1.a) and BCO [30.4](#30.4)) in the spirit of Galatians 6:1, shall remind the member, if possible both in person and in writing, of the declarations and promises by which he entered into a solemn covenant with God and His Church (BCO [62.2, questions 5–6](#62.2.5)), and warn him that, if he persists, his name shall be erased from the roll.
    
    If after diligently pursuing such pastoral discipline, and after further inquiry and due delay, the Session is of the judgment that the member will not fulfill his membership obligations in this or any other branch of the Visible Church (cf. BCO [3.2](#3.2)), then the Session shall erase his name from the roll. This erasure is an act of pastoral discipline (BCO [30.1.a](#30.1.a)) without process. The Session shall notify the person, if possible, whose name has been removed. Notwithstanding the above, if a member thus warned makes a written request for process (see BCO [34–36](#34); [38–39](#38)), the Session shall grant such a request. Further, if the Session determines that any offense of such a member is of the nature that process is necessary, the Session may institute such process.


## 42. Modes in Which the Proceedings of Lower Courts Come Under the Supervision of Higher Courts {-}

[](){#chapter-slug-42-modes-in-which-the-proceedings-of-lower-courts-come-under-the-supervision-of-higher-courts}

1. [](){#42}The acts and decisions of a lower court are brought under the supervision of a higher court in one or another of the following modes:
    a.  Review and Control;
    b.  Reference;
    c.  Appeal;
    d.  Complaint.
2. When the proceedings of a lower court are before a higher court the members of the lower court shall not lose the right to sit, deliberate, and vote in the higher court, except in cases of appeal or complaint.
3. While affirming that the Scripture is “the supreme judge by which all controversies of religion are to be determined,”[^rulesOfDiscipline.08] and that the Constitution of Evangel Presbytery is “subordinate to the Scriptures of the Old and New Testaments, the infallible Word of God” (BCO [29.1](#29.1)), and while affirming also that this Constitution is fallible,[^rulesOfDiscipline.09] Evangel Presbytery affirms that this subordinate and fallible Constitution has been “adopted by the church” (BCO [29.1](#29.1)) “as standard expositions of the teachings of Scripture in relation to both faith and practice” (BCO [32.1](#32.1)) and as setting forth a form of government and discipline “in conformity with the general principles of biblical polity” (BCO [23.6.c](#23.6.c)). To insure that this Constitution is not amended, violated or disregarded in judicial process, any review of the judicial proceedings of a lower court by a higher court shall be guided by the following principles: 
    a.  A higher court, reviewing a lower court, should limit itself to the issues raised by the parties to the case in the original (lower) court. Further, the higher court should resolve such issues by applying the Constitution of the church, as previously established through the constitutional process.
    b.  A higher court should ordinarily exhibit great deference to a lower court regarding those factual matters which the lower court is more competent to determine, because of its proximity to the events in question, and because of its personal knowledge and observations of the parties and witnesses involved. Therefore, a higher court should not reverse a factual finding of a lower court, unless there is clear error on the part of the lower court.
    c.  A higher court should ordinarily exhibit great deference to a lower court regarding those matters of discretion and judgment which can only be addressed by a court with familiar acquaintance of the events and parties. Such matters of discretion and judgment would include, but not be limited to: the moral character of candidates for sacred office, the appropriate censure to impose after a disciplinary trial, or judgment about the comparative credibility of conflicting witnesses. Therefore, a higher court should not reverse such a judgment by a lower court, unless there is clear error on the part of the lower court.
    d.  The higher court does have the power and obligation of judicial review, which cannot be satisfied by always deferring to the findings of a lower court. Therefore, a higher court should not consider itself obliged to exhibit the same deference to a lower court when the issues being reviewed involve the interpretation of the Constitution of the Church. Regarding such issues, the higher court has the duty and authority to interpret and apply the Constitution of the Church according to its best abilities and understanding, regardless of the opinion of the lower court.
    
[^rulesOfDiscipline.08]: [WCF 1.10](https://evangelpresbytery.com/westminster-confession-of-faith/#1.10). 

[^rulesOfDiscipline.09]: [WCF 31.3](https://evangelpresbytery.com/westminster-confession-of-faith/#31.3).


## 43. General Review and Control {-}

[](){#chapter-slug-43-general-review-and-control}

1. [](){#43}It is the right and duty of every court above the Session to review, at least once a year, the records of the court next below, and if any lower court fails to present its records for this purpose, the higher court may require them to be produced immediately, or at any time fixed by this higher court.
2. In reviewing records of a lower court the higher court is to examine:
    a.  Whether the proceedings have been correctly recorded;
    b.  whether they have been regular and in accordance with the Constitution;
    c.  whether they have been wise, equitable, and suited to promote the welfare of the Church;
    d.  whether the lawful injunctions of the higher court have been obeyed.
3. It is ordinarily sufficient for the higher court merely to record in its own minutes and in the records reviewed, whether it approves, disapproves, or corrects the records in any particular; but should any serious irregularity be discovered the higher court may require its review and correction by the lower. Proceedings in judicial cases, however, shall not be dealt with under review and control when notice of appeal or complaint has been given the lower court; and no judgment of a lower court in a judicial case shall be reversed except by appeal or complaint.
4. Courts may sometimes entirely neglect to perform their duty, by which neglect heretical opinions or corrupt practices may be allowed to gain ground; or offenders of a very gross character may be suffered to escape; or some circumstances in their proceedings of very great irregularity may not be distinctly recorded by them; in any of which cases their records will by no means exhibit to the higher court a full view of their proceedings. If, therefore, the next higher court be well advised that any such neglect or irregularity has occurred on the part of the lower court, it is incumbent on it to take cognizance of the same, and to examine, deliberate, and judge in the whole matter as completely as if it had been recorded, and thus brought up by the review of the records.
5. When any court having appellate jurisdiction shall be advised, either by the records of the court next below or by memorial, either with or without protest, or by any other satisfactory method, of any important delinquency or grossly unconstitutional proceedings of such court, the first step shall be to cite the court alleged to have offended to appear by representative or in writing, at a specified time and place, and to show what it has done or failed to do in the case in question. The court thus issuing the citation may reverse or redress the proceedings of the court below in other than judicial cases; or it may censure the delinquent court; or it may remit the whole matter to the delinquent court, with an injunction to take it up and dispose of it in a constitutional manner; or it may stay all further proceedings in the case; as circumstances may require.
6. In process against a lower court, the trial shall be conducted according to the rules provided for process against individuals, so far as they may be applicable.


## 44. References {-}

[](){#chapter-slug-44-references}

1. [](){#44}A reference is a written representation and application made by a lower court to a higher for advice, or other action, on a matter pending before the lower court, and is ordinarily to be made to the next higher court.
2. Among proper subjects for reference are matters that are new, delicate, or difficult; or on which the members of the lower court are very seriously divided; or which relate to questions involving the Constitution and legal procedure respecting which the lower court feels the need of guidance.
3. [](){#44.3}In making a reference the lower court may ask for advice only, or for final disposition of the matter referred; and in particular it may refer a judicial case with request for its trial and decision by the higher court.
4. A reference may be presented to the higher court by one or more representatives appointed by the lower court for this purpose, and it should be accompanied with so much of the record as shall be necessary for proper understanding and consideration of the matter referred.
5. Although references are sometimes proper, yet in general it is better that every court should discharge the duty assigned it under the law of the Church. A higher court is not required to accede to the request of the lower, but it should ordinarily give advice when so requested.
6. When a court makes a reference, it ought to have all the testimony and other documents duly prepared, produced, and in perfect readiness, so that the higher court may be able to fully consider and issue the case with as little difficulty or delay as possible.


## 45. Appeals {-}

[](){#chapter-slug-45-appeals}

1. [](){#45}An appeal is the transfer to a higher court of a judicial case on which judgment has been rendered in a lower court, and is allowable only to the party against whom the decision has been rendered. The parties shall be known as the appellant and appellee. An appeal cannot be made to any court other than the next higher, except with its consent.
2. Only those who have submitted to a regular trial are entitled to an appeal. Those who have not submitted to a regular trial are not entitled to an appeal.
3. The grounds of appeal are such as the following: any irregularity in the proceedings of the lower court; refusal of reasonable indulgence to a party on trial; receiving improper, or declining to receive proper, evidence; hurrying to a decision before all the testimony is taken; manifestation of prejudice in the case; and mistake or injustice in the judgment and censure.
4. Notice of appeal may be given the court before its adjournment. Written notice of appeal, with supporting reasons, shall be filed by the appellant with both the clerk of the lower court and the clerk of the higher court, within thirty days of notification of the last court’s decision.Notification shall be deemed to have occurred on the day of mailing (if certified, registered or express mail of a national postal service or any private service where verifying receipt is utilized), the day of hand delivery, or the day of confirmed receipt in the case of e-mail or facsimile. Furthermore, compliance with such requirements shall be deemed to have been fulfilled if a party cannot be located after diligent inquiry or if a party refuses to accept delivery. No attempt should be made to circularize the courts to which appeal is being made by either party before the case is heard.
5. It shall be the duty of the clerk of the lower court to file with the clerk of the higher court, not more than thirty (30) days after receipt of notice of appeal, a copy of all proceedings in connection with the case, including the notice of appeal and reasons therefor, the response of the lower court, the evidence, and any papers bearing on the case, which together shall be known as “the Record of the Case”, and the higher court shall not admit or consider anything not found in this “Record” without the consent of the parties in the case. Should new evidence come to light the case shall be remanded to the lower court from which the appeal was made, unless both parties consent to admit the new evidence and proceed with the case (cf. BCO [38.14](#38.14)).
6. Notice of appeal shall have the effect of suspending the judgment of the lower court until the case has been finally decided in the higher court. If, however, the censure is suspension from the Sacraments or excommunication, or deposition from office, the court may, for sufficient reasons duly recorded, put the censure into effect until the case is finally decided.
7. After a higher court has decided that an appeal is in order and should be entertained by the court, the court shall hear the case, or appoint a commission to do so. At the hearing, after the Record has been read, each side should be allotted not over thirty (30) minutes for oral argument, the appellant having the right of opening and closing the argument. After the hearing has been concluded, the court or commission should go into closed session, and discuss the merits of the case. The vote then should be taken, without further debate, on each specification in this form: Shall this specification of error be sustained? If the court or commission deem it wise, it may adopt a minute explanatory of its action, which shall become a part of its Record of the Case. The court or commission shall designate one of its members to write the opinion, which opinion shall be adopted by the court or commission as its opinion.
8. The decision of the higher court may be to confirm or to reverse, in whole or in part, the judgment of the lower court; or to remit the case to the lower court for the purpose of amending the record, should it appear incorrect or defective; or to send the case back for a new trial. In every case a full record shall be made, and a copy of it shall be sent to the lower court.
9. An appellant shall be considered to have abandoned his appeal if he fails to appear before the higher court, in person or by counsel, for a hearing thereof, after he has been properly notified; but an appellant may waive, in writing, his right to appear with permission of the court and not be considered to have abandoned his case. In case of such failure to appear, the judgment of the lower court will stand unless the appellant gives to the court a prompt and satisfactory explanation.
10. If an appellant manifests a litigious or otherwise unchristian spirit in the prosecution of his appeal, he shall receive a suitable rebuke by the appellate court.
11. If a lower court shall neglect to send up “the record of the case,” or any part of it, to the injury of the appellant, it shall receive a proper rebuke from the higher court, and the judgment from which the appeal has been taken shall be suspended, until “the record” is produced upon which the issue can be fairly tried.


## 46. Complaints {-}

[](){#chapter-slug-46-complaints}

1. [](){#46}A complaint is a written representation made against some act or decision of a court of the Church. It is the right of any communing member of the Church in good standing to make complaint against any action of a court to whose jurisdiction he is subject, except that no complaint is allowable in a judicial case in which an appeal is pending.
2. A complaint shall first be made to the court whose act or decision is alleged to be in error. Written notice of complaint, with supporting reasons, shall be filed with the clerk of the court within sixty (60) days following the meeting of the court. The court shall consider the complaint at its next stated meeting, or at a called meeting prior to its next stated meeting. No attempt should be made to circularize the court to which complaint is being made by either party.
3. If, after considering a complaint, the court alleged to be delinquent or in error is of the opinion that it has not erred, and denies the complaint, the complainant may take that complaint to the next higher court. If the lower court fails to consider the complaint against it by or at its next stated meeting, the complainant may take that complaint to the next higher court. Written notice thereof shall be filed with both the clerk of the lower court and the clerk of the higher court within thirty (30) days of notification of the last court’s decision. Notification shall be deemed to have occurred on the day of mailing (if certified, registered or express mail of a national postal service or any private service where verifying receipt is utilized), the day of hand delivery, or the day of confirmed receipt in the case of e-mail or facsimile. Furthermore, compliance with such requirements shall be deemed to have been fulfilled if a party cannot be located after diligent inquiry or if a party refuses to accept delivery.
4. Notice of complaint shall not have the effect of suspending the action against which the complaint is made, unless one-third (1/3) of the members present when the action was taken shall vote for its suspension, until the final decision in the higher court.
5. The court against which complaint is made shall appoint one or more representatives to defend its action before the higher court, and the parties in the case shall be known as complainant and respondent. The complainant himself may present his complaint, or he may obtain the assistance of a communing member of Evangel Presbytery, who is in good standing, in presenting his complaint.
6. It shall be the duty of the clerk of the lower court to file with the clerk of the higher court, not more than thirty (30) days after receipt of notice of complaint, a copy of all its proceedings in connection with the complaint including the notice of complaint and supporting reasons, the response of the lower court, if any, and any papers bearing on the complaint. If the clerk of the lower court shall neglect to send up the proceedings on the complaint, he shall receive a proper rebuke from the higher court, and the act or decision complained against shall be suspended until the proceedings are produced so that the higher court can fairly consider the complaint.
7. The complainant shall be considered to have abandoned his complaint if he fails to appear before the higher court, in person or by counsel, for a hearing thereof, after he has been properly notified; but a complainant may waive, in writing, his right to appear with permission of the court and not be considered to have abandoned his case. In case of such failure to appear, the judgment of the lower court will stand unless the complainant gives to the court a prompt and satisfactory explanation.
8. Subject to the provisions below, after the higher court has decided that the notice filed with its clerk was timely and that the complaint is otherwise in order for it to be heard by the higher court, it shall hear the complaint, or appoint a commission to do so. Ordinarily the court or its commission shall schedule a hearing in a manner that reasonably accommodates the schedules of the respective parties and affords each party a prior opportunity to file a written brief upon such terms and in accord with a briefing schedule established by the court or its commission in the reasonable exercise of its discretion.
9. At the hearing, after all the papers bearing on the complaint have been read, the complainant and respondent will be given the opportunity to present argument, the complainant having the right of opening and closing the argument. After the hearing has been concluded, the court or the commission should go into closed session, and discuss and consider the merits of the complaint. The vote should then or later be taken as to what disposition should be made of the complaint, and the complainant and respondent notified of the court’s decision.
10. The higher court has power, in its discretion, to annul the whole or any part of the action of a lower court against which complaint has been made, or to send the matter back to the lower court with instructions for a new hearing. If the higher court rules a lower court erred by not indicting someone, and the lower court refers the matter back to the higher court, it shall accept the reference if it is a doctrinal case or case of public scandal (see BCO [44.3](#44.3)).


## 47. Voting in Appeals and Complaints {-}

[](){#chapter-slug-47-voting-in-appeals-and-complaints}

1. [](){#47}In voting upon a complaint, the vote shall be either to sustain, to sustain in part, or not to sustain.
2. The effect of a vote to sustain shall be to sustain each and all of the items or counts of the complaint; that of a vote not to sustain shall be to annul each and all of the items or counts of the complaint; and that of a vote to sustain in part shall be to sustain one or more specific items or counts of the complaint.
3. Those voting to sustain in part shall be required when voting to state what item or items, count or counts of the complaint they desire to sustain.
4. In making up the vote on the complaint only those items or counts shall be declared to be sustained for the sustaining of which a majority of the votes cast has been given.


## 48. Dissents, Protests, and Objections {-}

[](){#chapter-slug-48-dissents-protests-and-objections}

1. [](){#48}Any member of a court who had a right to vote on a question, and is not satisfied with the action taken by that court, is entitled to have a dissent or protest recorded. None can join in a dissent or protest against an action of any court except those who had a right to vote in the case. Any member who did not have the right to vote on an appeal or complaint, and is not satisfied with the action taken by the court, is entitled to have an objection recorded. A dissent, protest, or objection shall be filed with the clerk of the lower court within thirty days following the meeting of the lower court.
2. A dissent is a declaration on the part of one or more members of a minority in a court, expressing a different opinion from that of the majority in a particular case. A dissent unaccompanied with reasons shall be entered on the records of the court.
3. A protest is a more solemn and formal declaration by members of a minority, bearing their testimony against what they deem a mischievous or erroneous judgment, and is generally accompanied with a detail of the reasons on which it is founded.
4. An objection is a declaration by one or more members of a court who did not have the right to vote on an appeal or complaint, expressing a different opinion from the decision of the court and may be accompanied with the reasons on which it is founded.
5. If a dissent, protest, or objection be couched in temperate language, and be respectful to the court, it shall be recorded; and the court may, if deemed necessary, put an answer to the dissent, protest, or objection on the records along with it. But here the matter shall end, unless the parties protesting obtain permission to withdraw their dissent, protest, or objection absolutely, or for the sake of amendment.


## 49. Jurisdiction {-}

[](){#chapter-slug-49-jurisdiction}

1. [](){#49}When a church member shall remove his residence beyond the bounds of the congregation of which he is a member, so that he can no longer regularly attend its services, it shall be his duty to transfer his membership by presenting a certificate of dismissal from the Session of the church of which he is a member to the church with which he wishes to unite. When the church of which he is a member has no Session, or for other good reasons it seems impossible for the member to secure a certificate of dismissal, he may be received by the Session upon other satisfactory testimonials, in which case the church of which he was a member shall be duly notified.
2. When a church member shall remove his residence beyond the bounds of the church of which he is a member into the bounds of another, it shall be the duty of the Pastor and Ruling Elders of the church of which he is a member, as far as possible, to continue pastoral oversight of him and to inform him that according to the teaching of our Book of Church Order it is his duty to transfer his membership as soon as practicable to the church in whose bounds he is living. It shall also be the duty of the church from whose bounds the member moved to notify the Pastor and Ruling Elders of the church into whose bounds he has moved and request them to take pastoral oversight of the member, with a view to having him transfer his membership. If a member, after having thus been advised, shall neglect for one year to have his membership transferred, the Session shall then proceed, according to BCO [41.4](#41.4), except in special cases such as: servicemen, students, etc. The name of any member whose residence has been unknown for one year to the Session shall be removed from the roll and such names are not to be counted in the annual statistical reports, though act of removal should be recorded in the Session’s minutes. If such a person at a latter date should appear or desire transfer of his letter, the Session will inform the governing body of the inquiring church of their action in removing said person from their roll.
3. Members of one church dismissed to join another shall be held to be under the jurisdiction of the Session dismissing them until they form a regular connection with that to which they have been dismissed.
4. Associate members are those believers temporarily residing in a location other than their permanent homes. Such believers may become associate members of a particular church without ceasing to be communing members of their home churches. An associate member shall have all the right and privileges of that church, with the exception of voting in a congregational or corporation meeting, and holding an office in that church.
5. When a Presbytery shall dismiss a Minister, licentiate, or candidate, the name of the Presbytery to which he is dismissed shall be given in the certificate, and he shall remain under the jurisdiction of the Presbytery dismissing him until received by the other.
6. No certificate of dismissal from either a Session or a Presbytery shall be valid testimony of good standing for a longer period than one year, unless its earlier presentation be hindered by some providential cause; and such certificates given to persons who have left the bounds of the Session or Presbytery granting them, shall certify the standing of such persons only to the time of their leaving those bounds.
7. [](){#49.7}When a Presbytery shall divest a Minister of his office without censure, or depose him without excommunication, it shall assign him to membership in some particular church, subject to the approval of the Session of that church.

