# Directory for the Worship of God {-} 

## Preface to the Directory {-}

<p data-type="subtitle" class="chapter-number"></p>
<p><a id="dfw-preface"></a>The purpose of this Directory is to express the Church&#8217;s common understanding of the principles and practice of public worship that is Reformed according to the Scriptures and, subordinately, to the Confession and Catechisms. Where practices are understood by the Church to be required by the Word of God, either expressly or by good and necessary consequence, they are mandated. In matters of circumstance and form in worship not specifically provided for in Scripture, the Directory provides guidance for their ordering according to the light of nature and Christian prudence, consonant with the general rules of the Word.</p>
<p>The Directory seeks to make clear this distinction in its use of language. The following denotations used in the Directory are to be understood as indicated. The first category denotes practices that are required by the Word of God.</p>

* Practices that are mandated are denoted by &#8220;shall,&#8221; &#8220;will,&#8221; &#8220;is to be,&#8221; &#8220;must,&#8221; and &#8220;are to be.&#8221;

The following three categories denote practices that are not mandated:

* Practices that are strongly recommended are denoted by &#8220;should,&#8221; &#8220;ought to,&#8221; &#8220;is desirable,&#8221; and &#8220;is advisable.&#8221;

* Practices that are commended as suitable are denoted by &#8220;is appropriate,&#8221; &#8220;is well,&#8221; and &#8220;is fitting.&#8221;

* Practices that are permissible are denoted by &#8220;may.&#8221;

<p>Other imperative forms occur in the Directory, and sometimes the forms in the list above are varied by modifying words or are put in the negative, either of which alters their force. For example, &#8220;may not&#8221; and &#8220;may only&#8221; are mandatory prohibitions, even though &#8220;may&#8221; is permissive. The meaning of these additional and altered forms is to be determined by the rules of English usage, with due respect to the distinctions outlined above.</p>
<p>The Suggested Forms for Particular Services are, by definition, suggested. The distinctions outlined above do not apply to the Suggested Forms.</p>
<p>Scripture quotations in the Directory and the Suggested Forms are drawn from the New American Standard Bible (1995) with a few variations, indicated by brackets, where deemed advisable for current understanding, without prejudice to other translations. In the use of the Directory, any accurate, faithful translation may be substituted.</p>

<section data-type="chapter" class="chapter" id="chapter-slug-50-gods-institution-of-public-worship" title="50. God’s Institution of Public Worship">

## 50. God’s Institution of Public Worship {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch50">
<li class="no-indent"><a id="50"></a>The living and true God, our triune Creator, has instituted the worship of Himself by all people everywhere in spirit and in truth.
<ol type="a">
<li class="no-indent">Because man&#8217;s chief end is to glorify God and fully to enjoy Him forever, all of life is to be worshipful. Nevertheless, worship itself consists primarily in specific acts of communion with God. </li>
<li class="no-indent">Only those people whose hearts have been made new through God&#8217;s grace by the work of the Holy Spirit can truly worship God. </li>
<li class="no-indent">While believers are to worship in secret as individuals and in private as families, they are also to worship as churches in assemblies of public worship, which are not carelessly or willfully to be neglected or forsaken. Public worship occurs when God, by His Word and Spirit, through the lawful government of the church, calls His people to assemble to worship Him together. </li>
</ol>
</li>
<li class="no-indent">In His Word, God has specially appointed one day in seven as a Sabbath to be kept holy to Him. It is the duty of every one to remember the Sabbath day, to keep it holy. From the beginning of the world to the resurrection of Christ, the Sabbath was the last day of the week, marking the completion of six days of work, anticipating eternal rest in the coming Messiah. By raising Christ from the dead on the first day of the week, God sanctified that day. And from the time of the apostles, the church, accordingly, has kept the first day of the week holy as the Christian Sabbath, the Lord&#8217;s Day, and as the day on which it is to assemble for worship. Now each weekly cycle begins with the people of God resting in Christ in the worship of His name, followed by six days of work. The Lord&#8217;s Day thus both depicts that the Christian&#8217;s rest has already begun in Christ, and anticipates the eternal rest of His sons and daughters in the new heaven and the new earth. </li>
<li class="no-indent">God&#8217;s covenant people are to devote the entire Lord&#8217;s Day as holy to the Lord.
<ol type="a">
<li class="no-indent">In order to sanctify the day, it is necessary for them to prepare for its approach. They should attend to their ordinary affairs beforehand, so that they may not be hindered from setting the Sabbath apart to God. </li>
<li class="no-indent">It is advisable for each individual and family to prepare for communion with God in His public ordinances. Therefore, they ought to do this by reading the Scriptures, by holy meditation, and by prayer, especially for God&#8217;s blessing on the ministry of the Word and sacraments. </li>
<li class="no-indent">They are then to observe a holy rest all the day from their own works, words, and thoughts concerning their everyday employment and recreations, and to devote themselves to delighting in the public and private exercises of communion with God and His people, in showing mercy and doing good in His name, and in works of necessity. </li>
<li class="no-indent">They shall so order works of necessity on that day that they do not improperly detain others from the public worship of God, nor otherwise hinder them from sanctifying the Sabbath. </li>
</ol>
</li>
<li class="no-indent">The Lord&#8217;s Day is a day of holy convocation, the day on which the Lord calls His people to assemble for public worship. Although it is fitting and proper that the members of Christ&#8217;s church assemble for worship on other occasions also, which are left to the discretion of particular sessions, the Lord calls the whole congregation of each local church to the sacred duty and high privilege of assembling for public worship each Lord&#8217;s Day. He expressly commands His people to draw near to Him, not forsaking the assembling of themselves together. Therefore, both worship and fellowship are necessary on the Lord’s Day. </li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-51-the-nature-of-public-worship" title="51. The Nature of Public Worship">

## 51. The Nature of Public Worship {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch51">
<li class="no-indent"><a id="51"></a>An assembly of public worship is not merely a gathering of God&#8217;s children with each other, but is, before all else, a meeting of the triune God with His covenant people. In the covenant, God promises His chosen ones that He will dwell among them as their God and they will be His people.
<ol type="a">
<li class="no-indent">The triune God is present in public worship, not only by virtue of the divine omnipresence, but, much more intimately, as the faithful covenant Savior. Through Christ, God&#8217;s people have access by one Spirit to the Father. </li>
<li class="no-indent">In an assembly of public worship, the triune God is not only the One to whom worship is directed, but also the One who is active in the worship of the church. Through His public ordinances, the covenant God actively works to engage His people in communion with Himself. In public worship, God communes with His people, and they with Him, in a manner which expresses the close relationships of the Father and His redeemed children, of the Son and His beloved Bride, and of the Holy Spirit and the living temple in which He dwells. </li>
<li class="no-indent">Pastors and ruling elders are to endeavor to inculcate in themselves and in the congregation expectations for, attitudes concerning, and behavior during public worship which are appropriate to the glorious fact that public worship is covenantal communion between God and His people in His public ordinances. </li>
</ol>
</li>
<li class="no-indent">Because Christ is the Mediator of the covenant, no one draws near to God except through Him alone.
<ol type="a">
<li class="no-indent">God&#8217;s people enter the Most Holy Place, the heavenly sanctuary, by the redeeming blood of Jesus, by the new and living way opened for them through the curtain, that is, His flesh. They draw near through Him as their Great High Priest, who has not entered a man-made sanctuary but heaven itself, now to appear for them in God&#8217;s presence. </li>
<li class="no-indent">Public worship is to be conducted in a manner that plainly expresses conscious reliance upon the mediation and merits of Jesus Christ. To this end, it is well that there be a prayer of confession of sin early in the worship service. It is fitting that the minister, as God&#8217;s ambassador, then declare an assurance of God&#8217;s grace in Christ, reminding each worshiper that he can have boldness to approach the holy God only through the mediation and merits of Jesus Christ. </li>
</ol>
</li>
<li class="no-indent">By the Spirit of the exalted Christ, God draws near to His people and they draw near to their God. They come by grace to Mount Zion, the heavenly Jerusalem, joining innumerable angels and all the people of God in joyous and reverent communion with Him.
<ol type="a">
<li class="no-indent">God&#8217;s people not only are to come into His presence with a deep sense of awe at the thought of His perfect holiness and their own exceeding sinfulness, but also are to enter into His gates with thanksgiving and into His courts with praise for the great salvation that He has so graciously wrought for them through His only begotten Son and which He applies to them by His Holy Spirit. All are therefore to worship with sincere devotion, reverence, and expectation. </li>
<li class="no-indent">Public worship is to be conducted in reliance on the gracious working of the Spirit of the exalted Christ, which alone can make anyone capable of such sincerity, reverence, devotion, awe, expectation, and joy. Hence, from its beginning to its end, public worship should be conducted in that simplicity which manifests dependence on the Spirit of Christ to bless His own ordinances. </li>
<li class="no-indent">Accordingly, the whole congregation should assemble promptly, that all may be present and may join together for the entire worship service. Unless necessary, none should depart until after the benediction. All should refrain from any behavior that would distract other worshipers or detract from their communion with God. </li>
</ol>
</li>
<li class="no-indent">In public worship, God&#8217;s people draw near to their God unitedly as His covenant people, the body of Christ.
<ol type="a">
<li class="no-indent">For this reason, the covenant children should be present so far as possible, as well as adults. Out-of-service childcare programs, while permissible and in many cases a necessary good, should lead towards and promote a child&#8217;s full participation in the service as soon as possible. Because God makes His covenant with believers and their children, it is fitting for households to sit together. </li>
<li class="no-indent">For the same reason, no favoritism may be shown to any who attend. Nor may any member of the church presume to exalt himself above others as though he were more spiritual, but each shall esteem others better than himself. </li>
<li class="no-indent">The unity and catholicity[^directoryForWorship.01] of the covenant people are to be manifest in public worship. Accordingly, the service is to be conducted in a manner that enables and expects all the members of the covenant community—male and female, old and young, poor and rich, uneducated and educated, healthy and infirm, people from every tribe, tongue, and nation—to worship together. </li>

[^directoryForWorship.01]: I.e., universal or worldwide.

<li class="no-indent">Because God&#8217;s people worship, not as an aggregation of individuals, but as a congregation of those who are members of one another in Christ, public worship is to be conducted as a corporate activity in which all the members participate as the body of Christ. </li>
</ol>
</li>
<li class="no-indent">The triune God assembles His covenant people for public worship in order to manifest and renew their covenant bond with Him and one another. The Holy Spirit engages them and draws them into the Father&#8217;s presence as a living sacrifice in Christ. God Himself has fellowship with them, strengthening and guiding them for life in His presence and service in His kingdom.
<ol type="a">
<li class="no-indent">Public worship should be conducted in a manner that reflects God&#8217;s initiative in the covenant itself, making clear that God establishes and renews His covenant with His people, assuring God&#8217;s people of those things which they so easily forget unless Christ crucified is portrayed before their eyes week after week, cultivating the expectation that God Himself meets His people in Christ as the Holy Spirit works through the public ordinances, always keeping central the persons and works of the triune God. </li>
<li class="no-indent">Consequently, it is well that public worship be so conducted that it is apparent that God summons His church to assemble in His presence, that He assures His people of His receiving and cleansing them through Christ the Mediator, that He consecrates them to Himself and His service by His Word, that He communes with them and gives them grace to help in time of need through His means of grace, and that He sends them out to serve with His blessing at the benediction. </li>
</ol>
</li>
<li class="no-indent">The triune God reveals the way of knowing and worshiping Him in His Word, the Holy Scriptures of the Old and New Testaments, which is the only infallible rule of faith and practice.
<ol type="a">
<li class="no-indent">The principles of public worship must be derived from the Bible—either as they are expressly set down in Scripture or by good and necessary consequence may be deduced from Scripture—and from no other source. The purpose of this directory is not contrary to that purpose, as it points us to what Scripture teaches concerning worship. Thus this directory and our confessions are standards always understood to be subordinate to the Word of God. </li>
<li class="no-indent">God may not be worshiped according to human imaginations or inventions or in any way not prescribed by His Word, nor may the church require her members to participate in elements of worship that God&#8217;s Word does not require. Only when the elements of worship are those appointed in God&#8217;s Word, and the circumstances and forms of worship are consonant with God&#8217;s Word, is there true freedom to know God as He is and to worship Him as He desires to be worshiped. </li>
</ol>
</li>
<li class="no-indent">The end of public worship is the glory of the triune God. To that end, Christ builds His church by perfecting the saints and adding to its membership such as are being saved—all to the glory of God. To this end, it is right that non-believers participate in worship because of the natural effect of worship and preaching in calling men to faith.[^directoryForWorship.02]

[^directoryForWorship.02]: 1 Corinthians 14:24-25.

<ol type="a">
<li class="no-indent">Through public worship on the Lord&#8217;s Day, God calls His people to serve Him all the days of the week in their every activity, and enables them, whether they eat or drink or whatever they do, to do all to the glory of God. </li>
<li class="no-indent">God&#8217;s people are to be led to engage in all the elements of worship with a single-minded focus on God&#8217;s glory and with a humble and dependent expectation that the exalted Lord Jesus Christ Himself will edify them and build His church through His appointed means of grace—all to the glory of God. </li>
</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-52-the-parts-of-public-worship" title="52. The Parts of Public Worship">

## 52. The Parts of Public Worship {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch52">
<li class="no-indent"><a id="52"></a>Because a service of public worship is in its essence a meeting of the triune God with His chosen people (some of whom have not yet come to faith and repentance), a worship service consists of two principal parts: those elements which are done on behalf of God (through a representative voice) and those elements which are done by the congregation (through their own or a representative voice).
<ol type="a">
<li class="no-indent">By His Spirit working through the ministry of the Word, God addresses His people in the call to worship, in the salutation[^directoryForWorship.03] and benediction, in the reading and preaching of the Word, and in the sacraments. </li>

[^directoryForWorship.03]: A salutation is a greeting from the Lord, taken from the inspired greetings, like those of the Apostle Paul in his epistles. See Ephesians 1:2; Philippians 1:2.

<li class="no-indent">His people, enabled by the Holy Spirit, address God in prayer, in song, in offerings, in hearing the Word, in confession, and in receiving and partaking of the sacraments. </li>
<li class="no-indent">It is advisable that these two parts be interspersed in the service. </li>
</ol>
</li>
<li class="no-indent">The triune God is not a passive spectator in public worship, but actively works in each element of the service of worship. Neither are the people of God to be passive spectators in public worship, but by faith are to participate actively in each element of the service of worship.
<ol type="a">
<li class="no-indent">Public worship should be conducted in a manner that enables and expects God&#8217;s people by faith actively to embrace the blessing of the Lord in the salutation and benediction; to pray with him who leads in prayer, so that the prayer being uttered aloud becomes their prayer, joining the one speaking to God in their behalf by saying “amen” with him at the conclusion of his prayer; to attend, in the reading of God&#8217;s Word, to what God reveals of Himself, His redeeming actions for them, and His will for their lives; to confess together with all the people the faith of the church; to heed the Word of truth as the sermon is preached and to appropriate it to their lives as God, through His servant, proclaims and applies it; to sing psalms, hymns, and spiritual songs to the praise of God and the edification of one another; to offer their possessions and themselves together as a living sacrifice to the Lord. </li>
<li class="no-indent">Accordingly, it is appropriate that worshipers respond with brief spoken or sung expressions of praise or affirmation such as &#8220;hallelujah&#8221; or &#8220;amen.&#8221; The former is a heartfelt declaration that the living God alone is worthy of adoration. The latter grows out of the responsibility of God&#8217;s people to affirm solemnly and earnestly the truthfulness of His Word and the permanence of His character. It is especially fitting for the congregation to join in an &#8220;amen&#8221; at such times as a response to a blessing, a Scripture reading, a psalm or hymn, a confession of faith, or a prayer. When believers sing or say &#8220;amen,&#8221; they are testifying to their wholehearted agreement with what has been spoken as being in harmony with God&#8217;s permanently valid Word. </li>
</ol>
</li>
<li class="no-indent">The Lord Jesus Christ has not prescribed a set order for public worship and care must be taken to oppose schismatic movements centered around men’s preferences in this matter. It may not be forgotten, however, that there is true liberty only where the rules of God&#8217;s Word are observed and the Spirit of the Lord is, so that all things are done decently and in order, and God&#8217;s people approach Him with reverence and in the beauty of holiness. While Christ has not prescribed a set order for public worship, this does not mean that it is fitting to ignore proper and scriptural patterns of worship that have been historically observed by the church, particularly in the Reformed tradition. The order of worship should be so structured that there will be a purposeful movement on the part of the congregation from one element of the service to the next. When each act of worship is full of meaning, the order of the elements will assume a coherent, edifying form. </li>
<li class="no-indent">The session does well to ensure that the public worship assembly space is so arranged as to reflect and reinforce God&#8217;s initiative in drawing near to and gathering His people through the ministry of the Word and sacraments. Because the pulpit, baptismal waters, and communion table facilitate the part of worship which is performed on behalf of God, it is fitting that they be positioned so as to draw the focus of the congregation upon the Word and sacraments, and that they be easily accessible and visible to the entire congregation throughout the worship service. Because the Word is primary and the sacraments serve to seal the Word, it is fitting that the pulpit be in the position of prominence. </li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-53-the-oversight-and-conduct-of-public-worship" title="53. The Oversight and Conduct of Public Worship">

## 53. The Oversight and Conduct of Public Worship {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch53">
<li class="no-indent"><a id="53"></a>Public worship is Christian, not only when the worshipers consciously recognize that Christ is the Mediator by whom alone they can come unto God, but also when they honor the exalted Christ as the living and only Head of the church, who rules over public worship.
<ol type="a">
<li class="no-indent">He rules over public worship by His Word and Spirit, not only directly, but also through the ministry of officers in their ruling, serving, teaching, and leading His church. </li>
<li class="no-indent">The exalted Christ thus applies Himself and His benefits to the elect through His Spirit working in human hearts by and with His Word, especially in its public reading, its preaching, its sealing by the sacraments, and as it is received in faith by prayer. </li>
</ol>
</li>
<li class="no-indent">For this reason:
<ol type="a">
<li class="no-indent">The session is responsible to give immediate oversight to the conduct of public worship in the local church. </li>
<li class="no-indent">Public worship is ordinarily to be led by those who have been ordained to represent the Lord Jesus Christ in the administration of His Word and sacraments. The pastor of the church is ordinarily responsible to plan (or oversee the planning of) and lead public worship. </li>
<li class="no-indent">Men who have been licensed by a presbytery to preach the Gospel may plan and conduct worship as probationers in order that the churches may form a better judgment respecting the fitness of those by whom they are to be instructed and governed. They may not, however, pronounce the salutation or the benediction or administer the sacraments. </li>
<li class="no-indent">When the session deems it fitting, ruling elders and other approved men may lead the congregation in prayer, read the Scriptures to the congregation, lead unison or antiphonal readings of Scripture by the congregation, lead congregational singing, or, on occasion, exhort the congregation as part of public worship. They may not, however, pronounce the salutation or the benediction, or administer the sacraments. </li>
<li class="no-indent">On occasion, with the approval of the session and under the close supervision of a minister, exceptions may be made for other men (even the young), and especially those being prepared for the Gospel ministry in Christ&#8217;s church who are either members of the congregation governed by that session or are ministerial interns under that session. They may not, however, pronounce the salutation or the benediction or administer the sacraments. </li>
<li class="no-indent">The session may choose to delegate leadership of the musical portions of the service to unordained, godly men gifted for that work, serving under the oversight of the pastor. </li>
<li class="no-indent">No others should take such leadership in overseeing or conducting public worship. </li>
<li class="no-indent">There are times when it is appropriate for women to participate vocally in a worship service without it being a violation of Scripture’s command for women to remain silent.[^directoryForWorship.04] Women should be encouraged to sing, to share prayer requests, to give testimonies of God’s faithfulness, and to pray. </li>

[^directoryForWorship.04]: 1 Corinthians 14:34.

<li class="no-indent">Only church officers should distribute the elements of the Lord’s Supper because this activity involves the exercise of pastoral authority over the congregation and is a picture of our heavenly Father’s provision of fathers to feed His flock. </li>
</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-54-elements-of-ordinary-public-worship-from-god-to-the-people" title="54. Elements of Ordinary Public Worship—From God to the People">

## 54. Elements of Ordinary Public Worship—From God to the People {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch54">
<li class="no-indent"><a id="54"></a><strong>The Call to Worship</strong>
<ol type="a">
<li class="no-indent">God having summoned His people to assemble in His presence to worship Him on the Lord&#8217;s Day, there ought to be a call to the congregation, in God&#8217;s own words, to worship Him. He who performs this element serves as God&#8217;s representative voice; accordingly, it ordinarily should be performed by a minister of the Word. </li>
<li class="no-indent">It is fitting that the congregation respond to the call to worship in words of Scripture, or with singing, or with prayer, or with all of these. </li>
</ol>
</li>
<li class="no-indent"><strong>The Public Reading of God&#8217;s Word</strong>
<ol type="a">
<li class="no-indent">Because the hearing of God&#8217;s Word is a means of grace, the public reading of the Holy Scriptures is an essential element of public worship. He who performs this serves as God&#8217;s representative voice. Thus, it ordinarily should be performed by a minister of the Word. Through this reading, God speaks directly to the congregation in His own words. For this reason, readers other than the pastor should ordinarily refrain from interspersing the reading of God&#8217;s Word with human comments. He should use an accurate, faithful translation in the language of the people. In English, translations such as the NASB95, NKJV, and KJV fulfill these requirements. Modern translations that pander to the corruptions of the day, such as minimizing or removing the male semantic meaning components of God’s words, are forbidden. The minister should read clearly and with understanding, and the congregation should attend to the reading with the deepest reverence. </li>
<li class="no-indent">It is desirable that portions from both the Old and the New Testaments be read each Lord&#8217;s Day. It is also well that the law of God be read frequently. </li>
<li class="no-indent">The public reading of the Scriptures to the congregation is to be distinguished from the unison or antiphonal reading of certain portions of Scripture by the minister and the congregation together. In the former, God addresses His people; in the latter, God&#8217;s people address their God, expressing in the words of Scripture their own contrition, adoration, gratitude, and other holy sentiments. The Psalms of Scripture are especially appropriate for this purpose. </li>
</ol>
</li>
<li class="no-indent"><strong>The Preaching of God&#8217;s Word</strong>
<ol type="a">
<li class="no-indent">The preaching of the Word, the power of God unto salvation, is of central importance in the public worship of God. It is therefore a matter of supreme importance that the minister preach only the Word of God, not the wisdom of man, and that he handle the Word of God correctly, always setting forth Jesus Christ, the Author and Finisher of our faith. In the sermon, God addresses the congregation by the mouth of His servant, and through His Spirit opens the ears of His people. </li>
<li class="no-indent">The preacher shall prepare each sermon prayerfully and diligently. He must take pains to expound a particular text of Scripture, bringing in other texts as applicable, carefully explaining the meaning, and diligently applying the particular text(s) for the salvation and edification of his hearers. He should take care in preaching that his exposition and application of the Scriptures be clear and simple, having regard to the capacity of the hearers, in demonstration of the Spirit and power, with fervor and zeal, and that he not divorce Christian duty from Christian faith. The preacher must, as Christ&#8217;s ambassador, seek to build up the saints in the most holy faith and beseech the unconverted to be reconciled to God. Nothing is more necessary than that the Gospel of salvation by grace be proclaimed without any adulteration or compromise, in order that the hearers may learn to rely for salvation only on the grace of God in Christ, to the exclusion of their own works or character, ascribing all glory to God alone for their salvation. The preacher is to instruct his hearers in the whole counsel of God, exhort the congregation to more perfect obedience to Christ, and warn them of the sins and dangers that are around them and within them. A preacher fails to perform his task as a God-appointed watchman on Zion&#8217;s walls when he neglects to warn the congregation of prevalent soul-destroying teachings by enemies of the Gospel. </li>
<li class="no-indent">The session is to give diligence that no person enter the pulpit concerning whose soundness in doctrine and life, or knowledge of Scripture, there is reasonable doubt. </li>
<li class="no-indent">No person shall be invited to preach in any of the churches under our care without the consent of the Session, unless sent by the Presbytery. </li>
</ol>
</li>
<li class="no-indent"><strong>The Sacraments</strong>
<ol type="a">
<li class="no-indent">The sacraments, baptism and the Lord&#8217;s Supper, as visible signs and seals of the Word of the covenant, are important elements of public worship. They represent Christ and His benefits, confirm His people&#8217;s participation in Him, visibly mark off from the world those who belong to His church, and solemnly bind them to covenant faith and loyalty. </li>
<li class="no-indent">Because the sacraments are ordinances of Christ for the benefit of the visible church, they are to be administered only under the oversight of the government of the church. Moreover, in ordinary circumstances they are properly administered only in a gathering of the congregation for the public worship of God, baptism being a sacrament whereby the parties baptized are solemnly admitted into the visible church, and the Lord&#8217;s Supper signifying and sealing the communion of believers with Christ and with each other as members of His mystical body. </li>
<li class="no-indent">Although the efficacy of the sacraments does not depend upon the piety or intention of the person administering them, they are not to be administered by any private person, but only a minister of the Word. Because the sacraments were given from Christ through the apostles to the church,[^directoryForWorship.05] and ministers are “stewards of the mysteries of God”[^directoryForWorship.06] in Christ’s church, no other is permitted to take this honor to himself.[^directoryForWorship.07] </li>

[^directoryForWorship.05]: Matthew 28:16-20; 1 Corinthians 11:23.

[^directoryForWorship.06]: 1 Corinthians 4:1.

[^directoryForWorship.07]: Hebrews 5:4.

</ol>
</li>
<li class="no-indent"><strong>Blessings</strong>
<ol type="a">
<li class="no-indent">The salutation and the benediction are blessings pronounced in God&#8217;s name and in His own words. Accordingly, they are properly used only in a gathering of Christ&#8217;s church and by a minister of the Word. </li>
<li class="no-indent">A salutation is the greeting from God to His people who have gathered to worship Him. It is fittingly pronounced immediately before or after the call to worship. Words of salutation from Scripture may be used, such as the opening greeting from one of the New Testament epistles, &#8220;Grace to you and peace from God our Father and the Lord Jesus Christ.&#8221; </li>
<li class="no-indent">A benediction is the pronouncement of God&#8217;s blessing upon His people at the conclusion of the worship service. Words of benediction taken from Scripture are to be used. The high priestly benediction, &#8220;The LORD bless you, and keep you; the LORD make His face shine upon you and be gracious to you; the LORD lift up His countenance on you, and give you peace,&#8221;[^directoryForWorship.08] or the Trinitarian apostolic benediction, &#8220;The grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit, be with you all,&#8221;[^directoryForWorship.09] are distinctly appropriate. If, however, the minister deems another benediction taken from Scripture more fitting for a particular occasion, he may use it. </li>

[^directoryForWorship.08]: Numbers 6:24-26.

[^directoryForWorship.09]: 2 Corinthians 13:14.

</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-54-elements-of-ordinary-public-worship-from-the-people-to-god" title="55. Elements of Ordinary Public Worship—From the People to God">

## 55. Elements of Ordinary Public Worship—From the People to God {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch55">
<li class="no-indent"><a id="55"></a><strong>Public Prayer</strong>
<ol type="a">
<li class="no-indent">Prayer is an essential element of public worship. In order to be accepted by God, prayer is to be by faith, in the name of the Son of God, by the help of His Spirit, and according to God&#8217;s will. </li>
<li class="no-indent">In preparation for the service, the session should provide circumstances conducive to the people adopting an attitude appropriate to worship and prayer. </li>
<li class="no-indent">He who leads in public prayer serves as the voice of the congregation. For this reason, he should pray in such a way, in clear words and in the plural, that the entire assembly of God&#8217;s people can pray with him; and it is the duty of the members of the congregation, not only to hear his words, but also to pray them in their hearts. To these ends, he who leads should diligently prepare himself for public prayers, so that he may perform this duty with propriety and with profit to the worshipers. </li>
<li class="no-indent">It is particularly appropriate that public prayer be led by a pastor of the congregation, because in it he both guides the people in their corporate prayer to God and teaches them how to pray biblically. Accordingly, every minister should, by a thorough acquaintance with the Holy Scriptures, by the study of the best writings on prayer, by meditation, and by a life of communion with God, endeavor to acquire both the spirit and the skill of prayer, as should ruling elders. When a guest minister is present, it is well that a pastor or ruling elder, as one who knows the congregation, lead in the prayers of intercession. </li>
<li class="no-indent">Near the beginning of the service, there should be a brief prayer of approach to God in response to His call to enter His presence for worship. It may express humble adoration, confess unworthiness and inability to worship aright, seek His merciful acceptance through Jesus Christ, and invoke the gracious working of the Holy Spirit. </li>
<li class="no-indent">During the service, there should be comprehensive prayer, which may be offered as more than one prayer throughout the worship service. Such prayer should include adoration of God&#8217;s perfections, thanksgiving for all His mercies, confession of sin, supplication for forgiveness through the blood of the atonement and for renewal by the Holy Spirit, lamentation in times of distress or crisis, and intercession for the needs of God&#8217;s people and others. It is fitting that the congregation intercede for the whole of mankind; for civil rulers; for the church universal; for Christian missions at home and abroad, Christian education, and other Christian activities; for our whole Church; for churches in ties of like faith with us; for the welfare of the local congregation itself, including its officers, its ministries, and its members, pleading for their growth in sanctification and remembering the daily needs and care of the people—the families, the singles, the rising generation, the elderly, the poor, the sick, the dying, the mourning, the erring, and unsaved loved ones; and for whatever else may seem particularly suitable. </li>
<li class="no-indent">It is fitting that a prayer of confession of sin precede or follow any reading of the law of God to the congregation. </li>
<li class="no-indent">It is appropriate that there be a brief offertory prayer either immediately preceding or immediately following the worship of God with offerings. Such prayer may thank God for His gifts, devote the offering and the worshipers to His service, and invoke His blessing on its use and on those who give. </li>
<li class="no-indent">It is fitting to pray at the time of the reading and preaching of the Word. Such prayer may petition for the Holy Spirit to grant illumination and to apply the Word preached to the minds, hearts, and lives of the people and give thanks for the Word received. It is valuable that such prayer should be by the one preaching the Word. </li>
<li class="no-indent">While public prayer must always be offered with deep humility and holy reverence and be free from vain repetition or display of words, it can be fitting at times for the entire congregation to pray vocally in unison. The form of prayer that our Lord Jesus taught His disciples, commonly called &#8220;the Lord&#8217;s Prayer,&#8221; is particularly appropriate for this use by the congregation. Great care should be taken, however, to guard against allowing this practice to become a mere formula or ritual. </li>
<li class="no-indent">It is fitting to encourage the congregation to join vocally in a corporate &#8220;amen&#8221; at the conclusion of a prayer. </li>
<li class="no-indent">Our prayers should be addressed to God the Father and concluded in the name of the Son, according to Scripture.[^directoryForWorship.10] </li>

[^directoryForWorship.10]: Luke 11:2; John 14:13-14.

</ol>
</li>
<li class="no-indent"><strong>Congregational Singing</strong>
<ol type="a">
<li class="no-indent">Congregational singing is a duty and privilege and should not be neglected in worship. Let every member of the church take part in this act of worship. God&#8217;s people should sing, not merely with the lips, but with understanding and with grace in their hearts, making melody to the Lord. </li>
<li class="no-indent">As public worship is for the praise and glory of God and the building up of the saints, not for the entertainment of the congregation nor the praise of man, the character of the songs used therein is to befit the nature of God and the purpose of worship. </li>
<li class="no-indent">Congregations do well to sing the metrical versions or other musical settings of the Psalms frequently in public worship. Congregations also do well to sing hymns of praise that respond to the full scope of divine revelation. It is recommended that new songs and Psalm settings be sung along with the familiar hymns of the church. </li>
<li class="no-indent">In the choice of song for public worship, great care must be taken that all the materials of song are fully in accord with the Scriptures. The words are to be suitable for the worship of God and the tunes are to be appropriate to the meaning of the words and to the occasion of public worship. Care should be taken to the end that the songs chosen will express those specific truths and sentiments which are appropriate at the time of their use in the worship service. </li>
<li class="no-indent">Musical gifts are properly used in public worship to assist the congregation in its worship of God. They may not be used for the praise or applause of men. </li>
<li class="no-indent">No person may take a prominent part in the leadership of the service unless he is a professing Christian who is a member of Christ’s church. </li>
</ol>
</li>
<li class="no-indent"><strong>Public Confession of Faith</strong>
<ol type="a">
<li class="no-indent">Individual believers are to publicly profess their faith in Christ before God and His people in order formally to pledge their commitment to serve Christ and to be welcomed into all the privileges of full communion with God&#8217;s people. </li>
<li class="no-indent">It is also fitting that the congregation as one body confess its common faith, using creeds that are true to the Word of God, such as the Apostles&#8217; Creed or the Nicene Creed. </li>
</ol>
</li>
<li class="no-indent"><strong>The Bringing of Offerings</strong>
<ol type="a">
<li class="no-indent">The bringing of offerings in the public assembly of God&#8217;s people on the Lord&#8217;s Day is a solemn act of worship to almighty God. The people of God are to set aside to Him the firstfruits of their labors; in so doing, they should present themselves with thanksgiving as a living sacrifice to God. All should participate in this act of worship when God gives opportunity for it. Parents are to instruct and encourage their children by precept and example to give of their substance regularly, purposefully, generously, and joyfully to the Lord through His church. </li>
<li class="no-indent">It is the duty of the pastor, since he is to proclaim to the people the whole counsel of God, to cultivate biblical stewardship and the grace of liberal giving in the members of the church. The pastor himself, as well as the officers of the church, should be exemplary in their own worship through tithes and offerings. The Pastor should remind the church of the admonition in Scripture that everyone is to give as the Lord has prospered him, of the assurance of Scripture that God loves a cheerful giver, and of the blessed example of the Lord Jesus Christ, who, though He was rich, became poor, in order that poor sinners through His poverty might become rich. </li>
<li class="no-indent">The session shall take care that the tithes and offerings of the congregation are used only for biblical purposes, such as the maintenance of public worship, the preaching of the Gospel throughout the world, the ministry of mercy in Christ&#8217;s name, and other Christian objects. </li>
<li class="no-indent">It is desirable that Christian love be demonstrated by offerings for the use of the deacons in the ministry of mercy on behalf of the church. It is appropriate that a special offering be received for this purpose following the Lord&#8217;s Supper. </li>
</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-56-the-administration-of-the-sacraments-general-provisions" title="56. The Administration of the Sacraments—General Provisions">

## 56. The Administration of the Sacraments—General Provisions {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch56">
<li class="no-indent"><a id="56"></a>In order that the sacraments may be observed with discernment and profit, it is imperative that adequate preparation be made prior to their administration. Before observing the sacraments, God&#8217;s people ought to meditate on the teaching of the Word of God concerning them, particularly as summarized in the Confession of Faith and Catechisms. It is also advisable that from time to time the preaching include suitable instruction on the sacraments. Moreover, when the sacraments are being celebrated, the minister shall always accompany them by the preaching of the Word, and he shall take especial care in that preaching to proclaim Christ and His benefits, so that God&#8217;s people can understand what the sacrament means. In connection with the administration of the sacraments, he shall set forth a summary of the teaching of the Word of God as to their institution, meaning, and nature.</li>
<li class="no-indent">Concerning paedo-baptism, the baptism of infants is not to be unduly delayed, but is to be administered as soon as practicable.</li>
<li class="no-indent">Concerning credo-baptism, baptism is to be administered as soon as practicable after public profession of faith in Christ.</li>
<li class="no-indent">The Lord&#8217;s Supper is to be celebrated frequently, but the frequency may be determined by each session as it may judge most conducive to edification.</li>
<li class="no-indent">In the administration of the sacraments, the minister shall follow the directions prescribed in this chapter, but, except in the case of the words of the baptismal formula, he is not required to use the exact language of the indented forms (below), which are suggested as appropriate. He may employ these or similar forms, using his own liberty and godly wisdom, as he deems best for the edification of the people.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-57-the-baptism-of-infants" title="57. The Baptism of Infants">

## 57. The Baptism of Infants {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch57">
<li class="no-indent"><a id="57"></a><strong>Prerequisites</strong>
<p class="no-indent">For a child to be presented for baptism, at least one parent must be a communing member of the Church, in good standing, normally of the local congregation. In order to present a child for baptism, parents shall make prior arrangements with the session. Before presentation for baptism, the session shall ensure that instruction has been given to the parent(s) as to the nature, privileges, and responsibilities of baptism for the parents and the child. Only parents who are communing members of a church may be permitted to take parental vows. If only one of two parents is a communing member and taking vows, it shall be the duty of the minister to inform the congregation of the situation, including that the one parent is not a member of this congregation and is not taking the vows. In extraordinary circumstances, at the parents’ request, the session may permit the baptism of a child of parents who are communing members of another church which is approved by the session, on behalf of and with the written permission of the governing body of that church. In such a case, the session shall inform the other governing body, in writing, when the baptism has been administered.</p>
</li>
<li class="no-indent"><strong>The Administration of Baptism to Infants</strong>
<ol type="a">
<li class="no-indent"><strong>The Institution of the Sacrament</strong>
<p class="no-indent">The minister ought to read the words of the institution of the sacrament of baptism from a passage such as Matthew 28:18-20.</p>
</li>
<li class="no-indent"><strong>The Meaning and Nature of the Sacrament</strong>
<p class="no-indent">The minister shall first summarize before the congregation the teaching of the Word of God and the Confession and Catechisms of this church as to the meaning and nature of the sacrament of baptism. In doing so, he may use these or like words:

> The Lord Jesus Christ instituted baptism as a covenant sign and seal for His church. He uses it not only for the solemn admission of the person who is baptized into the visible church, but also to depict and to confirm His ingrafting of that person into Himself and His including that person in the covenant of grace.
> 
> The Lord uses baptism to portray to us that we and our children are conceived and born in sin and need to be cleansed.
> 
> He uses it to witness and seal to us the remission of sins and the bestowal of all the gifts of salvation through union with Christ. Baptism with water signifies and seals cleansing from sin by the blood and the Spirit of Christ, together with our death unto sin and our resurrection unto newness of life by virtue of the death and resurrection of Christ. The time of the outward application of the sign does not necessarily coincide with the inward work of the Holy Spirit which the sign represents and seals to us. Because these gifts of salvation are the gracious provision of the triune God, who is pleased to claim us as His very own, we are baptized in the name of the Father and of the Son and of the Holy Spirit.
> 
> In our baptism, the Lord puts His name on us, claims us as His own, and summons us to assume the obligations of the covenant. He calls us to believe in Jesus Christ as our Savior, to renounce the devil, the world, and the flesh, and to walk humbly with our God in devotion to His commandments.

</li>
<li class="no-indent"><strong>Exhortation to the Members of the Congregation to Improve Their Baptism</strong>
<p class="no-indent">Then the minister may exhort the congregation in these or like words:</p>
<blockquote>
<p>As solemn vows are about to be made before you, and baptism is now to be administered, you who are baptized will do well to take this occasion to reflect on your own baptism. Christ has put His name and claim on you. He calls you to be repentant for your sins against your covenant God, to confess your faith before men, and to live in newness of life to God, who sealed His covenant with you by the blood of His own Son.</p>
</blockquote>
</li>
<li class="no-indent"><strong>The Ground of Baptizing Infants</strong>
<p class="no-indent">The minister shall then give instruction as to the ground of the baptism of infants. He may use these or like words:</p>

> Although our young children do not yet understand these things, they are nevertheless to be baptized. For God commands that all who are under His covenant of grace be given the sign of the covenant.
> 
> God made the promise of the covenant to believers and to their offspring. In the Old Testament, He declared to Abraham: &#8220;I will establish My covenant between Me and you and your descendants after you throughout their generations for an everlasting covenant, to be a God unto you, and to your descendants after you.&#8221;[^directoryForWorship.11] For this reason, in the Old Testament, God commanded that covenant infants be given the sign of circumcision.
> 
> The covenant is the same in essence in both the Old and the New Testaments. Indeed, the grace of God for the consolation of believers is even more fully manifested in the New Testament. He declares that &#8220;For the promise is for you and your children.&#8221;[^directoryForWorship.12] He promises, &#8220;Believe in the Lord Jesus Christ, and you will be saved, you and your household.&#8221;[^directoryForWorship.13] He affirms that if even one parent is a believer, the children are &#8220;holy.&#8221;[^directoryForWorship.14] Moreover, our Savior admitted little children into His presence, embracing and blessing them, and saying, &#8220;for the kingdom of God belongs to such as these.&#8221;[^directoryForWorship.15]</p>
> 
> And so, in the New Testament no less than in the Old, the children of believers have an interest in the covenant and a right to the covenant sign and to the outward privileges of the covenant people, the church. In the New Testament, baptism has replaced circumcision as the covenant sign.[^directoryForWorship.16] Therefore, by the covenant sign of baptism the children of believers are to be distinguished from the world and solemnly admitted into the visible church.

[^directoryForWorship.11]: Genesis 17:7.

[^directoryForWorship.12]: Acts 2:39.

[^directoryForWorship.13]: Acts 16:31.

[^directoryForWorship.14]: 1 Corinthians 7:14.

[^directoryForWorship.15]: Mark 10:14.

[^directoryForWorship.16]: Colossians 2:11–12.

</li>
<li class="no-indent"><strong>The Covenant Commitments of the Parents and the Congregation</strong>
<p class="no-indent">The minister shall then require the parents to vow publicly their duty as Christian parents to present their children for baptism and to nurture them in the Christian faith, by answering these questions in the affirmative:</p>

> (1) Do you reaffirm your own faith in Jesus Christ as Savior and Lord?
> (2) Do you acknowledge your child&#8217;s need of the cleansing blood of Jesus Christ, and the renewing grace of the Holy Spirit?
> (3) Do you claim God&#8217;s covenant promises in [his/her] behalf and do you look in faith to the Lord Jesus Christ for [his/her] salvation, as you do for your own?
> (4) Do you now unreservedly dedicate your child to God, and promise, in humble reliance upon God’s grace, that you will seek to set before [him/her] a godly example, that you will pray with and for [him/her], that you will teach [him/her] the doctrines of our holy religion, and that you will strive, by all the tools which God has given us, to bring [him/her] up in the nurture and admonition of the Lord?

<p class="no-indent">The minister shall then require the congregation[^directoryForWorship.17] to vow publicly their duty to assist the parent(s) in the Christian nurture of the child:</p>

[^directoryForWorship.17]: If the session has permitted the parents' request for the baptism of an infant to take place in another church, the congregation present at the baptism should not take this vow. At a subsequent date, with explanation (especially in exclusively credo-baptistic churches), the vow should be administered to the home congregation.

<blockquote>
<p>Do you as a congregation undertake the responsibility of assisting the parents in the Christian nurture of this child? [If so, say, “We do.”]</p>
</blockquote>
</li>
<li class="no-indent"><strong>Prayer</strong>
<p class="no-indent">The minister shall then pray for the presence and blessing of the triune God, that the grace signified and sealed by baptism may be abundantly realized.</p>
</li>
<li class="no-indent"><strong>The Baptism</strong>
<p class="no-indent">Then, calling the child by name, the minister shall say, as he baptizes him with water, without adding any other ceremony:</p>
<blockquote>
<p>[Name of Child], I baptize you in the name of the Father and of the Son and of the Holy Spirit.</p>
</blockquote>
</li>
<li class="no-indent"><strong>Charge to the Parents</strong>
<p class="no-indent">It is then fitting that the minister give a charge to the parents in the following or like words:</p>
<blockquote>
<p>Beloved in Christ Jesus, we give thanks to God for this child that He has given you, and for your expressed desire for [him/her] to know the Lord and to follow Him all [his/her] days. Along with the great blessing of the gift of this child have come responsibilities that you have just acknowledged and to which you have solemnly committed yourselves, and I charge you to continue steadfastly in the commitments that you have made today before God and these witnesses, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.</p>
</blockquote>
</li>
<li class="no-indent"><strong>Prayer</strong>
<p class="no-indent">The whole service of baptism shall then be concluded with prayer. It is well in such prayer to thank the Lord for His covenant of grace, rejoice that this child has been included, and to ask the Lord to graciously enable him to be a covenant keeper, daily dying to sin and walking in newness of life in Christ.</p>
</li>
</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-58-a-note-on-infant-dedication" title="58. A Note on Infant Dedication">

## 58. A Note on Infant Dedication {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="58"></a>While infant dedication is not a sacrament, those who hold credo-baptist views may yet wish to present their child before the congregation, thanking God for his safe delivery, asking God’s blessing upon him, and testifying to God’s promises concerning our children. A suggested ceremony for infant dedication can be found in BCO <a href="#79">79</a>.</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-59-the-baptism-of-those-professing-faith" title="59. The Baptism of Those Professing Faith">

## 59. The Baptism of Those Professing Faith {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch59">
<li class="no-indent"><a id="59"></a><strong>Prerequisites</strong>
<p class="no-indent">He who seeks to be baptized shall make a public profession of his faith before the congregation prior to the baptism. He shall previously have received instruction in the Christian faith in accordance with the confessional standards of this Church, including instruction as to the meaning of baptism, and have also made before the session of the church a credible profession of faith in Christ according to the provisions of BCO <a href="#61.3">61.3</a>.</p>
</li>
<li class="no-indent"><strong>The Administration of Baptism to Those Professing Faith</strong>
<ol type="a">
<li class="no-indent"><strong>The Institution of the Sacrament</strong>
<p class="no-indent">The minister ought to read the words of the institution of the sacrament of baptism from a passage such as Matthew 28:18-20.</p>
</li>
<li class="no-indent"><strong>The Covenant Commitment of the One Receiving Baptism and the Congregation</strong>
<p class="no-indent">At the time of the service at which the person is to be baptized, he shall first profess his faith publicly before the assembled congregation. The minister may address him in these or like words:</p>

> Beloved in the Lord Jesus Christ, we thank our God for the grace that was given you, in that our Savior has sought and found you and through faith you have become a partaker of the covenant of grace. We rejoice that in His grace He has brought you to this congregation and given you the desire to profess your faith before us and to unite with us. We ask that you testify before us to the faith that you profess by giving assent to the following questions.

<p class="no-indent">To this end, the minister shall require the person to profess publicly his Christian faith by answering these questions in the affirmative:</p>

> (1) Do you believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ His only Son our Lord; and in the Holy Spirit, the Lord and Giver of life?
> (2) Do you acknowledge yourself to be a sinner in the sight of God, justly deserving His wrath, and without hope apart from His sovereign mercy?
> (3) Do you believe the Bible, consisting of the Old and New Testaments, to be the infallible Word of God, and its doctrine of salvation to be the perfect and only true doctrine of salvation?
> (4) Do you believe in the Lord Jesus Christ as the Son of God, and Savior&nbsp;of sinners, and do you receive and rest upon Him alone for salvation as&nbsp;He is offered in the Gospel?
> (5) Do you now resolve and promise, in humble reliance upon the grace of the Holy Spirit, that you will endeavor to live as a faithful follower of Christ?
> (6) Do you promise to support the Church in its worship and work to the best of your ability, to submit yourself to its government and discipline, and to strive for its purity and peace?

<p class="no-indent">The minister shall then require the congregation to vow publicly their duty to welcome into Christian fellowship those being baptized:</p>

> Do you, the members of this congregation, welcome this disciple [*or* these disciples] and promise by your fellowship to strengthen [his/her/their] tie[s] with the household of God? [If so, say, “We do.”]

<p class="no-indent">If the session deems it appropriate, it may also ask him to bear brief testimony to his faith in his own words.</p>
<p class="no-indent">After answers to the above questions in the affirmative, the minister shall proceed to the baptism.</p>
</li>
<li class="no-indent"><strong>The Meaning and Nature of the Sacrament</strong>
<p class="no-indent">The minister shall then summarize before the congregation the teaching of the Word of God and the Confession and Catechisms of this church as to the meaning and nature of the sacrament of baptism. He may use these or like words:</p>

> The Lord Jesus Christ instituted baptism as a covenant sign and seal for His church. He uses it not only for the solemn admission of the person who is baptized into the visible church, but also to depict and to confirm His ingrafting of that person into Himself and His including that person in the covenant of grace.
> 
> The Lord uses baptism to portray to us that we and our children are conceived and born in sin and need to be cleansed.
> 
> He uses it to witness and seal to us the remission of sins and the bestowal of all the gifts of salvation through union with Christ. Baptism with water signifies and seals cleansing from sin by the blood and the Spirit of Christ, together with our death unto sin and our resurrection unto newness of life by virtue of the death and resurrection of Christ. Because these gifts of salvation are the gracious provision of the triune God, who is pleased to claim us as His very own, we are baptized in the name of the Father and of the Son and of the Holy Spirit.
> 
> In our baptism, the Lord puts His name on us, claims us as His own, and summons us to assume the obligations of the covenant. He calls us to believe in Jesus Christ as our Savior, to renounce the devil, the world, and the flesh, and to walk humbly with our God in devotion to His commandments.

</li>
<li class="no-indent"><strong>Prayer</strong>
<p class="no-indent">Thereupon the minister shall pray for the presence and blessing of the triune God, that the grace signified and sealed by baptism may be abundantly realized.</p>
</li>
<li class="no-indent"><strong>The Baptism</strong>
<p class="no-indent">Then, calling the person by name, he shall baptize him with water, without any other ceremony, saying:</p>
<blockquote>
<p>[Name of Person], I baptize you in the name of the Father and of the Son and of the Holy Spirit.</p>
</blockquote>
</li>
<li class="no-indent"><strong>Welcome and Charge</strong>
<p class="no-indent">It is then fitting that the minister address the baptized person in the following or like words:</p>

> Beloved, in the name of the Lord Jesus Christ I welcome you to all the privileges of full communion with God’s people, and in particular to participation in the sacrament of the Holy Supper.
> 
> I charge you to continue steadfastly in the confession that you have made, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.
> 
> Rest assured that if you confess Christ before men, He will confess you before His Father who is in heaven.
> 
> May the God of all grace, who called you unto His eternal glory in Christ, after you have suffered a little while, perfect, establish, and strengthen you. To Him be the glory and dominion for ever and ever. Amen.

</li>
<li class="no-indent"><strong>Prayer</strong>
<p class="no-indent">The whole service of baptism shall be concluded with prayer. It is well in such a prayer to thank the Lord for His covenant of grace, rejoice that this brother has been included, and to ask the Lord to graciously enable him to be a covenant keeper, daily dying to sin and walking in newness of life in Christ.</p>
</li>
</ol>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-60-the-lords-supper" title="60. The Lord's Supper">

## 60. The Lord's Supper {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch60">
<li class="no-indent"><a id="60"></a><strong>General Provisions of the Lord’s Supper</strong>
<p class="no-indent">The Lord&#8217;s Supper is to be celebrated frequently, but the frequency may be determined by each session as it judges most conducive to edification. Where the Lord’s Supper is celebrated less frequently, public notice should be given to the congregation, at least the Sabbath before the administration of this ordinance, and either then, or on some day of the week, the people may be instructed in its nature, and urged to make due preparation for it, that all may come in a suitable manner to this holy feast. In accord with the historical practice of the church, the use of a loaf and common cup is commended as a faithful and rich observation of Christ’s commands for His Table. The senior pastor shall administer the Lord’s Supper. If he is unable, an assistant or associate pastor may administer it.</p>
</li>
<li class="no-indent"><strong>The Institution of the Sacrament</strong>
<p class="no-indent">The minister shall read the words of the institution and instruction of the Lord&#8217;s Supper as found in 1 Corinthians 11:23-29 or one of the Gospel accounts (Matthew 26:26-29, Mark 14:22-25, or Luke 22:14-20). In addition, he may read words of instruction from passages such as John 6 and 1 Corinthians 10.</p>
</li>
<li class="no-indent"><strong>The Meaning and Nature of the Sacrament</strong>
<p class="no-indent">The minister shall then summarize before the congregation the teaching of the Word of God as to the meaning and nature of the sacrament in the following or like words:</p>
<blockquote>
<p>Our Lord Jesus Christ instituted the Lord&#8217;s Supper as an ordinance to be observed by His church until He comes again. It is not a re-sacrificing of Christ, but is a remembrance of the once-for-all sacrifice of Himself in His death for our sins. Nor is it a mere memorial to Christ&#8217;s sacrifice. It is a means of grace by which God feeds us with the crucified, resurrected, exalted Christ. He does so by His Holy Spirit and through faith. Thus He strengthens us in our warfare against sin and in our endeavors to serve Him in holiness. The sacrament further signifies and seals the forgiveness of our sin and our nourishment and growth in Christ. The bread and wine represent the crucified body and the shed blood of the Savior, which He gave for His people. In this sacrament, God confirms that He is faithful and true to fulfill the promises of His covenant, and He calls us to deeper gratitude for our salvation, to renewed consecration, and to more faithful obedience. The Supper is also a bond and pledge of the communion that believers have with Him and with each other as members of His body. As Scripture says, &#8220;Since there is one bread, we who are many are one body; for we all partake of the one bread.&#8221;[^directoryForWorship.18] The Supper anticipates the consummation of the ages, when Christ returns to gather all His redeemed people at the glorious wedding feast of the Lamb. As we come to the Lord&#8217;s Table, we humbly resolve to deny ourselves, to crucify the sin that is within us, to resist the devil, and to follow Christ as becomes those who bear His name.</p>

[^directoryForWorship.18]: 1 Corinthians 10:17.

</blockquote>
</li>
<li class="no-indent"><strong>Invitation and Fencing the Table</strong>
<p class="no-indent">The minister shall then declare who may come to, and who are excluded from, the Lord&#8217;s Table according to the Word of God. He may use the following or like words:</p>

> We have heard, my brothers, how our Lord administered His Supper among His disciples, and in this He shows us that strangers, that is, those not of the company of the faithful should not be admitted. Following this rule, therefore, in the name and by the authority of our Lord Jesus Christ, I excommunicate all idolaters, blasphemers, despisers of God, heretics, and all who form separate parties to break the unity of the church, all perjurers, all those who rebel against their father and mother and against their superiors, all fomenters of sedition or mutiny, quarrelers, fighters, adulterers, fornicators, sexual deviants, thieves, lovers of money, plunderers, drunkards, gluttons, and all those who lead a scandalous life; declaring to those that they are to abstain from this holy table lest they pollute and contaminate this sacred food, which our Lord Jesus Christ gives only to His servants and faithful ones.
> 
> Therefore, according to the exhortation of the Apostle Paul, let each one test and examine his own conscience, to know whether he truly repents of his faults and is sorry for them, desiring from now on to live in holiness and in conformity with God; and above all, whether he trusts in the mercy of God and seeks his salvation wholly from Jesus Christ; and whether renouncing all hostility and malice, he has the good intention and the courage to live in harmony and brotherly love with his neighbors.
> 
> If we have such a testimony in our hearts before God, let us not doubt in the least that He acknowledges us to be His children and that the Lord Jesus is speaking to us, bringing us to His table and offering us this Holy Sacrament, which He delivered to His disciples.
> 
> And since we are conscious of much frailty and misery in ourselves, as well as not having a perfect faith, but that we are prone rather to unbelief and distrust, so that we are not entirely dedicated to serving God and with such a zeal as we ought, but we have instead a battle daily against the lusts of our flesh; nevertheless, since our Lord has granted us this grace of having His Gospel engraved on our heart, so that we might resist all unbelief, and He has given us the desire and longing to renounce our own desires to pursue His righteousness and holy commandments; let us all be assured that the sins and imperfections that are in us will not prevent Him from receiving us, nor from making us worthy to share in this spiritual table. For we do not come insisting that we are perfect or righteous in ourselves, but rather, seeking our life in Jesus Christ, we confess that we are dead. Let us understand, therefore, that this Sacrament is a medicine for poor, spiritually sick people and that the only worthiness that our Lord requires of us is to know ourselves well enough to be displeased with our sins and to find all our pleasure, joy, and contentment in Him alone.[^directoryForWorship.19]</p>

[^directoryForWorship.19]: From John Calvin’s Lord’s Supper liturgy, 1542, 1566, modernized. See Mark Earngey and Jonathan Gibson, *Reformation Worship* (New Growth Press, 2018), 326–27.

</blockquote>
</li>
<li class="no-indent"><strong>Exhortation</strong>
<p class="no-indent">If desired, the minister may exhort the people of God, in the following or other words, to embrace in the sign the thing that is signified:</p>
<blockquote>
<p>So let us first believe in these promises, which Jesus Christ, who is the infallible truth, spoke with His mouth, namely, that He truly wishes to make us partakers of His body and blood; that we might possess Him fully, so that He might live in us and we in Him. And since we see only bread and wine, yet we do not doubt that He accomplishes spiritually in our souls all that He demonstrates to us outwardly through these visible signs, namely, that He is the heavenly bread that feeds and nourishes us for eternal life. So let us be grateful for the infinite goodness of our Savior, who spreads out all His riches and goods on this table to distribute them to us. For by giving Himself to us, He testifies to us that all He has is ours. Therefore, let us receive this Sacrament as a seal that the power of His death and passion is imputed to us for righteousness, just as though we had suffered it ourselves. Let us therefore not be so wicked as to pull back from where Jesus Christ so gently invites us through His Word. But considering the worth of this precious gift which He has given us, let us present ourselves to Him with ardent zeal, so that He would make us able to receive it.[^directoryForWorship.20]</p>

[^directoryForWorship.20]: Ibid., 327–28.

<p>Beloved congregation, lift up your hearts from these visible elements even to heaven itself, where Jesus Christ is seated at the right hand of the Father, from where we look for Him to return and perfect our redemption. All the promises of God are yes and amen in Him. Every spiritual blessing is found in Him. With joyful hearts, in Christian love, partake of His Table, giving thanks for the great love that He has shown to us.</p>
</blockquote>
</li>
<li class="no-indent"><strong>Prayer</strong>
<p class="no-indent">The distribution of the elements shall be preceded by prayer. It is well in such prayer to praise God for His mighty power and grace in bringing salvation; confess our unworthiness to come to the Table because of our own utter lack of righteousness; reaffirm our trust in God&#8217;s grace and in Christ&#8217;s righteousness and mediation; plead for the Lord to grant the gracious, effectual working of His Spirit in us; thank God for the elements, request Him to use them for their intended purpose; and ask Him to grant that by faith His people may feed upon Jesus Christ, crucified and raised for them, so that, being strengthened by grace, they might live in Him and for Him.</p>
</li>
<li class="no-indent"><strong>Partaking of the Elements</strong>
<p class="no-indent">Normally,[^directoryForWorship.21] the elements of the Lord’s Supper should be taken in the following manner.</p>

[^directoryForWorship.21]: This portion of the Lord’s Supper liturgy follows the historical Reformed liturgies of the early Reformation. With the addition of the word “normally,” we do not intend to allow significant departure from this process of partaking of the elements. Intinction—the taking of the elements simultaneously by communicants—or the use of many individual cups does not *significantly* depart from the outlined process. The significance of both the bread and the cup should be described prior to eating and drinking.

<p class="no-indent">After prayer and thanksgiving, the minister shall take the bread, saying in the following or like words:</p>
<blockquote>
<p>Our Lord Jesus Christ, the same night in which He was betrayed, took bread, blessed it, broke it, and gave it to His disciples, as I, ministering in His name, give this bread to you.</p>
</blockquote>
<p class="no-indent">The minister shall then break the bread and give it to the people; it shall be distributed to the people by church officers, preferably the ruling elders, but in any case male officers. The bread may be eaten either upon reception of it, or in unison when all have been served, as the session may judge most conducive to edification. The minister may continue, before the bread is eaten, saying:</p>
<blockquote>
<p>Our Lord Jesus said, &#8220;Take, eat, this is My body, which is for you; do this in remembrance of Me.&#8221;</p>
</blockquote>
<p class="no-indent">Having given the bread, the minister shall take the cup and give it to the people, saying in the following or like words:</p>
<blockquote>
<p>In the same manner, our Savior also took the cup, and having given thanks as has been done in His name, He gave it to His disciples, as I ministering in His name give this cup to you.</p>
</blockquote>
<p class="no-indent">The minister shall then give the cup, as in the distribution of the bread; it shall be distributed to the people by church officers, preferably the ruling elders, but in any case male officers. The minister may continue, before the cup is drunk, saying:</p>
<blockquote>
<p>Our Lord Jesus said, &#8220;This cup is the new covenant in My blood, which is shed for many for the remission of sins; drink of it, all of you.&#8221;</p>
</blockquote>
</li>
<li class="no-indent"><strong>Response of Thanksgiving and Commitment</strong>
<p class="no-indent">When all have partaken, prayer or a congregational song should be offered. It is well in such prayer to give thanks for the sacrifice of Jesus Christ, through whom we have the forgiveness of sins; recommit God&#8217;s people to Christ and to each other; present them as a living sacrifice to God; and plead that the Holy Spirit will make the sacrament effectual to the edifying and strengthening of God&#8217;s people.</p>
<p class="no-indent">It is well that the congregation respond by singing a psalm or hymn that focuses on the benefits of Christ&#8217;s death and the triumph of the Gospel, bringing forth gratitude and joy and renewed commitment of the believer to His Lord, and that an offering be taken for the relief of the poor or for some other sacred purpose.</p>
</li>
<li class="no-indent"><strong>Blessing</strong>
<p class="no-indent">The following benediction is particularly appropriate when the Lord&#8217;s Supper has been celebrated:</p>
<blockquote>
<p>&#8220;Now the God of peace, who brought up from the dead the great Shepherd of the sheep through the blood of the eternal covenant, even Jesus our Lord, equip you in every good thing to do His will, working in us that which is pleasing in His sight, through Jesus Christ, to whom be the glory forever and ever. Amen.”[^directoryForWorship.22]</p>

[^directoryForWorship.22]: Hebrews 13:20-21.

</blockquote>
</li>
</ol>
<p class="no-indent">*The above exhortations and explanations are in accord with the historic Reformed liturgies.*</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-61-public-reception-of-church-members-general-provisions" title="61. Public Reception of Church Members—General Provisions">

## 61. Public Reception of Church Members—General Provisions {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch61">
<li class="no-indent"><a id="61"></a>Only those may be admitted to full communion in the church who have been baptized and have made public profession of faith in Jesus Christ.</li>
<li class="no-indent">In order to aid those who contemplate making public profession or reaffirmation of faith in Christ to understand the implication of this significant act and to perform it meaningfully, the pastor or someone approved by the session shall conduct classes in Christian doctrine and life, both for the children of the church and for any others who may manifest an interest in the way of salvation.</li>
<li class="no-indent"><a id="61.3"></a>In order for the session to assure itself so far as possible that the candidate makes a credible profession, it shall examine him to ascertain that he possesses the knowledge requisite for saving faith in the Lord Jesus Christ, relies on the merits of Christ alone, and is determined by the grace of God to lead a Christian life.</li>
<li class="no-indent">In the public reception of church members, the minister shall follow the directions prescribed in this chapter, but he is not required to use the exact language of the forms (below), which are suggested as appropriate. He may employ these or similar forms, using his own liberty and godly wisdom as he deems best for the edification of the people.</li>
<li class="no-indent">Whether baptized or unbaptized, children of communing members are non-communing members of the particular church and come to the Lord’s Table, also, by a credible profession of faith. Normally such professions should be actively sought in the regular course of the elder board’s shepherding work. Because God has limited the ability of infants and very young children to articulate a credible profession of faith, demonstrate the fruit of repentance, and discern the Lord’s body, they do not yet qualify for admission to communicant membership and the Lord’s Table.[^directoryForWorship.23] For further explanation, see BCO <a href="#1.3">1.3</a>.</li>

[^directoryForWorship.23]: Calvin’s process for allowing covenant children to come to the Lord’s Supper is described by Scott Manetsch as follows: “By the time that students completed their studies at the schola privata at age eleven or twelve, they would have worked through Calvin’s *Catechism* six or seven times and most would have mastered its doctrinal contents. It is important to note, however, that admission to the Lord’s Table was not tied directly to a child’s level of schooling or age. The *Ecclesiastical Ordinances* made clear that boys and girls were welcomed to the Lord’s Supper only after they had reached the age of discretion (around ten years of age) and were able satisfactorily to articulate the basic doctrines of the reformed religion and confess it as their own. Toward that end, four times a year on the Sunday before Geneva’s quarterly communion service, young people who were prepared to confess their Christian faith stood in front of the worshiping congregation and, in response to the ministers’ questions, recited the shortened form of the *Catechism* that served as their formal profession of faith. A week later, they were invited for the first time to feed upon the body and blood of Jesus Christ offered in the sacred meal of the Lord’s Table.” *Calvin’s Company of Pastors: Pastoral Care and the Emerging Reformed Church, 1536-1609* (Oxford University Press, 2013), 270-71. Additionally: “Another primary source, though, describes the age of discretion and Geneva’s children coming to the Lord’s table as between ages eight and ten: ‘Throughout all this, somebody else reads from the pulpit in the vernacular, with head uncovered, the Gospel of Saint John, from the beginning of the thirteenth chapter, until everyone has taken their pieces, both men and women, each one at their different tables, along with the boys and girls of around eight to ten years of age.’” Ibid., 275, quoting Antoince Cathelan, *Passevent Parisien*, 74.

<li class="no-indent">If they have been baptized, non-communing members of the congregation may be received into communicant membership by profession of faith.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-62-reception-into-full-communion-of-non-communing-members-by-profession-of-faith" title="62. Reception into Full Communion of Non-communing Members by Profession of Faith">

## 62. Reception into Full Communion of Non-communing Members by Profession of Faith {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch62">
<li class="no-indent"><a id="62"></a>When a non-communing member who was baptized as an infant is received into full communion, that reception is effective at the time of his public profession of faith. On the occasion of that person’s public reception, it is highly advisable that the minister remind the people that he is already a member of the church, albeit a non-communing member, and has been receiving the blessings of Christ as a member of the church, and that those blessings have resulted in this day wherein, having given evidence of conscious saving faith in Christ, he is now about to confess that faith and become a communing member of the congregation. The minister may then address him in these or like words:<br />
<blockquote>
<p>Beloved in the Lord Jesus Christ, we thank our God for the grace that was given you, in that you have accepted God’s covenant promise that was signified and sealed unto you in your infancy by holy baptism. We ask you now to profess your faith publicly.</p>
</blockquote>
</li>
<li class="no-indent"><p>The minister shall then require the person to profess publicly his Christian faith by giving assent to these questions:</p>

> (1) Do you believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ His only Son our Lord; and in the Holy Spirit, the Lord and Giver of life?
> (2) Do you acknowledge yourself to be a sinner in the sight of God, justly deserving His wrath, and without hope apart from His sovereign mercy?
> (3) Do you believe the Bible, consisting of the Old and New Testaments, to be the infallible Word of God, and its doctrine of salvation to be the perfect and only true doctrine of salvation?
> (4) Do you believe in the Lord Jesus Christ as the Son of God, and Savior&nbsp;of sinners, and do you receive and rest upon Him alone for salvation as&nbsp;He is offered in the Gospel?
> (5)<a id="62.2.5"></a> Do you now resolve and promise, in humble reliance upon the grace of the Holy Spirit, that you will endeavor to live as a faithful follower of Christ?
> (6) Do you promise to support the Church in its worship and work to the best of your ability, to submit yourself to its government and discipline, and to strive for its purity and peace?

<p>If the session deems it appropriate, it may also ask him to bear brief testimony to his faith in his own words.</p>
</li>
<li class="no-indent">It is appropriate that the minister exhort the congregation in these or like words:<br />
<blockquote>
<p>From the time [Name] was baptized, the whole congregation has been obligated to love and receive [him/her] as a member of the church. As [he/she] is received into full communion, the congregation is reminded of these obligations. For in Christ we are members of one another. Christ claims this [brother/sister] as His own and calls you to receive [him/her] in love and commitment. Therefore, you ought to commit yourself before God to assist [Name] in [his/her] Christian nurture by godly example, prayer, and encouragement in our most precious faith and in the fellowship of believers.</p>
</blockquote>
</li>
<li class="no-indent">When anyone has publicly professed his faith in this way, it is fitting that the minister address him in the following or similar words:<br />


> Beloved, in the name of the Lord Jesus Christ I welcome you to all the privileges of full communion with God’s people, and in particular to participation in the sacrament of the Holy Supper.
> 
> I charge you to continue steadfastly in the confession that you have made, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.
> 
> Rest assured that if you confess Christ before men, He will confess you before His Father who is in heaven.
> 
> May the God of all grace, who called you unto His eternal glory in Christ, after you have suffered a little while, perfect, establish, and strengthen you. To Him be the glory and dominion for ever and ever. Amen.

<p>This part of the service shall be concluded with prayer.</p>
</li>
</ol>
<p class="no-indent">*For children of paedo-baptistic parents making a profession of faith in a credo-baptistic church, please see BCO <a href="#66.3">66.3</a>, <a href="#66.4">66.4</a>.*</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-63-reception-by-letter-of-transfer-from-another-church-within-evangel-presbytery" title="63. Reception by Letter of Transfer from Another Church within Evangel Presbytery">

## 63. Reception by Letter of Transfer from Another Church within Evangel Presbytery {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="63"></a>When a person is received into membership on letter of transfer from another Evangel Presbytery congregation, that reception is effective at the time of the action of the session to receive him. Nevertheless, a session may deem it appropriate to welcome that person publicly into the congregation and allow him to give public expression to his faith. If this is done, it shall be made clear to the congregation that the person has already been received by action of the session. Nevertheless, the minister may address him in appropriate words similar to those found below in BCO <a href="#64.4">64.4</a>.</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-64-reception-by-letter-of-transfer-from-another-church-of-like-faith-and-practice" title="64. Reception by Letter of Transfer from Another Church of Like Faith and Practice">

## 64. Reception by Letter of Transfer from Another Church of Like Faith and Practice {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch64">
<li class="no-indent"><a id="64"></a>When a person is received into membership on letter of transfer from another church of like faith and practice approved by the session, that reception is effective at the time of his public profession of faith. On the occasion of that person&#8217;s public reception, the minister shall address him in these or like words:<br />
<blockquote>
<p>Beloved in the Lord Jesus Christ, we thank our God for the grace that was given you, in that you have accepted God&#8217;s promise of salvation and publicly confessed your faith in the Savior, Jesus Christ. We praise Him that He brought you into communicant membership in a church of like faith and practice with this congregation. We rejoice that God, in His gracious providence, has now brought you here and given you a desire to unite with us, and that your former church has committed you to our fellowship and oversight. We ask that you testify before us to the faith that you profess by giving assent to the following questions.</p>
</blockquote>
</li>
<li class="no-indent"><p>The minister shall then require the person to profess publicly his Christian faith by giving assent to these questions:</p>

> (1) Do you believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ His only Son our Lord; and in the Holy Spirit, the Lord and Giver of life?
> (2) Do you acknowledge yourself to be a sinner in the sight of God, justly deserving His wrath, and without hope apart from His sovereign mercy?
> (3) Do you believe the Bible, consisting of the Old and New Testaments, to be the infallible Word of God, and its doctrine of salvation to be the perfect and only true doctrine of salvation?
> (4) Do you believe in the Lord Jesus Christ as the Son of God, and Savior of sinners, and do you receive and rest upon Him alone for salvation as He is offered in the Gospel?
> (5) Do you now resolve and promise, in humble reliance upon the grace of the Holy Spirit, that you will endeavor to live as a faithful follower of Christ?
> (6) Do you promise to support the Church in its worship and work to the best of your ability, to submit yourself to its government and discipline, and to strive for its purity and peace?

<p>If the pastor deems it appropriate, he may also ask him to bear brief testimony to his faith in his own words.</p>
</li>
<li class="no-indent">The minister may exhort the congregation in these or like words:<br />
<blockquote>
<p>As [Name] is received into full communion in the church, the whole congregation is obligated to receive [him/her], for in Christ we are members of one another. Christ claims this [brother/sister] as His own and calls you to serve [him/her] in love. Therefore, you ought to commit yourself before God to assist [Name] in [his/her] Christian nurture by godly example, prayer, and encouragement in our most precious faith and in the fellowship of believers.</p>
</blockquote>
</li>
<li class="no-indent"><a id="64.4"></a>When anyone has publicly professed his faith in this way, it is fitting that the minister address him in the following or like words:<br />

> Beloved, in the name of the Lord Jesus Christ I welcome you to all the privileges of full communion with this congregation of God&#8217;s people.
> 
> I charge you to continue steadfastly in the confession that you have made, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.
> 
> Rest assured that if you confess Christ before men, He will confess you before His Father who is in heaven.
> 
> May the God of all grace, who called you unto His eternal glory in Christ, after you have suffered a little while, perfect, establish, and strengthen you. To Him be the glory and dominion for ever and ever. Amen.

<p>This part of the service shall be concluded with prayer.</p>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-65-reception-by-reaffirmation-of-faith" title="65. Reception by Reaffirmation of Faith">

## 65. Reception by Reaffirmation of Faith {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch65">
<li class="no-indent"><a id="65"></a>When a person is received into membership by reaffirmation of faith, that reception is effective at the time of his public profession of faith. On the occasion of that person&#8217;s public reception, the minister shall address him in these or like words:<br />
<blockquote>
<p>Beloved in the Lord Jesus Christ, we thank our God for the grace that was given you, in that you have accepted God&#8217;s promise of salvation and publicly confessed your faith in the Savior, Jesus Christ. We rejoice that God, in His gracious providence, has brought you into this congregation and given you a desire to reaffirm the faith that you have previously professed, and to unite with us. We ask that you testify before us to the faith that you profess by giving assent to the following questions.</p>
</blockquote>
</li>
<li class="no-indent">The minister shall then require the person to profess publicly his Christian faith by giving assent to these questions:<br />

> (1) Do you believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ His only Son our Lord; and in the Holy Spirit, the Lord and Giver of life?
> (2) Do you acknowledge yourself to be a sinner in the sight of God, justly deserving His wrath, and without hope apart from His sovereign mercy?
> (3) Do you believe the Bible, consisting of the Old and New Testaments, to be the infallible Word of God, and its doctrine of salvation to be the perfect and only true doctrine of salvation?
> (4) Do you believe in the Lord Jesus Christ as the Son of God, and Savior of sinners, and do you receive and rest upon Him alone for salvation as He is offered in the Gospel?
> (5) Do you now resolve and promise, in humble reliance upon the grace of the Holy Spirit, that you will endeavor to live as a faithful follower of Christ?
> (6) Do you promise to support the Church in its worship and work to the best of your ability, to submit yourself to its government and discipline, and to strive for its purity and peace?

<p>If the pastor deems it appropriate, it may also ask him to bear brief testimony to his faith in his own words.</p>
</li>
<li class="no-indent">It is appropriate that the minister exhort the congregation in these or like words:<br />
<blockquote>
<p>As [Name] is received into full communion in the church, the whole congregation is obligated to receive (him/her), for in Christ we are members of one another. Christ claims this (brother/sister) as His own and calls you to serve (him/her) in love. Therefore, you ought to commit yourself before God to assist [Name] in (his/her) Christian nurture by godly example, prayer, and encouragement in our most precious faith and in the fellowship of believers.</p>
</blockquote>
</li>
<li class="no-indent">When anyone has publicly professed his faith in this way, it is fitting that the minister address him in the following or like words:<br />
<blockquote>
<p>Beloved, in the name of the Lord Jesus Christ I welcome you to all the privileges of full communion with this congregation of God&#8217;s people.</p>
</blockquote>
<blockquote>
<p>I charge you to continue steadfastly in the confession that you have made, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.</p>
</blockquote>
<blockquote>
<p>Rest assured that if you confess Christ before men, He will confess you before His Father who is in heaven.</p>
</blockquote>
<blockquote>
<p>May the God of all grace, who called you unto His eternal glory in Christ, after you have suffered a little while, perfect, establish, and strengthen you. To Him be the glory and dominion for ever and ever. Amen.</p>
</blockquote>
<p>This part of the service shall be concluded with prayer.</p>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-66-reception-of-new-members-by-public-profession-of-faith" title="66. Reception of New Members by Public Profession of Faith">

## 66. Reception of New Members by Public Profession of Faith {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch66">
<li class="no-indent">When an unbaptized person is received into membership by profession of faith, that reception is effective at the time of his public profession of faith and baptism. He shall be received in accord with BCO <a href="#59">59</a>. When a previously baptized person who is not a member of the congregation and has not previously made a confession of his faith is received into membership by profession of faith, that reception is effective at the time of his public profession of faith. On the occasion of that person’s public reception, the minister shall address him in these or like words:<br />
<blockquote>
<p>Beloved in the Lord Jesus Christ, we thank our God for the grace that was given you, in that our Savior has sought and found you and through faith you have become a partaker of the covenant of grace. We rejoice that in His grace He has brought you to this congregation and given you the desire to profess your faith before us and to unite with us. We ask that you testify before us to the faith that you profess by giving assent to the following questions.</p>
</blockquote>
</li>
<li class="no-indent">The minister shall then require the person to profess publicly his Christian faith by giving assent to these questions:<br />

> (1) Do you believe in God the Father Almighty, Maker of heaven and earth; and in Jesus Christ His only Son our Lord; and in the Holy Spirit, the Lord and Giver of life?
> (2) Do you acknowledge yourself to be a sinner in the sight of God, justly deserving His wrath, and without hope apart from His sovereign mercy?
> (3) Do you believe the Bible, consisting of the Old and New Testaments, to be the infallible Word of God, and its doctrine of salvation to be the perfect and only true doctrine of salvation?
> (4) Do you believe in the Lord Jesus Christ as the Son of God, and Savior&nbsp;of sinners, and do you receive and rest upon Him alone for salvation as&nbsp;He is offered in the Gospel?
> (5) Do you now resolve and promise, in humble reliance upon the grace of the Holy Spirit, that you will endeavor to live as a faithful follower of Christ?
> (6) Do you promise to support the Church in its worship and work to the best of your ability, to submit yourself to its government and discipline, and to strive for its purity and peace?

<p>If the pastor deems it appropriate, he may also ask him to bear brief testimony to his faith in his own words.</p>
</li>
<li class="no-indent"><a id="66.3"></a>It is appropriate that the minister exhort the congregation in these or like words:<br />
<blockquote>
<p>As [Name] is received into full communion in the church, the whole congregation is obligated to receive (him/her), for in Christ we are members of one another. Christ claims this (brother/sister) as His own and calls you to serve (him/her) in love. Therefore, you ought to commit yourself before God to assist [Name] in (his/her) Christian nurture by godly example, prayer, and encouragement in our most precious faith and in the fellowship of believers.</p>
</blockquote>
</li>
<li class="no-indent"><a id="66.4"></a>When anyone has publicly professed his faith in this way, it is fitting that the minister address him in the following or like words:<br />
<blockquote>
<p>Beloved, in the name of the Lord Jesus Christ I welcome you to all the privileges of full communion with God’s people, and in particular to participation in the sacrament of the Holy Supper.</p>
</blockquote>
<blockquote>
<p>I charge you to continue steadfastly in the confession that you have made, humbly relying upon the grace of God in the diligent use of the means of grace—especially the Word of God, the sacraments, and prayer.</p>
</blockquote>
<blockquote>
<p>Rest assured that if you confess Christ before men, He will confess you before His Father who is in heaven.</p>
</blockquote>
<blockquote>
<p>May the God of all grace, who called you unto His eternal glory in Christ, after you have suffered a little while, perfect, establish, and strengthen you. To Him be the glory and dominion for ever and ever. Amen.</p>
</blockquote>
<p>This part of the service shall be concluded with prayer.</p>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-67-other-occasions-of-public-worship" title="67. Other Occasions of Public Worship">

## 67. Other Occasions of Public Worship {-}

<p data-type="subtitle" class="chapter-number"></p>
<p><a id="67"></a>Under the Gospel, we are commanded to keep no other particular day holy, except the Lord&#8217;s Day. Nevertheless, God&#8217;s people may observe other occasions of worship as the Lord allows. Such observance is both consonant with Scripture and pastorally appropriate.</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-68-prayer-meetings" title="68. Prayer Meetings">

## 68. Prayer Meetings {-}

<p data-type="subtitle" class="chapter-number"></p>
<p><a id="68"></a>Prayer meetings for the purpose of corporate prayer should be held under the direction of the Session. They may be conducted by the Pastor or member of the session. They may also be conducted by other members of the church when so authorized by the session. The exercises appropriate for the prayer meeting are prayer, reading of Scriptures, instruction and exhortation by men. All of the people of the church, young and old, male and female, should be encouraged to pray aloud in public and so have an active part in the prayer meeting.</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-69-prayer-and-fasting" title="69. Prayer and Fasting">

## 69. Prayer and Fasting {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch69">
<li class="no-indent"><a id="69"></a>When great and notable calamities come upon or threaten the church, community, or nation, when judgment is deserved because of sin, when the people seek some special blessing from the Lord, or when a pastor is to be ordained or installed, it is fitting that the people of God engage in times of solemn prayer and fasting.</li>
<li class="no-indent">Prayer and fasting may be observed by private individuals and families at their discretion or by the Church at the discretion of the appropriate judicatory. If the civil authority calls for a time of prayer and fasting that the judicatories of the Church deem to be in harmony with the Scriptures, they should consider issuing such a call to their members.</li>
<li class="no-indent">Public notice is to be given before the time of prayer and fasting comes, to enable persons to order their temporal affairs so that they can participate.</li>
<li class="no-indent">It is especially appropriate on days of prayer and fasting called by the Church that the people of God gather for a time of prayer, the singing of psalms and hymns, and the reading and preaching of the Word of God. Let them lament their distress or unworthiness before the Lord, confess their sins, humbly implore the Lord for deliverance from the judgment present or imminent or for the blessing sought, and commit themselves anew to the faithful service of the Lord their God. It is fitting on such days that God&#8217;s people abstain from food and from such activities as may distract from their solemn engagement in prayer.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-70-thanksgiving" title="70. Thanksgiving">

## 70. Thanksgiving {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch70">
<li class="no-indent"><a id="70"></a>1. When God&#8217;s blessings on the church, community, or nation are particularly evident, it is fitting that the people of God engage in special times of thanksgiving.</li>
<li class="no-indent">Special times of thanksgiving may be observed by private individuals and families at their discretion or by the Church as called by the appropriate judicatory. If the civil authority calls for a time of thanksgiving that the judicatories of the Church deem to be in harmony with the Scriptures, they should consider issuing such a call to their members.</li>
<li class="no-indent">Public notice is to be given before the day of thanksgiving comes, to enable persons to order their temporal affairs so that they can participate.</li>
<li class="no-indent">It is especially appropriate on special days of thanksgiving called by the Church that the people of God gather for prayer, testimony to God&#8217;s blessings, joyful singing of psalms and hymns, and the reading and preaching of the Word of God. Let them give thanks to God for His goodness to His people and especially for the greatness of His mercies to them in Christ. And let them commit themselves anew to the faithful service of the Lord their God in gratitude for His blessings. It is fitting on such days that God&#8217;s people spend the day in expressions of Christian love and charity toward one another, rejoicing more and more in the Lord, as becomes those who make the joy of the Lord their strength. Also, they may feast together before the Lord with joy and thanksgiving.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-71-home-fellowship-groups" title="71. Home Fellowship Groups">

## 71. Home Fellowship Groups {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch71">
<li class="no-indent"><a id="71"></a>It is fitting for church members to gather in each other’s homes on the Lord’s Day and other days, eating together, discussing and applying the preaching of God’s Word, studying the Scriptures, singing praises, confessing sins, praying for one another and bearing one another’s burdens.</li>
<li class="no-indent">Such a gathering is no substitute for the public worship of the local church on the Lord’s Day.</li>
<li class="no-indent">Officers of the church may lead these groups or leadership may be delegated to other faithful men. Pastors and elders should maintain frequent communication with group leaders, both to ensure that those leaders are leading a holy life, and to be made aware of pastoral needs of those involved in the group.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-72-the-solemnization-of-marriage" title="72. The Solemnization of Marriage">

## 72. The Solemnization of Marriage {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch72">
<li class="no-indent"><a id="72"></a>Marriage is a divine institution though not a sacrament, nor peculiar to the Church of Christ. It is proper that every commonwealth, for the good of society, make laws to regulate marriage, which all citizens are bound to obey insofar as they do not transgress the laws of God.[^directoryForWorship.24]</li>

[^directoryForWorship.24]: Acts 5:29.

<li class="no-indent">Christians should marry in the Lord; therefore it is appropriate that their marriage be solemnized by a lawful minister, that special instruction be given them, and suitable prayers offered, when they enter into this relation.</li>
<li class="no-indent"><a id="72.3"></a>During the solemnization of the marriage, the three Scriptural purposes of marriage as described by the Westminster Confession of Faith shall be stated: “Marriage was ordained for the mutual help of husband and wife, for the increase of mankind with a legitimate issue, and of the Church with an holy seed; and for preventing of uncleanness.” Additionally, the man is required to vow to love and cherish the woman, and the woman is required to vow to love, cherish, and obey the man.</li>
<li class="no-indent">Marriage is to be a lifelong, monogamous union between one man and one woman,[^directoryForWorship.25] in accordance with the Word of God.</li>

[^directoryForWorship.25]: For the intended meaning of the words “man” and “woman,” please refer to BCO <a href="#28">28</a>, particularly <a href="#28.7">section 7</a>.

<li class="no-indent">The parties should be of such years of discretion as to be capable of making their own choice; and if they be under age, or live with their parents, the consent of the parents or others, under whose care they are, should be previously obtained, and well proven to the minister before he proceeds to solemnize the marriage.</li>
<li class="no-indent">Parents should neither compel their children to marry contrary to their will, nor deny their consent without just and significant reasons.</li>
<li class="no-indent">Marriage and the welfare of civil society cannot be separated. The happiness of families and the credit of Christianity are deeply interested in it. Therefore, the intent to marry should be sufficiently published for objections to the marriage to be registered in a timely way, and for them to be adjudicated.[^directoryForWorship.26] Ministers should be careful that they obey the laws of the community to the extent that those laws do not transgress the laws of God as declared by the Constitution of Evangel Presbytery; and that they not destroy the peace and comfort of families, ministers should be assured that, with respect to the parties applying to them, no just objections lie against their marriage.</li>

[^directoryForWorship.26]: This requirement is based upon the ancient practice of “publishing the banns.” In Calvin’s Geneva, for example, it was required that the minister publish the banns—that is, announce to the congregation the intent of a couple to marry—for the three Sundays preceding the wedding. This announcement allowed those who objected to the wedding to explain their reasons to the minister. It also taught the congregation about the public and solemn nature of the wedding ceremony. For more on Calvin’s practice, see John Witte Jr. and Robert M. Kingdon, *Courtship, Engagement, and Marriage*, vol. 1 of *Sex, Marriage, and Family Life in John Calvin’s Geneva* (Eerdmans, 2005).

</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-73-the-visitation-of-the-sick" title="73. The Visitation of the Sick">

## 73. The Visitation of the Sick {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch73">
<li class="no-indent"><a id="73"></a>The power of the prayer of faith is great, and Christians therefore should pray for the sick at the throne of heavenly grace, and should also seek God’s blessing upon all proper means which are being employed for their recovery. Moreover, when persons are sick, their minister, or some officer of the church, should be notified, that the minister, officers, and members may unite their prayers for the sick. It is the privilege and duty of the pastor to visit the sick and to minister to their physical, mental, and spiritual welfare.</li>
<li class="no-indent">In view of the varying circumstances of the sick, the minister should use discretion in the performance of this duty. In some circumstances, the minister will be wise to encourage women to visit other women who are sick or in need of care. For those unable to attend services for extended periods of time, the sacraments may be administered to them by a senior pastor or associate pastor only when a subset of the members of the congregation is gathered in their residence. A short exposition of the Word of God should always accompany the application of baptism or the celebration of the Lord’s Supper. Those gathered, and in good standing, should all partake of the Lord’s Supper together.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-74-worship-in-the-home" title="74. Worship in the Home">

## 74. Worship in the Home {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch74">
<li class="no-indent"><a id="74"></a>In addition to public worship, it is the duty of each person in private, and of every family in private, to worship God.</li>
<li class="no-indent">Private worship is commanded by our Lord. In this duty everyone, should spend some time in prayer, reading the Scriptures, holy meditation, and serious self-examination.</li>
<li class="no-indent">Family worship, which should be observed by every family, should consist in prayer, reading the Scriptures, and singing praises, even if briefly.</li>
<li class="no-indent">Parents should instruct their children in the Word of God, and in the principles of our holy religion. The reading of devotional literature should be encouraged and every proper opportunity for biblical instruction should be gladly embraced.</li>
<li class="no-indent">Parents should set an example of piety and consistent living before the family. The Lord’s Day should be sanctified and left free for worship, rest, and works of mercy.</li>
<li class="no-indent">In the task of Christian education, parents should cooperate with the Church by setting their children an example in regular and punctual attendance at religious instruction provided by the church and services of worship, by assisting them in the preparation of their lessons, and by leading them in the consistent application of the teachings of the Gospel in their daily activities.</li>
</ol>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-75-suggested-form-for-the-solemnization-of-marriage" title="75. Suggested Form for the Solemnization of Marriage">

## 75. Suggested Form for the Solemnization of Marriage {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="75"></a>*The requirements of BCO <a href="#72">72</a>, particularly <a href="#72.3">section 3</a>, are required regardless of what liturgy is used for the marriage ceremony.*</p>
<p class="no-indent">*The form that follows in this section is based upon the marriage solemnization found in the 1549 Book of Common Prayer*</p>
<p>Prelude</p>
<p>Seating of Mothers</p>
<p>Bridal Party’s Entrance</p>
<p>Bride’s Entrance</p>
<p>Words of Institution</p>
<p style="text-align: center">*The Minister says,*</p>

> Dearly beloved, we are gathered here together in the sight of God, and in the presence of these witnesses, to join together this man and this woman in holy matrimony. Marriage is an honorable estate, instituted by God in the garden in the time of man’s innocence, before the corruption of sin, and signifying unto us the mystical union between Christ and His Church. This holy estate Christ adorned and beautified with His presence and first miracle in Cana of Galilee, and is commended by St. Paul to be honorable among all men.
> 
> Therefore, it is not to be entered into lightly or unadvisedly, nor is it to be undertaken loosely as satisfaction for carnal lusts, as if men were unrestrained animals with no understanding; but rather, it is to be sought reverently, discreetly, advisedly, soberly, and in the fear of God. In ordaining the gift of marriage, our Lord has commended to us three purposes for it. First, marriage is given for the mutual society, help, and comfort that man and wife should have from the other, both in prosperity and adversity. Second, marriage is given for the procreation of children, to be brought up in the fear and nurture of the Lord, and to the praise of God. Third, marriage is instituted as a remedy against sin, and to avoid fornication, so that those who are married might live in the purity of marriage, and keep themselves undefiled as members of Christ’s body.
> 
> Into this holy estate this man and this woman come now to be joined.
> 
> If any man can show just cause why they may not lawfully be joined, let him speak now, or else hereafter forever hold his peace.

<p style="text-align: center">*And also speaking to the persons to be married, he shall say,*</p>
<blockquote>
<p>I require and charge you both, that if either of you know any reason why you may not lawfully be joined in matrimony, you tell it to me. For you can be certain that all who are joined together in any way besides what God’s word allows are not joined by God, nor is their marriage lawful, and they will answer on the dreadful day of judgement, when the secrets of all hearts shall be revealed.</p>
</blockquote>
<p style="text-align: center">*At this time, if anyone raises an objection why the couple may not be joined together in matrimony, and is willing to stand by his allegation while it is investigated, then the marriage must be deferred, until the truth is found.*</p>
<p>Declaration of Consent</p>
<p style="text-align: center">*If no objection is raised, then the minister shall say unto the man,*</p>
<blockquote>
<p>[Name of Groom], will you have this woman to be your wedded wife, to live together after God’s ordinance in the holy estate of matrimony? Will you love her, comfort her, honor, and keep her in sickness and in health? And, forsaking all others, keep yourself only unto her, so long as you both shall live?</p>
</blockquote>
<p style="text-align: center">*The man shall answer,*</p>
<blockquote>
<p>I will.</p>
</blockquote>
<p style="text-align: center">*Then the minister shall say to the woman,*</p>
<blockquote>
<p>[Name of Bride], will you have this man to be your wedded husband, to live together after God’s ordinance, in the holy estate of matrimony? Will you obey him, and serve him, love, honor, and keep him in sickness and in health? And, forsaking all others, keep yourself only unto him, so long as you both shall live?</p>
</blockquote>
<p style="text-align: center">*The woman shall answer,*</p>
<blockquote>
<p>I will.</p>
</blockquote>
<p style="text-align: center">*Then shall the Minister say,*</p>
<blockquote>
<p>Who gives this woman to be married to this man?</p>
</blockquote>
<p style="text-align: center">*The father of the bride or a man standing in his place shall say,*</p>
<blockquote>
<p>I do.</p>
</blockquote>
<p style="text-align: center;padding-left: 30px">*Then the minister, receiving the woman at her father’s or friend’s hands, will cause the man to take the woman by the right hand.*</p>
<p>Invocation</p>
<blockquote>
<p>Let us pray. Almighty and ever blessed God, whose presence is the happiness of every condition and whose favor makes holy every relation; We ask You to be present and to look with favor upon these Your servants, as together they make their covenant before You. As You have brought them together by Your providence, sanctify them by Your Spirit, giving them a new frame of heart fit for their new estate. Pour out Your grace upon them so that they may enjoy the comforts, bear up under the cares, endure the trials, and perform the duties of life together under Your heavenly guidance and protection. May they be truly joined in the honorable estate of marriage, and may they know the salvation of the only true God. We ask these things through our Lord Jesus Christ. Amen.</p>
</blockquote>
<p style="text-align: center">*The Minister, Bride and Groom, Maid of Honor and Best Man, ascend to platform.*</p>
<p>Song</p>
<p>Scripture Reading (for example, Genesis 2:18-25, Ephesians 5:22-33)</p>
<p>Sermon</p>
<p>Exchange of Vows</p>
<p style="text-align: center">*The man and the woman turn and face each other and join hands. The man will say, repeating after the minister,*</p>
<blockquote>
<p>I [Name of Groom] take you [Name of Bride] to be my lawful wedded wife, to have and to hold from this day forward, for better, for worse, for richer, for poorer, in sickness, and in health, to love and to cherish, till death us do part: according to God’s holy ordinance; and to this vow I pledge you my faithfulness.</p>
</blockquote>
<p style="text-align: center">*The woman will say, repeating after the minister,*</p>
<blockquote>
<p>I [Name of Bride] take you [Name of Groom] to be my lawful wedded husband, to have and to hold from this day forward, for better, for worse, for richer, for poorer, in sickness, and in health, to love, cherish, and to obey, till death us do part: according to God’s holy ordinance; and to this vow I give you my faithfulness.</p>
</blockquote>
<p>Ring Ceremony</p>
<p style="text-align: center">*The minister will say to the man,*</p>
<blockquote>
<p>[Name of Groom], what keepsake do you give [Name of Bride] of your promise to fulfill these vows you have made?</p>
</blockquote>
<p style="text-align: center">*The best man gives the ring to the groom; the groom says, “This ring.” The groom takes the bride’s left hand the puts the ring on her fourth finger. The man says, repeating after the minister,*</p>
<blockquote>
<p>As a pledge and symbol of the vows we have made, with this ring I thee wed, with my body I thee honor: and all my worldly goods I give to thee. In the name of the Father, and of the Son, and of the Holy Spirit. Amen.</p>
</blockquote>
<p style="text-align: center">*The minister will say to the woman,*</p>
<blockquote>
<p>[Name of Bride], what keepsake do you give [Name of Groom] of your promise to fulfill these vows you have made?</p>
</blockquote>
<p style="text-align: center">*The maid of honor gives the ring to the bride; the bride says, “This ring.” The bride takes the groom’s left hand the puts the ring on his fourth finger. The woman says, repeating after the minister,*</p>
<blockquote>
<p>As a pledge and symbol of the vows we have made, with this ring I am wedded to thee, in the name of the Father, and of the Son, and of the Holy Spirit. Amen.</p>
</blockquote>
<p>Prayer</p>

> Let us pray.
> 
> O Eternal God, Father of our Lord Jesus Christ, Creator and Preserver of all mankind, Giver of all spiritual grace, and the Author of everlasting life: send Your blessing upon these Your servants, this man and this woman, whom we bless in Your name; that as Isaac and Rebecca lived faithfully together in the bonds of matrimony, so may this man and wife surely perform and keep the vow and covenant made between them, of which these rings are a token and pledge. And may they ever remain in perfect love and peace together, and live according to Your laws, through Jesus Christ our Lord. Amen.

<p>Pronouncement</p>
<p style="text-align: center">*Then the minister shall speak to the people,*</p>
<blockquote>
<p>Forasmuch as [Name of Groom] and [Name of Bride] have consented together to holy wedlock, and have witnessed their vow here before God and this company; and have given and pledged their faithfulness to each other by the joining of hands and exchanging of rings: By the authority committed unto me as a Minister of the Church of Jesus Christ, I pronounce that this man and this woman be man and wife, according to the ordinance of God. In the name of the Father, and of the Son, and of the Holy Spirit. Amen.</p>
</blockquote>
<p style="text-align: center">*Then the minister shall join their right hands together, and say,*</p>

> Those whom God has joined together, let no man separate.[^directoryForWorship.27]
> 
> [Name of Groom], you may kiss your bride.

[^directoryForWorship.27]: Matthew 19:6.

<p>Presentation of the Couple</p>
<p style="text-align: center">*The couple turns and faces the congregation. The minister shall say,*</p>
<blockquote>
<p>I now have the honor of presenting to you: Mr. and Mrs. _______________________.</p>
</blockquote>
<p>Recessional</p>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-76-suggested-form-for-a-funeral" title="76. Suggested Form for a Funeral">

## 76. Suggested Form for a Funeral {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="76"></a>*Because the funeral is a service of worship of the Lord Jesus Christ, eulogy of the deceased shall be given prior to the call to worship at the beginning of worship. Similarly, if the family and friends wish to share remembrances, these shall precede the worship service.*</p>
<p class="no-indent">*The following form is from The Book of Church Order of the Presbyterian Church in the United States (1933), modernized.*</p>
<p>Scripture Readings</p>
<blockquote>
<p>“Jesus said to her, ‘I am the resurrection and the life; he who believes in Me will live even if he dies, and everyone who lives and believes in Me will never die. Do you believe this?’”[^directoryForWorship.28]</p>

[^directoryForWorship.28]: John 11:25-26.

<p>“‘Man, who is born of woman, is short-lived and full of turmoil. Like a flower he comes forth and withers. He also flees like a shadow and does not remain.’”[^directoryForWorship.29]</p>

[^directoryForWorship.29]: Job 14:1-2.

<p>“For we are sojourners before You, and tenants, as all our fathers were; our days on the earth are like a shadow, and there is no hope.”[^directoryForWorship.30]</p>

[^directoryForWorship.30]: 1 Chronicles 29:15.

<p>“For we have brought nothing into the world, so we cannot take anything out of it either.”[^directoryForWorship.31]</p>

[^directoryForWorship.31]: 1 Timothy 6:7.

<p>“‘The LORD gave and the LORD has taken away. Blessed be the name of the LORD.’”[^directoryForWorship.32]</p>

[^directoryForWorship.32]: Job 1:21b.

</blockquote>
<p>Prayer of Invocation</p>

> Let us pray.
> 
> O God, who is our God, and our fathers&#8217; God; You whose compassions fail not, but who is the same yesterday, today, and forever, grant us now Your presence, we beseech You, that our souls may be strengthened, and that we faint not under Your afflicting providence, but that through Your condescension may find all grace to help in this our time of need, which we ask in the name of Jesus Christ, our Lord and Saviour, to whom, with You and the Holy Spirit, we will ascribe all honor, majesty and might, world without end. Amen.

<p>Song</p>
<p>Scripture Readings (for example, Psalm 39:4-13; Psalm 90:1-12; 1 Corinthians 15:20-58. Instead of the foregoing passage from 1 Corinthians 15, one or more of the following may be substituted as the occasion may require: Ecclesiastes 12; Psalm 27; Revelation 22:1-5.)</p>
<p>Preaching of God’s Word</p>
<p>Prayer</p>
<blockquote>
<p>Let us pray.</p>
<p>Almighty and most merciful God, our heavenly Father, the consolation of the sorrowful and the support of the stricken, who does not willingly afflict the children of men, look in pity, we ask You, on all upon whom You have laid Your afflicting hand, and, in the multitude of Your tender mercies, be pleased to uphold and comfort them in the day of their trial and distress. Grant us all grace that we may lay to heart the lesson of this solemn providence, and work while the day lasts, knowing that the night comes, when no man can work; and that we may set our affections on things that are in heaven, and not on things that are on the earth. Enable us to live by faith on the Son of God, that when Christ, who is our life, shall appear, we also may appear with Him in glory.</p>
<p>O Lord Jesus Christ, Son of God, Lamb of God, which takes away the sin of the world, to whom shall we go but to You? You have the words of eternal life. You who were a Man of Sorrows and acquainted with grief, have pity upon those who cry to You. When our eyes grow dim in the shadows of death, and we pass through the deep waters, by Your agony and bloody sweat, and by Your death on Calvary, we ask You to remember us. O You who saved us, do not forsake us in the trying hour; You who vanquished death, give us the victory, and bring us to Your own everlasting rest in the assembly of Your saints on high.</p>
<p>O God, the Holy Spirit, Author of light and life and truth, inspire our souls with hope through the Gospel of our Lord Jesus Christ, imparting the benefits of His atonement, and the power of His all-sufficient grace. Release us from our sins; fill us with the fruits of Your own indwelling, and form us anew in the image of God. Help us now, O blessed Comforter; heal our wounded spirits and do not despise our broken and contrite hearts.</p>
<p>O God the Father, God the Son, and God the Holy Spirit, Triune Jehovah, have mercy upon us, Your servants, as we wait before You: and hear our prayer. Be pleased graciously to attend to our humble requests, and to do for us all that we need, glorifying Yourself by us both in this present world, and in that which is to come: all of which we ask through Jesus Christ our Lord. Amen.</p>
</blockquote>
<p>Lord’s Prayer</p>
<blockquote>
<p>Our Father who art in heaven, Hallowed be Thy name. Thy kingdom come. Thy will be done on earth as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil. For Thine is the kingdom and the power and the glory forever. Amen.</p>
</blockquote>
<p>Benediction</p>
<blockquote>
<p>“The grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit, be with you all.”[^directoryForWorship.33] Amen.</p>

[^directoryForWorship.33]: 2 Corinthians 13:14.

</blockquote>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-77-suggested-form-for-a-childs-funeral" title="77. Suggested Form for a Child’s Funeral">

## 77. Suggested Form for a Child’s Funeral {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="77"></a>*Because the funeral is a service of worship of the Lord Jesus Christ, eulogy of the deceased shall be given prior to the call to worship at the beginning of worship. Similarly, if the family and friends wish to share remembrances, these shall precede the worship service.*</p>
<p class="no-indent">*The following form is from The Book of Church Order of the Presbyterian Church in the United States (1933), modernized.*</p>
<p>Scripture Readings</p>
<blockquote>
<p>May the LORD answer you in the day of trouble!<br />
May the name of the God of Jacob set you securely on high!<br />
May He send you help from the sanctuary<br />
And support you from Zion![^directoryForWorship.34]</p>

[^directoryForWorship.34]: Psalm 20:1-2.

<p>“‘Man, who is born of woman, is short-lived and full of turmoil. Like a flower he comes forth and withers. He also flees like a shadow and does not remain.’”[^directoryForWorship.35]</p>

[^directoryForWorship.35]: Job 14:1-2.

<p>“‘The LORD gave and the LORD has taken away. Blessed be the name of the LORD.’”[^directoryForWorship.36]</p>

[^directoryForWorship.36]: Job 1:21b.

<p>“‘Come to Me, all who are weary and heavy-laden, and I will give you rest.’”[^directoryForWorship.37]</p>

[^directoryForWorship.37]: Matthew 11:28.

</blockquote>
<p>Prayer</p>
<blockquote>
<p>Father of mercies, God of all grace, ever comforting us by the tender assurance of Your love for all those whom you chasten, be near to us now in this hour of sorrow, as we come to cast our care upon You, and seek the strength and consolation You only can impart.</p>
<p>As a father pities his children, so do You pity those who sit before You, smitten and afflicted. As one whom his mother comforts, do You comfort them, and so sanctify to them this sorrow that theirs may be everlasting consolation.</p>
<p>O You who leads Joseph like a flock, who knows Your own sheep by name as they follow You, carrying the lambs in Your arms and folding them in Your bosom, it is not Your will that one of these little ones should perish. When You do send your messenger, like a gentle shepherd, to lead them into the heavenly pastures, may bereaved parents hear the voice which says, “Let the children alone, and do not hinder them from coming to Me.”[^directoryForWorship.38] Fill them with resignation to Your will; give them the consolations of Your Spirit, and grant that, through Your grace, this chastening may be for their profit, that, being made partakers of Your holiness, they may be prepared for everlasting blessedness in that world where, after the separations and sorrows of this life, they may be forever with one another and with the Lord, through the merits and mediation of Jesus Christ, Your Son, our Savior. Amen.</p>

[^directoryForWorship.38]: Matthew 19:14.

</blockquote>
<p>Song</p>
<p>Scripture Readings (for example, Psalm 23; 2 Samuel 12:16-23; Isaiah 51:12, 66:13; John 13:7; Hebrews 12:5-7, 11-12; Romans 8:15-18; John 14:1-2; Isaiah 40:1, 11; Mark 10:13-16; Matthew 18:10-14; Rev. 7:15-17)</p>
<p>Preaching of God’s Word</p>
<p>Prayer</p>
<blockquote>
<p>O God, our heavenly Father, who through the blood of Your Son has provided redemption for all Your own, we would render to You most hearty thanks, in this our time of grief, for the hope we have that the soul of this dear child whose loss we mourn is at rest in You. Not a sparrow falls to the ground without our Father, and those who are of more value than many sparrows cannot die until You, who regards with tender compassion the weakest of Your creatures, call them to Yourself. We would not sorrow as those who have no hope, but bow in humble submission to Your sovereign decree, and by divine grace would say, Your will be done.</p>
<p>Grant to Your servants, we implore You, the consolations of Your Spirit, giving us beauty for ashes, the oil of joy for mourning, and the garment of praise for the spirit of heaviness. May this chastisement which now seems so grievous yield us the peaceable fruits of righteousness, by drawing us into closer fellowship with You, that we may not set our affections on the things of this world; but upon that blessed home above, where all who have departed in Christ await us beyond the reach of sorrow.</p>
<p>Shine upon our darkness, O Lord; pardon all our sins; build us up and strengthen us in our most holy faith; and at last give us the victory over death, bringing us in holiness and joy to Your own eternal rest.</p>
<p>Hear now our prayer, O God, and be pleased mercifully to bestow the blessings which we need, for the love of Jesus Christ, Your well-beloved Son, to whom, with You and the Holy Spirit, be all dominion, glory and praise, world without end. Amen.</p>
</blockquote>
<p>Lord’s Prayer</p>
<blockquote>
<p>Our Father who art in heaven, Hallowed be Thy name. Thy kingdom come. Thy will be done on earth as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil. For Thine is the kingdom and the power and the glory forever. Amen.</p>
</blockquote>
<p>Benediction</p>
<blockquote>
<p>“The grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit, be with you all.”[^directoryForWorship.39] Amen.</p>

[^directoryForWorship.39]: 2 Corinthians 13:14.

</blockquote>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-78-suggested-form-for-a-graveside-committal-service" title="78. Suggested Form for a Graveside Committal Service">

## 78. Suggested Form for a Graveside Committal Service {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="78"></a>*The following form is from the 1549 Book of Common Prayer, modernized.*</p>
<p style="text-align: center">*At the grave, while the corpse is made ready to be laid into the earth, the minister shall say,*</p>
<blockquote>
<p>Man that is born of a woman has but a short time to live and is full of misery. He comes up and is cut down, like a flower; he flees like a shadow and never continues in one place.</p>
<p>In the midst of life, we are in death: and of whom may we seek for relief, but of You, O Lord, who for our sins are justly displeased?</p>
<p>Yet, O Lord God most holy, O Lord most mighty, O holy and most merciful Savior, deliver us not into the bitter pains of eternal death. You know, O Lord, the secrets of our hearts: shut not your merciful ears to our prayers; but spare us, Lord most holy, O God most mighty, O holy and merciful Savior, O most worthy Judge eternal, suffer us not at our last hour for any pains of death to fall from You.</p>
</blockquote>
<p style="text-align: center">*Then shall follow this lesson, taken from the fifteenth chapter of the First Epistle to the Corinthians:*</p>
<blockquote>
<p>But now Christ has been raised from the dead, the first fruits of those who are asleep. For since by a man *came* death, by a man also came the resurrection of the dead. For as in Adam all die, so also in Christ all will be made alive. But each in his own order: Christ the first fruits, after that those who are Christ’s at His coming, then *comes* the end, when He hands over the kingdom to the God and Father, when He has abolished all rule and all authority and power. For He must reign until He has put all His enemies under His feet. The last enemy that will be abolished is death. For HE HAS PUT ALL THINGS IN SUBJECTION UNDER HIS FEET. But when He says, “All things are put in subjection,” it is evident that He is excepted who put all things in subjection to Him. When all things are subjected to Him, then the Son Himself also will be subjected to the One who subjected all things to Him, so that God may be all in all.</p>
<p>Otherwise, what will those do who are baptized for the dead? If the dead are not raised at all, why then are they baptized for them? Why are we also in danger every hour? I affirm, brethren, by the boasting in you which I have in Christ Jesus our Lord, I die daily. If from human motives I fought with wild beasts at Ephesus, what does it profit me? If the dead are not raised, LET US EAT AND DRINK, FOR TOMORROW WE DIE. Do not be deceived: “Bad company corrupts good morals.” Become sober-minded as you ought, and stop sinning; for some have no knowledge of God. I speak *this* to your shame.</p>
<p>But someone will say, “How are the dead raised? And with what kind of body do they come?” You fool! That which you sow does not come to life unless it dies; and that which you sow, you do not sow the body which is to be, but a bare grain, perhaps of wheat or of something else. But God gives it a body just as He wished, and to each of the seeds a body of its own. All flesh is not the same flesh, but there is one *flesh* of men, and another flesh of beasts, and another flesh of birds, and another of fish. There are also heavenly bodies and earthly bodies, but the glory of the heavenly is one, and the *glory* of the earthly is another. There is one glory of the sun, and another glory of the moon, and another glory of the stars; for star differs from star in glory.</p>
<p>So also is the resurrection of the dead. It is sown a perishable *body*, it is raised an imperishable *body*; it is sown in dishonor, it is raised in glory; it is sown in weakness, it is raised in power; it is sown a natural body, it is raised a spiritual body. If there is a natural body, there is also a spiritual *body*. So also it is written, “The first MAN, Adam, BECAME A LIVING SOUL.” The last Adam *became* a life-giving spirit. However, the spiritual is not first, but the natural; then the spiritual. The first man is from the earth, earthy; the second man is from heaven. As is the earthy, so also are those who are earthy; and as is the heavenly, so also are those who are heavenly. Just as we have borne the image of the earthy, we will also bear the image of the heavenly.</p>
<p>Now I say this, brethren, that flesh and blood cannot inherit the kingdom of God; nor does the perishable inherit the imperishable. Behold, I tell you a mystery; we will not all sleep, but we will all be changed, in a moment, in the twinkling of an eye, at the last trumpet; for the trumpet will sound, and the dead will be raised imperishable, and we will be changed. For this perishable must put on the imperishable, and this mortal must put on immortality. But when this perishable will have put on the imperishable, and this mortal will have put on immortality, then will come about the saying that is written, “DEATH IS SWALLOWED UP in victory. “O DEATH, WHERE IS YOUR VICTORY? O DEATH, WHERE IS YOUR STING?” The sting of death is sin, and the power of sin is the law; but thanks be to God, who gives us the victory through our Lord Jesus Christ.</p>
</blockquote>
<p style="text-align: center">*Then shall follow this lesson, taken from the fourteenth chapter of the Gospel of John:*</p>
<blockquote>
<p>“Do not let your heart be troubled; believe in God, believe also in Me. In My Father’s house are many dwelling places; if it were not so, I would have told you; for I go to prepare a place for you. If I go and prepare a place for you, I will come again and receive you to Myself, that where I am, *there* you may be also. And you know the way where I am going.” Thomas said to Him, “Lord, we do not know where You are going, how do we know the way?” Jesus said to him, “I am the way, and the truth, and the life; no one comes to the Father but through Me.”</p>
</blockquote>
<p style="text-align: center">*Then the minister shall say,*</p>
<blockquote>
<p>Forasmuch as it hath pleased Almighty God in His infinite wisdom and mercy to take out of this world the soul of our [brother/sister] departed, we now commit [his/her] body to the ground, earth to earth, ashes to ashes, and dust to dust.</p>
</blockquote>
<p style="text-align: center">*Then shall follow this lesson, taken from the fourth chapter of the Apostle Paul’s First Epistle to the Thessalonians,*</p>
<blockquote>
<p>But we do not want you to be uninformed, brethren, about those who are asleep, so that you will not grieve as do the rest who have no hope. For if we believe that Jesus died and rose again, even so God will bring with Him those who have fallen asleep in Jesus. For this we say to you by the word of the Lord, that we who are alive and remain until the coming of the Lord, will not precede those who have fallen asleep. For the Lord Himself will descend from heaven with a shout, with the voice of *the* archangel and with the trumpet of God, and the dead in Christ will rise first. Then we who are alive and remain will be caught up together with them in the clouds to meet the Lord in the air, and so we shall always be with the Lord. Therefore comfort one another with these words.</p>
</blockquote>
<p style="text-align: center">*Then shall be said,*</p>
<blockquote>
<p>I heard a voice from heaven, saying, “Write, ‘Blessed are the dead who die in the Lord from now on!’” “Yes,” says the Spirit, “so that they may rest from their labors,&#8230;”</p>
</blockquote>
<p style="text-align: center">*Then the minister shall say,*</p>
<blockquote>
<p>Let us pray.</p>
<p>Almighty God, our heavenly Father, who, in thy perfect wisdom and mercy has ended for your servants departed, the voyage of this troubled life, grant we ask you, that we who are still to continue our course amidst earthly dangers, temptations, and troubles may evermore be protected by Your mercy, and finally come to the haven of eternal salvation, through Jesus Christ our Lord. Amen.</p>
</blockquote>
<p style="text-align: center">*Then the minister shall pronounce a benediction,*</p>
<blockquote>
<p>The LORD bless you, and keep you;<br />
The LORD make His face shine on you,<br />
And be gracious to you;<br />
The LORD lift up His countenance on you,<br />
And give you peace.</p>
<p>Amen.</p>
</blockquote>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-79-suggested-form-for-infant-dedication" title="79. Suggested Form for Infant Dedication">

## 79. Suggested Form for Infant Dedication {-}

<p data-type="subtitle" class="chapter-number"></p>
<p class="no-indent"><a id="79"></a>*While infant dedication is not a sacrament, those who hold credo-baptist views may yet wish to present their child before the congregation, thanking God for his safe delivery, asking God’s blessing upon him, and testifying to God’s promises concerning our children. The following is a sample form which may be used where parents would like to publicly dedicate their children to the Lord.*</p>
<p><strong>Explanation of Infant Dedication</strong></p>
<blockquote>
<p>It has always been a custom among God’s people to mark the blessing of the Lord in the birth of a child. Today, this family [these families] has come to give thanks to God for bringing this child safely into the world, to continue the duty and privilege given our father Adam in naming this child, and to testify to God’s promises concerning our children. We have therefore set aside this time to seek God’s blessing on this child, and for these parents to proclaim their commitment to raise him within the household of God, the Church, and to tenderly care for, disciple, and teach him the truths of Scripture. Alongside them, our church family pledges to be responsible for this child, to share in their duty to care for him, and to assist them in their teaching and discipleship.</p>
<p>This dedication is an act in which the parents confess that this child is a joyful trust and stewardship from God. They also rejoice with the psalmist, who says,</p>
<p>“Behold, children are a gift of the LORD,<br />
The fruit of the womb is a reward.<br />
Like arrows in the hand of a warrior,<br />
So are the children of one’s youth.<br />
How blessed is the man whose quiver is full of them;<br />
They will not be ashamed<br />
When they speak with their enemies in the gate.”[^directoryForWorship.40]</p>

[^directoryForWorship.40]: Psalm 127:3-5.

<p>These parents also come to claim God’s many promises that He will be a God to us and to our children, as the Scriptures testify:</p>
<p>“For the promise is for you and your children and for all who are far off, as many as the Lord our God will call to Himself.”[^directoryForWorship.41]</p>

[^directoryForWorship.41]: Acts 2:39.

</blockquote>
<p><strong>Naming of the Child and Vows of the Parents</strong></p>
<blockquote>
<p><strong>Pastor</strong>: Father, name your child.<br />
<strong>Father</strong>: [Gives full name].<br />
<strong>Pastor</strong>: As you come to dedicate your [son/daughter] [Name] to the Lord, I now ask you to reaffirm your faith by answering the following questions.<br />
Pastor: Do you confess your faith in God the Father, in Jesus Christ the only begotten Son of God, and in the Holy Spirit, the Lord and Giver of Life?<br />
<strong>Parent(s)</strong>: We do.<br />
<strong>Pastor</strong>: Do you acknowledge that this child is conceived and born in sin, that no one can enter the kingdom of God unless he be born of the Spirit, and that it is only by faith in Christ that this child may be given the blessing of eternal life?<br />
<strong>Parent(s)</strong>: We do.<br />
<strong>Pastor</strong>: Do you promise to teach your child the commandments of God, to live a godly and sober life before [him/her], to renounce the devil and all his works, and to show by your care and discipline the love, mercy, discipline, and righteousness of our Lord?<br />
<strong>Parent(s)</strong>: We do.<br />
<strong>Pastor</strong>: Do you acknowledge and claim for yourselves the promise of God that He will be a God to you and your children, such that it is your hope that your child may in God’s good time profess faith in our Lord Jesus Christ?<br />
<strong>Parent(s)</strong>: We do.</p>
</blockquote>
<p><strong>Charge to the Parents</strong></p>
<blockquote>
<p>Beloved, I charge you to teach your child the Word of God, to instruct [him/her] in the principles of our holy religion as contained in the Scriptures of the Old and New Testaments, to pray with [him/her] and for [him/her], to set an example of piety and godliness before [him/her], and to endeavor by every method which God has given us to bring up your child in the nurture and admonition of the Lord.</p>
</blockquote>
<p><strong>Vows of the Congregation</strong></p>
<blockquote>
<p><strong>Pastor</strong>: Will the members of [Name of Church] please rise?<br />
<strong>Pastor</strong>: Do you, the congregation of [Name of Church], promise to tell this child of the Gospel of our Lord, to help [him/her] learn all of Christ’s commandments, and to assist [him/her] in living a godly and Christian life in the household of God?<br />
<strong>Congregation</strong>: We do.<br />
<strong>Pastor</strong>: Do you promise to help these parents raise this child in the nurture and admonition of the Lord, so that in due time [he/she] may confess faith in our Lord and Savior, Jesus Christ?<br />
<strong>Congregation</strong>: We do.<br />
[Please be seated.]</p>
</blockquote>
<p><strong>Prayer of Blessing</strong></p>
<blockquote>
<p>Let us pray.</p>
<p>Almighty and everlasting God, who of Your infinite mercy and goodness has promised that You will not be only our God, but also the God and Father of our children: we thank you for the safe delivery of this child through the pains and difficulties of labor. And we come to you now, humbly asking that you take this child under your fatherly care and protection, and guide [him/her] into faith. Allow [him/her] to grow in wisdom and in stature, and in favor with God and man. Abundantly enrich (him/her) with your heavenly grace: bring [him/her] safely through the perils of childhood, deliver [him/her] from the temptations of youth, lead [him/her] to a sincere confession of faith in Jesus Christ, and cause [him/her] to persevere in that confession to [his/her] life’s end.</p>
<p>Father, please guide these parents with your counsel as they train and teach their child; and help them to lead their household into an ever-increasing knowledge of Christ. We commend to Your care the children and families of this congregation. Help us in our homes to honor You, and to lovingly serve one another. To Your name be all blessing and glory through Jesus Christ our Lord. Amen.</p>
</blockquote>
</section>
<section data-type="chapter" class="chapter" id="chapter-slug-80-the-creeds" title="80. The Creeds">

## 80. The Creeds {-}

<p data-type="subtitle" class="chapter-number"></p>
<ol class="ch80">
<li class="no-indent"><a id="80"></a><strong>The Apostles’ Creed</strong><br />
<blockquote class="hanging-indent">
<p>I believe in God, the Father Almighty,<br />
Maker of heaven and earth,<br />
and in Jesus Christ, His only Son, our Lord:</p>
<p>Who was conceived by the Holy Ghost,[^directoryForWorship.42]<br />
born of the virgin Mary,<br />
suffered under Pontius Pilate,<br />
was crucified, dead, and buried;</p>
<p>He descended into hell;</p>
<p>The third day He arose again from the dead;</p>
<p>He ascended into heaven,<br />
and sitteth[^directoryForWorship.43] on the right hand of God the Father Almighty;<br />
from thence[^directoryForWorship.44] He shall come to judge the quick[^directoryForWorship.45] and the dead.</p>

[^directoryForWorship.42]: Or, “Holy Spirit.”

[^directoryForWorship.43]: Or, “sits.”

[^directoryForWorship.44]: Or, “there.”

[^directoryForWorship.45]: Or, “living.”

<p>I believe in the Holy Ghost,[^directoryForWorship.46]<br />
the holy catholic[^directoryForWorship.47] church,<br />
the communion of saints,<br />
the forgiveness of sins,<br />
the resurrection of the body,<br />
and the life everlasting.</p>

[^directoryForWorship.46]: Or, “Holy Spirit.”

[^directoryForWorship.47]: Or, “universal.”

<p>Amen.</p>
</blockquote>
</li>
<li class="no-indent"><strong>The Nicene Creed</strong><br />
<blockquote class="hanging-indent">
<p>We believe in one God, the Father Almighty,<br />
Maker of heaven and earth,<br />
and of all things visible and invisible.</p>
<p>And in one Lord Jesus Christ, the only-begotten Son of God,<br />
begotten of the Father before all worlds;<br />
God of God, Light of Light,<br />
very God of very God;<br />
begotten, not made,<br />
being of one substance with the Father,<br />
by whom all things were made.<br />
Who, for us men and for our salvation,<br />
came down from heaven,<br />
and was incarnate by the Holy Spirit of the virgin Mary,<br />
and was made man;<br />
and was crucified also for us under Pontius Pilate;<br />
He suffered and was buried;<br />
and the third day He rose again, according to the Scriptures;<br />
and ascended into heaven, and sits on the right hand of the Father;<br />
and He shall come again, with glory, to judge the quick[^directoryForWorship.48] and the dead;<br />
whose kingdom shall have no end.</p>

[^directoryForWorship.48]: Or, “living.”

<p>And we believe in the Holy Spirit,<br />
the Lord and Giver of Life;<br />
who proceeds from the Father and the Son;<br />
who with the Father and the Son together is worshiped and glorified;<br />
who spoke by the prophets.</p>
<p>And we believe (in) one holy catholic[^directoryForWorship.49] and apostolic Church.<br />
We acknowledge one baptism for the remission of sins;<br />
and we look for the resurrection of the dead,<br />
and the life of the world to come.</p>

[^directoryForWorship.49]: Or, “universal.”

<p>Amen.</p>
</blockquote>
</li>
<li class="no-indent"><strong>The Athanasian Creed</strong><br />
<blockquote>
<p>[1] Whoever desires to be saved should above all hold to the catholic[^directoryForWorship.50] faith. [2] Anyone who does not keep it whole and unbroken will doubtless perish eternally.</p>

[^directoryForWorship.50]: Or, “universal.”

<p>[3] Now this is the catholic faith: that we worship one God in Trinity and the Trinity in unity, [4] neither confounding their persons nor dividing the essence. [5] For the person of the Father is a distinct person, the person of the Son is another, and that of the Holy Spirit still another. [6] But the divinity of the Father, Son, and Holy Spirit is one, the glory equal, the majesty coeternal. [7] Such as the Father is, such is the Son and such is the Holy Spirit. [8] The Father is uncreated, the Son is uncreated, the Holy Spirit is uncreated. [9] The Father is immeasurable, the Son is immeasurable, the Holy Spirit is immeasurable. [10] The Father is eternal, the Son is eternal, the Holy Spirit is eternal. [11] And yet there are not three eternal beings; there is but one eternal being. [12] So too there are not three uncreated or immeasurable beings; there is but one uncreated and immeasurable being. [13] Similarly the Father is almighty, the Son is almighty, the Holy Spirit is almighty. [14] Yet there are not three almighty beings; there is but one almighty being. [15] Thus, the Father is God, the Son is God, the Holy Spirit is God. [16] Yet there are not three gods; there is but one God. [17] Thus, the Father is Lord, the Son is Lord, the Holy Spirit is Lord. [18] Yet there are not three lords; there is but one Lord. [19] Just as Christian truth compels us to confess each person individually as both God and Lord, [20] so catholic religion forbids us to say that there are three gods or lords. [21] The Father was neither made nor created nor begotten from anyone. [22] The Son was neither made nor created; He was begotten from the Father alone. [23] The Holy Spirit was neither made nor created nor begotten; He proceeds from the Father and the Son. [24] Accordingly, there is one Father, not three fathers; there is one Son, not three sons; there is one Holy Spirit, not three holy spirits. [25] None in this Trinity is before or after, none is greater or smaller; [26] in their entirety the three persons are coeternal and coequal with each other. [27] So in everything, as was said earlier, the unity in Trinity, and the Trinity in unity, is to be worshiped. [28] Anyone then who desires to be saved should think thus about the Trinity.</p>
<p>[29] But it is necessary for eternal salvation that one also believe in the incarnation of our Lord Jesus Christ faithfully. [30] Now this is the true faith: that we believe and confess that our Lord Jesus Christ, God’s Son, is both God and man, equally. [31] He is God from the essence of the Father, begotten before time; and He is man from the essence of His mother, born in time; [32] completely God, completely man, with a rational soul and human flesh; [33] equal to the Father as regards divinity, less than the Father as regards humanity. [34] Although He is God and man, yet Christ is not two, but one. [35] He is one, however, not by His divinity being turned into flesh, but by God’s taking humanity to Himself. [36] He is one, certainly not by the blending of His essence, but by the unity of His person. [37] For just as one man is both rational soul and flesh, so too the one Christ is both God and man. [38] He suffered for our salvation; He descended to hell; He arose from the dead on the third day; [39] He ascended to heaven; He is seated at the Father’s right hand; [40] from there He will come to judge the living and the dead. [41] At His coming all people will arise bodily [42] and give an accounting of their own deeds. [43] Those who have done good will enter eternal life, and those who have done evil will enter eternal fire.</p>
<p>[44] This is the catholic faith: that one cannot be saved without believing it firmly and faithfully.</p>
</blockquote>
</li>
<li class="no-indent"><strong>The Chalcedonian Creed</strong><br />
<blockquote>
<p>We, then, following the holy Fathers, all with one consent, teach men to confess one and the same Son, our Lord Jesus Christ, the same perfect in Godhead and also perfect in manhood; truly God and truly man, of a reasonable[^directoryForWorship.51] soul and body; consubstantial with the Father according to the Godhead, and consubstantial with us according to the Manhood; in all things like unto us, without sin; begotten before all ages of the Father according to the Godhead, and in these latter days, for us and for our salvation, born of the Virgin Mary, the God-bearer,[^directoryForWorship.52] according to the Manhood; one and the same Christ, Son, Lord, Only-begotten, to be acknowledged in two natures, inconfusedly, unchangeably, indivisibly, inseparably; the distinction of natures being by no means taken away by the union, but rather the property of each nature being preserved, and concurring in one Person and one Subsistence, not parted or divided into two persons, but one and the same Son, and only begotten, God the Word, the Lord Jesus Christ, as the prophets from the beginning have declared concerning Him, and the Lord Jesus Christ Himself has taught us, and the Creed of the holy Fathers has handed down to us.</p>

[^directoryForWorship.51]: Or, “rational.”

[^directoryForWorship.52]: τῆς θεοτόκου, sometimes rendered “Mother of God.”

</blockquote>
</li>
</ol>
