# Updates {.unnumbered}

*Significant changes to this Book of Church Order will be listed here, the most recent appearing at the top. For a detailed diff hosted at Github, [click here](https://github.com/Evangel-Presbytery/evangel-bco).*

* **Current version: On June 5, 2025, Evangel Presbytery ratified the following:** 
  * **Amend the BCO to (1)\ create a new category of constitutional documents called [Doctrinal Declarations of the Presbytery (DDP)](https://ddp.evangelpresbytery.com) and (2)\ define the constitutional weight of these declarations. (BCO Preface §C, 15.5, 21.2, 21.3, 22.1, 23.4, 23.6, 26.4, 30.1, 30.4, 33.1, DFW Preface, 52.6)**
  * **Remove BCO\ 28, “Declaration of Doctrine and Policies Concerning Sexuality,” adopting its doctrinal portions, as revised, into the DDP.**
  * **Remove BCO\ 29, “Abortion and the Church: What We Teach,” adopting its content, as written with no revisions, into the DDP.**
  * **Amend the BCO to adopt policy statements, as revised, from BCO\ 28 into the Directory for Worship. (BCO 71–72)**
  * **Renumber the chapters of the BCO according to the following changes:**
    * **Removal of BCO 28**
    * **Removal of BCO 29**
  * **Addition of “Other Policies Relating to Biblical Sexuality” (new number: BCO 72) after “The Solemnization of Marriage” (Old BCO\ 73, new number: BCO\ 71)**
  * **Update the BCO’s internal cross references affected by the new chapter numbering.**
* Amendment to BCO 26.1 regarding the notice required before congregational meetings. Ratified at the February 6, 2025 meeting of Presbytery.
* Amendment to BCO 15.10 regarding special called meetings. Ratified at the June 6, 2024 meeting of Presbytery.
* Amendments to BCO 6.3, 12.3 and 22.11 regarding the use of "Teaching Elder"; amendment to BCO 12.3 regarding who is required to preach at presbytery; amendment inserting a new section 29 on abortion to the BCO (subsequent sections, and all internal links, were re-numbered as a result). These amendments were ratified at the presbytery meeting held on October 6, 2023.
* Amendments to BCO 61.4 (regarding fencing the Lord's table) and BCO 61.1 (regarding paedocommunion) ratified at the June 2023 meeting of Presbytery.
* Amendments to BCO 14, 24 and 64, ratified at the October 2022 meeting of Presbytery.
* Migrated from Pressbooks to Bookdown hosted on Github pages.
* [Hot Fix December 10, 2021](https://www.dropbox.com/sh/e5lszl09qec2wy0/AADMEzOS1C1Z7Ao4r4xyddHNa?dl=0)
  * The second paragraph of BCO 25.1 was amended on June 6, 2019. However, the entire paragraph was accidentally omitted from the published version of the BCO. This hotfix fixes that mistake.
* [Amended October 8, 2021](https://www.dropbox.com/sh/67fg23e5sksui6j/AAB6LRjZ2dld47gYz1G0jo-Fa?dl=0)
* [Amended June 3, 2021](https://www.dropbox.com/sh/z9buy77lg1ay8t0/AAAnPPQysyhwRPJ7lpLxl3Bma?dl=0)
* [Amended on October 31, 2019](https://www.dropbox.com/sh/yhg7o7s6vlx0jha/AABM5so3BTahNcU7rUWsZHAGa?dl=0)
* [Amended on June 6, 2019](https://www.dropbox.com/sh/6e1mcd2n8vojvpv/AADWRZsciqNw1xteiuRA0lr3a?dl=0)
* [Original Version released February 28, 2019](https://www.dropbox.com/sh/w46pitp7sevpepk/AAAH_HDpb8Qpck42Dkfw661Za?dl=0)
