--- 
title: "Evangel Presbytery Book of Church Order"
author: "Evangel Presbytery"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
github-repo: Evangel-Presbytery/evangel-bco
description: "This is Evangel Presbytery's Book of Church Order."
---

# Preface {-}

<div id="front-matter-preface"></div>

## A. Historical Statement and Declaration of Intent {-}

<p class="no-indent">The Lord has blessed His Church with many precious gifts for equipping the saints for the work of ministry and for building up the body of Christ. Among these gifts are basic biblical principles for the system of government and discipline of His Church. Applying this wisdom to our time and place, we learn how to conduct ourselves in the Household of Faith as we labor with other congregations and undershepherds in mutual accountability and love.

We believe the Book of Church Order, whose roots stretch back to Calvin’s Geneva, is an excellent outworking of these principles. John Calvin wrote the first modern Presbyterian Book of Order for the church at Geneva in 1542.

John Knox learned under John Calvin’s teaching and pastoral ministry for several years, and then returned to Scotland. He wrote The First Book of Discipline for the Presbyterian Church of Scotland, in 1560. The whole history of Presbyterian church government in Scotland goes back to this First Book of Discipline.

The Westminster Assembly, which met in London in 1643, wrote not only the Confession of Faith and Catechisms, but also The Form of Presbyterian Church Government. The Presbyterian Churches of England, Scotland, and Ireland adopted this Westminster Form of Government.

When our Presbyterian forefathers came to America they brought with them the Westminster “Form of Presbyterian Church Government,” and it became the basis of Church law in the American Presbyterian Church.

The first General Assembly of the Presbyterian Church in America was organized in 1789. The General Synod in preparing for the organization of the General Assembly practically rewrote The Form of Presbyterian Church Government in 1788, in order to adjust it to the conditions in America. This new book was called The Form of Government and Discipline of the Presbyterian Church in the United States of America. It was revised a number of times prior to 1861 and the beginning of the Civil War, when the Northern and Southern Presbyterian Churches were tragically divided. At that time, the Southern Presbyterians withdrew and formed The Presbyterian Church in the United States.

When the General Assembly of the Presbyterian Church in the United States (PCUS) was organized on December 4, 1861, it adopted the Form of Government and Discipline which had been in use since 1788. In 1863 the General Assembly took steps to revise this Form of Government and Discipline with the result that a thoroughgoing revision was adopted in 1879. A great many amendments were added during the next forty years.

In 1921 the PCUS General Assembly took steps to revise the Book of Church Order again. Another thoroughgoing revision was proposed by the Committee on Revision, adopted by the General Assembly, approved by a large majority of the Presbyteries, and enacted into law by the General Assembly of 1925.

The Form of Government and Rules of Discipline of this 2019 Book of Church Order are based in part on a 1933 revision to the PCUS Book of Church Order and portions of the current Presbyterian Church in America Book of Church Order.[^preface.01] The Directory for Worship is based on the one in use by the Orthodox Presbyterian Church.

[^preface.01]: All quotations from The Book of Church Order of the Presbyterian Church in America used by permission from the Office of the Stated Clerk of the General Assembly of the Presbyterian Church in America.

While this current version seeks to likewise build on the solid foundation of centuries of Reformed polity, an important difference should be noted. The fellowship of churches governed by this Book of Church Order is committed to the good and pleasant unity[^preface.02] of brothers whose convictions about the time and mode of baptism differ. We grieve over the almost-perpetual division of reformed believers which has been watched by the world and the larger evangelical community during the last century, as it has been demonstrated over a whole host of secondary doctrinal matters. It’s our desire to demonstrate unity amidst diversity at points where the system of doctrine taught by reformed standards such as the Belgic Confession, the London Baptist Confession, and the Westminster Standards, etc. is not at stake. We believe the time and mode of baptism to be such a place.

[^preface.02]: Psalm 133.

Our work to keep the unity of the Spirit through the bond of peace means placing ourselves in yoke with like-minded churches who have committed themselves to both aspects of the Reformation Motto: The Church Reformed and Always Reforming. Perhaps no work of reform is more desperately needed in the church today than discipline and accountability. An expositor of a prior version of the Book of Church Order observed—in 1898—the dangerous tendency in the church of that time to avoid discipline and the inevitable harmful fruit of such unfaithfulness:

> Discipline, thorough and scriptural, is possible under our system. It is not necessary to argue that discipline is a duty enjoined in the Scriptures; but there is among us, one is tempted to say, a pervading infidelity of the worth of such teachings. Outside of the discipline of ministers charged with heresies, and of very notorious offenders in morality, there is seldom anything in the nature of judicial prosecution among us; and there is reason to believe that there is even less of that forewarning which looks forward to such prosecution. . . .
> 
> It is not easy to exercise discipline, not only on account of the imperfection of those who are to exercise it, but also on account of the strength of corruption that has come for the lack of discipline; and discipline is especially difficult where the revenues of the church come from voluntary contributions. To censure offenders generally endangers revenue. It requires a lofty indifference to financial considerations in comparison with spiritual results, or the inexperience of youth, to embolden to attempt thorough discipline. Many attempts have failed largely because the men who failed when they had less wisdom of experience and less maturity of spiritual growth have not attempted it when they became better qualified. Their former failures, and the new Book, make them afraid. But we must come to it or we perish. The churches of America must learn to exercise discipline, or the experiment of religious liberty, without financial aid from the civil power, will prove a failure. Such a result will not come, for the churches will learn this lesson of discipline. It may be through bitter experience of the fruits of laxity and of the consequent worldly corruption of the church, but to discipline the church must come. And it is here insisted that we have the usable machinery of discipline, and all we need now is the spiritual power to make it efficient.[^preface.03]

[^preface.03]: F.&nbsp;P. Ramsay, <em>An Exposition of the Form of Government and the Rules of Discipline of the Presbyterian Church in the United States</em> (Presbyterian Committee of Publication, 1898), 7-9.

Now, 120 years later, we are in no less need of the Holy Spirit’s sanctifying presence and power. And so we commit this work to God’s hands, trusting Him to supply all our needs according to His riches in glory in Christ Jesus.

## B. Preliminary Principles {-}

The members of Evangel Presbytery, in presenting to the Christian public the system of union, and the form of government and discipline which they have adopted, have thought proper to state, by way of introduction, a few of the general principles by which they have been governed in the formation of the plan. This, it is hoped, will, in some measure, prevent those rash misconstructions, and uncandid reflections, which usually proceed from an imperfect view of any subject; as well as make the several parts of the system plain, and the whole perspicuous and fully understood. They are unanimously of opinion:

1. God alone is Lord of the conscience and has left it free from any doctrines or commandments of men (a) which are in any respect contrary to the Word of God, or (b) which, in regard to matters of faith and worship, are not governed by the Word of God. Therefore, the rights of private judgment in all matters that respect religion are universal and inalienable.

2. In perfect consistency with the above principle, every Christian Church, or union or association of particular churches, is entitled to declare the terms of admission into its communion and the qualifications of its ministers and members, as well as the whole system of its internal government which Christ has appointed. In the exercise of this right it may, notwithstanding, err in making the terms of communion either too lax or too narrow; yet even in this case, it does not infringe upon the liberty or the rights of others, but only makes an improper use of its own.

3. Our blessed Savior, for the edification of the visible Church, which is His body, has appointed officers not only to preach the Gospel and administer the Sacraments, but also to exercise discipline for the preservation both of truth and duty. It is incumbent upon these officers and upon the whole Church in whose name they act, to censure or cast out the erroneous and scandalous, observing in all cases the rules contained in the Word of God.

4. Godliness is founded on truth. A test of truth is its power to promote holiness according to our Savior’s rule, “By their fruits ye shall know them.”[^preface.04] No opinion can be more pernicious or more absurd than that which brings truth and falsehood upon the same level. On the contrary, there is an inseparable connection between faith and practice, truth and duty. Otherwise it would be of no consequence either to discover truth or to embrace it.

[^preface.04]: Matthew 7:20.

5. While, under the conviction of the above principle, it is necessary to make effective provision that all who are admitted as teachers be sound in the faith, there are truths and forms with respect to which men of good character and principles may differ. In all these it is the duty both of private Christians and societies to exercise mutual forbearance towards each other.

6. Though the character, qualifications and authority of church officers are laid down in the Holy Scriptures, as well as the proper method of officer investiture, the power to elect persons to the exercise of authority in any particular society resides in that society.

7. All church power, whether exercised by the body in general, or by representation, is only ministerial and declarative since the Holy Scriptures are the only rule of faith and practice. No church judicatory may make laws to bind the conscience. All church courts may err through human frailty, yet it rests upon them to uphold the laws of Scripture though this obligation be lodged with fallible men.

8. Since ecclesiastical discipline derives its force only from the power and authority of Christ, the great Head of the Church Universal, it must be purely moral and spiritual in its nature.

If the preceding scriptural principles be steadfastly adhered to, the vigor and strictness of disciplines will contribute to the glory and well-being of the Church.

## C. Constitution Defined {-}

The Constitution of Evangel Presbytery, which is subject to and subordinate to the Scriptures of the Old and New Testaments, the infallible Word of God, consists of its doctrinal standards set forth in the <em>Westminster Confession of Faith,</em>[^preface.05] together with the <em>Larger</em>[^preface.06] and <em>Shorter Catechisms</em>[^preface.07]; the Book of Church Order, which comprises the Form of Government, the Rules of Discipline, and the Directory for the Worship of God; and the Apostles’ Creed, Nicene Creed, the Chalcedonian Creed, and Athanasian Creed; all as adopted by the Presbytery (BCO<a href="#29.1">29.1</a>).

[^preface.05]: American revisions as adopted by the Orthodox Presbyterian Church in 1936, https://evangelpresbytery.com/westminster-confession-of-faith.

[^preface.06]: https://evangelpresbytery.com/westminster-larger-catechism.

[^preface.07]: https://evangelpresbytery.com/westminster-shorter-catechism.

<!--chapter:end:index.Rmd-->

# (PART) Form of Government {-} 

# 1. The Doctrine of Church Government {-}

<div id="part-main-body-2"></div>
<div id="chapter-slug-1-the-doctrine-of-church-government"></div>

<ol class="ch1">
<li class="no-indent"><a id="1"></a>The scriptural form of Church government, which is that of Presbytery, is comprehended under five heads, namely: 1. The Church; 2. Its Members; 3. Its Officers; 4. Its Courts; and 5. Its Orders.</li>
<li class="no-indent">The Church which the Lord Jesus Christ has erected in this world for the gathering and perfecting of the saints, is His visible kingdom of grace, and is one and the same in all ages.</li>
<li class="no-indent"><a id="1.3"></a>The members of this visible Church catholic are all those persons in every nation who make profession of their faith in the Lord Jesus Christ and promise submission to His laws. Communing members are those who have made a profession of faith in Christ, have been baptized, and have been admitted by the Session to the Lord’s Table. The children of communing members are, through the covenant and by right of birth, non-communing members of the church. The children of communing members holding credo-baptistic convictions are non-communing members in the sense that they are entitled to the church’s care, love, discipline, and training, with a view to their embracing Christ and thus possessing personally all the benefits of the covenant. The children of communing members holding paedo-baptistic convictions are non-communing members in the sense that they are entitled to baptism and to the church’s care, love, discipline, and training, with a view to their embracing Christ and thus possessing personally all the benefits of the covenant.</li>
<li class="no-indent">The officers of the Church, by whom all its powers are administered, are, according to the Scriptures, Ministers of the Word, Ruling Elders, and Deacons.</li>
<li class="no-indent">Ecclesiastical jurisdiction is not a several, but a joint power, to be exercised by Presbyters in courts. These courts may have jurisdiction over one or many churches, but they sustain such mutual relations as to realize the idea of the unity of the Church.</li>
<li class="no-indent">The ordination of officers is ordinarily by a court.</li>
<li class="no-indent">This scriptural doctrine of Presbytery is necessary to the perfection of the order of the visible Church, but is not essential to its existence.</li>
</ol>

# 2. The King and Head of the Church {-}

<div id="chapter-slug-2-the-king-and-head-of-the-church"></div>

<ol class="ch2">
<li class="no-indent"><a id="2"></a>Jesus Christ, upon whose shoulders the government is, whose name is called Wonderful, Counsellor, the Mighty God, the Everlasting Father, the Prince of Peace; of the increase of whose government and peace there shall be no end; who sits upon the throne of David, and upon His kingdom to order it and to establish it with judgment and with justice from henceforth, even for ever; having all power given unto him in heaven and in earth by the Father, who raised him from the dead, and set him on His own right hand, far above all principality and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come, and hath put all things under His feet, and gave him to be the Head over all things to the Church, which is His body, the fullness of him that filleth all in all; He, being ascended up far above all heavens, that He might fill all things, received gifts for His Church, and gave all officers necessary for the edification of His Church and the perfecting of His saints.</li>
<li class="no-indent">Jesus, the Mediator, the sole Priest, Prophet, King, Savior, and Head of the Church, contains in himself, by way of eminency, all the offices in His Church, and has many of their names attributed to him in the Scriptures. He is Apostle, Teacher, Pastor, Minister, and Bishop, and the only Lawgiver in Zion. It belongs to His Majesty from His throne of glory, to rule and teach the Church, through His Word and Spirit, by the ministry of men; thus mediately exercising His own authority, and enforcing His own laws, unto the edification and establishment of His kingdom.</li>
<li class="no-indent">Christ, as King, has given to His Church, officers, oracles and ordinances; and especially has He ordained therein His system of doctrine, government, discipline, and worship; all which are either expressly set down in Scripture, or by good and necessary consequence may be deduced therefrom; and to which things He commands that nothing be added, and that from them naught be taken away.</li>
<li class="no-indent">Since the ascension of Jesus Christ to heaven, He is present with the Church by His Word and Spirit, and the benefits of all His offices are effectually applied by the Holy Spirit.</li>
</ol>

# 3. The Visible Church Defined {-}

<div id="chapter-slug-3-the-visible-church-defined"></div>

<ol class="ch3">
<li class="no-indent"><a id="3"></a>The Visible Church before the law, under the law, and now under the Gospel, is one and the same, and consists of all those who make profession of the true religion, together with their children.</li>
<li class="no-indent"><a id="3.2"></a>This visible unity of the body of Christ, though obscured, is not destroyed by its division into different denominations of professing Christians; but all of these which maintain the Word and Sacraments in their fundamental integrity are to be recognized as true branches of the Church of Jesus Christ.</li>
<li class="no-indent"><a></a>It is according to scriptural example that the Church should be divided into many individual churches.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-4-the-nature-and-extent-of-church-power" title="4. The Nature and Extent of Church Power">
<header>
<h1 class="chapter-title">4. The Nature and Extent of Church Power</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch4">
<li class="no-indent"><a id="4"></a>The power which Christ has committed to His Church vests in the whole body, the rulers and the ruled, constituting it a spiritual commonwealth. This power, as exercised by the people, extends to the choice of those officers whom He has appointed in His Church.</li>
<li class="no-indent">Ecclesiastical power, which is wholly spiritual, is twofold: the officers exercise it sometimes severally, as in preaching the Gospel, administering the sacraments, reproving the erring, visiting the sick, and comforting the afflicted, which is the power of order; and they exercise it sometimes jointly in Church courts, after the form of judgment, which is the power of jurisdiction.</li>
<li class="no-indent">The sole functions of the Church as a kingdom and government distinct from the civil commonwealth, are to proclaim, to administer, and to enforce the law of Christ revealed in the Scriptures.</li>
<li class="no-indent">The Church, with its ordinances, officers, and courts, is the agency which Christ has ordained for the edification and government of His people, for the propagation of the faith, and for the evangelization of the world. The power of the Church is exclusively spiritual; that of the State includes the exercise of force. The constitution of the Church derives from divine revelation; the constitution of the State will also be determined by human reason and the course of providential events. The Church has an obligation to speak prophetically to the civil magistrates, reminding them their authority is from God and they are to rule according to God’s Law; the Church has no authority to construct or modify a government for the State, and the State has no authority to frame a creed or polity for the Church. &#8220;Render unto Caesar the things that are Caesar&#8217;s and to God the things that are God&#8217;s.&#8221;<span data-type="footnote" class="footnote">Matthew 22:21.</span></li>
<li class="no-indent">The exercise of ecclesiastical power, whether joint or several, has the divine sanction, when in conformity with the statutes enacted by Christ, the Lawgiver, and when put forth by courts or by officers appointed thereunto in His Word.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-5-the-particular-church" title="5. The Particular Church">
<header>
<h1 class="chapter-title">5. The Particular Church</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch5">
<li class="no-indent"><a id="5.1"></a>A particular church consists of a number of professing Christians, with their children, associated together for divine worship and godly living, agreeably to the Scriptures, and submitting to the lawful government of Christ&#8217;s Kingdom.</li>
<li class="no-indent">Its officers are the Pastor(s), the Ruling Elders, and the Deacons.</li>
<li class="no-indent">Its jurisdiction being a joint power, is lodged in the hands of the church Session, consisting of the Pastor(s) and Ruling Elders.</li>
<li class="no-indent">To the Deacons belong the collection and administration of the offerings of mercy and benevolence of the people for the relief of those in need under the supervision of the Session.</li>
<li class="no-indent">The ordinances established by Christ, the Head, in His Church, are prayer; singing praises; reading, expounding and preaching the Word of God; administering the sacraments of Baptism and the Lord&#8217;s Supper; public solemn fasting and thanksgiving; catechising; making offerings for the relief of the poor and for other pious uses; exercising discipline; the taking of solemn vows; and the ordination to sacred office.</li>
<li class="no-indent">Churches destitute of the official ministration of the Word ought not to forsake the assembling of themselves together, but should be convened by the Session on the Lord&#8217;s Day, and at other suitable times, for prayer, praise, the reading and expounding of the Holy Scriptures, and exhortation, or the reading of a sermon of some approved minister. In like manner, Christians whose lot is cast in destitute regions ought to meet regularly for the worship of God.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-6-the-organization-of-a-particular-church" title="6. The Organization of a Particular Church">
<header>
<h1 class="chapter-title">6. The Organization of a Particular Church</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch6">
<li class="no-indent"><a id="6"></a>A mission church may be properly described in the same manner as the particular church is described in BCO <a href="#5.1">5.1</a>. It is distinguished from a particular church in that it has no permanent governing body, and thus must be governed or supervised by others. However, its goal is to mature and be organized as a particular church as soon as this can be done decently and in good order.
<ol type="a">
<li class="no-indent">Ordinarily, mission churches are established by Presbyteries within their boundaries.
<ol type="i">
<li class="no-indent">Initiatives to which the Presbytery may respond in establishing a mission church include, but are not limited to, the following:
<ol>
<li class="no-indent">The Presbytery establishes a mission church at its own initiative.</li>
<li class="no-indent">The Presbytery responds to the initiative of a Session of a particular church.</li>
<li class="no-indent">The Presbytery responds to the petition of an independent gathering of believers who have expressed their desire to become a congregation by submitting to the Presbytery a written request.</li>
</ol>
</li>
<li class="no-indent">In the event an existing non-Evangel Presbytery church is interested in coming into Evangel Presbytery, the Presbytery shall work with the church leadership to determine whether the church should come into Evangel Presbytery as a mission church or seek Presbytery approval to be received under the provisions of BCO <a href="#15.7">15.7</a>.</li>
<li class="no-indent">Should it become necessary, the Presbytery may dissolve the mission church. Church members enrolled should be cared for according to the procedures of BCO <a href="#15.9">15.9</a>.</li>
</ol>
</li>
<li class="no-indent">The mission church, because of its transitional condition, requires a temporary system of government. Depending on the circumstances and at its own discretion, the Presbytery may provide for such government in one of several ways:
<ol type="i">
<li class="no-indent">Appoint an Evangelist as prescribed in BCO <a href="#9.6">9.6</a>.</li>
<li class="no-indent">Cooperate with the Session of a particular church in arranging a mother-daughter relationship with a mission church. The Session may then serve as the temporary governing body of the mission church.</li>
<li class="no-indent">Appoint a BCO <a href="#17.1">17.1</a> commission to serve as a temporary Session of the mission church. When a minister of the Presbytery has been approved to serve as pastor of the mission church, he shall be included as a member of the commission and serve as its moderator. The temporary system of government shall record and submit its records to Presbytery for annual review in the same manner as Sessions of particular churches.</li>
</ol>
</li>
<li class="no-indent"><a id="6.1.c"></a>Pastoral ministry for the mission church may be provided:
<ol type="i">
<li class="no-indent">by a minister of the Presbytery called by Presbytery to serve as pastor, or</li>
<li class="no-indent">by stated, student, or ruling elder supply (BCO <a href="#24.5">24.5-6</a>), or</li>
<li class="no-indent">by a series of qualified preachers approved by the temporary government</li>
</ol>
</li>
<li class="no-indent"><a id="6.1.d"></a>The temporary government shall receive members (BCO <a href="#14.5">14.5</a>) into the mission church according to the provisions of BCO <a href="#53">53</a> so far as they may be applicable. As members of the mission church those received are communing or non-communing members of Evangel Presbytery.
<ol type="i">
<li class="no-indent">If there is a minister approved by Presbytery to serve the mission church as its pastor (BCO <a href="#6.1.c">6.1.c</a>), each member so received shall be understood to assent to the call of that minister and to affirm the promises made to the pastor in BCO <a href="#23.10">23.10</a>.</li>
<li class="no-indent">Meetings of the members of the mission church shall be governed according to the provisions of BCO <a href="#27">27</a> so far as they may be applicable.</li>
</ol>
</li>
<li class="no-indent">Mission churches and their members shall have the right of judicial process to the court having oversight of their temporary governing body.</li>
<li class="no-indent">Mission churches shall maintain a roll of communicant and non-communicant members, in the same manner as, but separate from, other particular churches.</li>
<li class="no-indent">It is the intention of Evangel Presbytery that mission churches enjoy the same status as particular churches in relation to civil government.</li>
</ol>
</li>
<li class="no-indent">A new particular church can be organized only by the authority of Presbytery.
<ol type="a">
<li class="no-indent">The Presbytery should establish standing rules setting forth the prerequisites that qualify a mission church to begin the organization process, e.g., the minimum number of petitioners and the level of financial support to be provided by the congregation. The number of officers sufficient to constitute the quorum for a session shall be necessary to complete the organization process.</li>
<li class="no-indent">The temporary government of the mission church shall oversee the steps necessary for organization.</li>
<li class="no-indent">When among the members of the mission congregation to be organized there are men who appear qualified as officers, the temporary government shall examine these men and present a slate of candidates for election by the congregation.</li>
<li class="no-indent">The election of officers shall normally take place at least two weeks prior to the date of the organization service. However, the effective date of service for the newly elected officers shall be upon the completion of the organization service.</li>
<li class="no-indent">If deacons are not elected, the duties of the office shall devolve upon the session, until deacons can be secured.</li>
<li class="no-indent">If there is a minister approved by Presbytery to serve the mission church as its pastor, and members of the mission church have been received according to BCO <a href="#6.1.d">6.1.d</a>, the temporary session shall call a congregational meeting at which the congregation may, by majority vote, call the organizing pastor to be their pastor without the steps of BCO <a href="#22">22</a>. If no such minister has been appointed, or the minister or congregation choose not to continue the pastoral relationship of the newly organized church, a pastor shall be called as follows:
<ol type="i">
<li class="no-indent">The temporary government shall oversee the election of a pastor according the provisions of BCO <a href="#22">22</a> so far as they are applicable. If a candidate is to be proposed before the organization, the congregational meeting to elect a pastor shall take place early enough for Presbytery to consider and approve the pastor’s call prior to the service of organization. This may be the same meeting called for the election of other officers.</li>
<li class="no-indent">The ordination and/or installation shall be according to the provisions of BCO <a href="#23">23</a> so far as they are applicable. The service may take place at the service of organization.</li>
</ol>
</li>
<li class="no-indent">In order to proceed to organization as a particular church the members of the mission church shall sign a petition to Presbytery requesting the same.</li>
<li class="no-indent">Upon Presbytery’s approval of the petition, Presbytery shall appoint an organizing commission and shall set the date and time of the organization service.</li>
<li class="no-indent">At the service of organization the following elements shall be included in the order deemed by the organizing commission to be appropriate:
<ol type="i">
<li class="no-indent">The organizing commission shall ordain and/or install ruling elders and/or deacons according to the provisions of BCO <a href="#26.5">26.5</a> so far as they may be applicable.</li>
<li class="no-indent">If a pastor is being ordained and/or installed at the service, the organizing commission shall act according to the provisions of BCO <a href="#23">23</a> so far as they may be applicable.</li>
<li class="no-indent">A member of the organizing commission shall require communicant members of the mission church present to enter into covenant, by answering the following question affirmatively:<br />
<blockquote>
<p>Do you, in reliance on God for strength, solemnly promise and covenant that you will walk together as a particular church, on the principles of the faith and order of Evangel Presbytery, and that you will be zealous and faithful in maintaining the purity and peace of the whole body?</p>
</blockquote>
</li>
<li class="no-indent">A member of the organizing commission shall then say:<br />
<blockquote>
<p>I now pronounce and declare that you are constituted a church according to the Word of God and the faith and order of Evangel Presbytery. In the name of the Father and of the Son and of the Holy Spirit. Amen.</p>
</blockquote>
</li>
</ol>
</li>
</ol>
</li>
<li class="no-indent">Upon organization, the newly elected session should meet as soon as is practicable to elect a stated clerk and formulate a budget. If there is no pastor, the session may elect as moderator one of their own number or any teaching elder of the Presbytery with Presbytery’s approval. Alternatively, the administrative committee has the power of committee to appoint a moderator for the new session, giving approval on behalf of Presbytery. Further, if there is no pastor, action shall be taken to secure, as soon as practicable, the regular administration of Word and Sacraments.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-7-church-members" title="7. Church Members">
<header>
<h1 class="chapter-title">7. Church Members</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<p class="no-indent"><a id="7"></a>The members of this visible Church catholic are all those persons in every nation who make profession of their faith in the Lord Jesus Christ and promise submission to His laws. Communing members are those who have made a profession of faith in Christ, have been baptized, and have been admitted by the Session to the Lord’s Table. The children of communing members are, through the covenant and by right of birth, non-communing members of the church. The children of communing members holding credo-baptistic convictions are non-communing members in the sense that they are entitled to the church’s care, love, discipline, and training, with a view to their embracing Christ and thus possessing personally all the benefits of the covenant. The children of communing members holding paedo-baptistic convictions are non-communing members in the sense that they are entitled to baptism and to the church’s care, love, discipline, and training, with a view to their embracing Christ and thus possessing personally all the benefits of the covenant.</p>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-8-church-officers-general-classification" title="8. Church Officers—General Classification">
<header>
<h1 class="chapter-title">8. Church Officers—General Classification</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch8">
<li class="no-indent"><a id="8"></a>Under the New Testament, our Lord at first collected His people out of different nations, and united them to the household of faith by the mission of the apostles, endued with miraculous gifts. This office has ceased.</li>
<li class="no-indent">The whole polity of the Church consists in doctrine, government, and distribution. And the ordinary and perpetual officers in the Church are Pastors, or Ministers of the Word, who are commissioned to preach the Gospel and administer the sacraments; Ruling Elders, whose office is to have the government and spiritual oversight of the church; and Deacons, whose office is to collect and administer the people&#8217;s offerings of mercy and benevolence and to minister to their physical and material needs. In accordance with the Scripture, these offices are open to men only.</li>
<li class="no-indent">No one who holds office in the Church ought to usurp authority therein, or receive any official titles of spiritual preeminence, except such as are employed in the Scriptures.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-9-the-minister-of-the-word" title="9. The Minister of the Word">
<header>
<h1 class="chapter-title">9. The Minister of the Word</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch9">
<li class="no-indent"><a id="9"></a>This office is the first in the Church, both for dignity and usefulness. The person who fills it has in Scripture different titles expressive of his various duties. As he has the oversight of the flock of Christ, he is termed Bishop. As he feeds them with spiritual food, he is termed Pastor. As he serves Christ in the Church, he is termed Minister. As it is his duty to be grave and prudent, and an example to the flock, and to govern well in the house and kingdom of Christ, he is termed Presbyter or Elder. As he is sent to declare the will of God to sinners, and to beseech them to be reconciled to God through Christ, he is termed Ambassador. As he bears the glad tidings of salvation to the ignorant and perishing, he is termed Evangelist. As he stands to proclaim the Gospel, he is termed Preacher. As he expounds the Word, and by sound doctrine both exhorts and convinces the gainsayer, he is termed Teacher. As he dispenses the manifold grace of God, and the ordinances instituted by Christ, he is termed Steward of the mysteries of God. These titles do not indicate different grades of office, but all describe one and the same officer.</li>
<li class="no-indent">He that fills this office should possess a competency of human learning, and be blameless in life, sound in the faith, and apt to teach; he should exhibit a sobriety and holiness of life becoming the Gospel; he should rule his own house well; and should have a good report of them that are without.</li>
<li class="no-indent">As the Lord has given different gifts to the Ministers of the Word, and has committed to them various works to execute, the Church is authorized to call and appoint them to labor as Pastors, Teachers, and Evangelists, and in such other works as may be needful to the Church, according to the gifts in which they excel.</li>
<li class="no-indent">When a Minister is called to labor as a Pastor, it belongs to his office to pray for and with his flock, as the mouth of the people unto God; to feed the flock, by reading, expounding, and preaching the Word; to direct the congregation in singing the praises of God; to administer the sacraments; to catechize the children and youth; to visit officially the people, devoting especial attention to the poor, the sick, the afflicted, and the dying; and with the other Elders, to exercise the joint power of government—and to that end, he shall be an ex officio member of every board and committee of the church.</li>
<li class="no-indent">When a Minister is appointed to be a teacher in a school of divinity, or to give instruction in the doctrines and duties of religion to youth assembled in a college or university, it appertains to his office to take a pastoral oversight of those committed to his charge, and to be diligent in sowing the seed of the Word and gathering the fruit thereof, as one who watches for souls.</li>
<li class="no-indent"><a id="9.6"></a>When a Minister is appointed to the work of the Evangelist, he is commissioned to preach the Word and administer the sacraments in foreign countries, frontier settlements, or the destitute parts of the Church; and to him may be entrusted power to organize churches, and ordain Ruling Elders and Deacons therein. He is commissioned for a renewable term of twelve months to preach the Word, to administer the Sacraments, to receive and dismiss members of mission churches, and to train potential officers.</li>
<li class="no-indent">When a Minister is called to labor through the press, in an educational setting, or in any other similar necessary work, it shall be incumbent on him to make full proof of his ministry by disseminating the Gospel for the edification of the Church. He shall give a report of his work to the Presbytery annually.</li>
<li class="no-indent">The Presbytery may, at its discretion, approve the call of a Minister to work with an organization outside the jurisdiction of Evangel Presbytery, provided that he be engaged in preaching and teaching the Word, that the Presbytery be assured he will have full freedom to maintain and teach the doctrine of our Church, and that he submit a written report on his work to the Presbytery at least annually.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-10-the-ruling-elder" title="10. The Ruling Elder">
<header>
<h1 class="chapter-title">10. The Ruling Elder</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch10">
<li class="no-indent"><a id="10"></a>As there were in the Church, under the law, Elders of the people for the government thereof, so in the Gospel Church, Christ has furnished others besides the Ministers of the Word with gifts and commission to govern when called thereunto, which officers are entitled Ruling Elders.</li>
<li class="no-indent">These Ruling Elders possess the same authority and eligibility to office in the courts of the Church as the Ministers of the Word. They should, moreover, cultivate zealously their aptness to teach the Bible and should improve every opportunity of doing so, to the end that destitute places, mission points, and churches without Pastors may be supplied with religious services.</li>
<li class="no-indent">Those who fill this office ought to be blameless in life and sound in the faith; they should be men of wisdom and discretion; and by the holiness of their walk and conversation should be examples to the flock.</li>
<li class="no-indent">Ruling Elders, the immediate representatives of the people, are chosen by them, that, in conjunction with the Pastors or Ministers, they may exercise government and discipline, including determining those qualified to receive the sacraments and assisting in the administration thereof, and take the oversight of the spiritual interests of the particular church, and also of the Church generally, when called thereunto. It appertains to their office, both severally and jointly, to watch diligently over the flock committed to their charge, that no corruption of doctrine or of morals enter therein. Evils which they cannot correct by private admonition they should bring to the notice of the Session. They should visit the people at their homes, especially the sick; they should instruct the ignorant, comfort the mourner, nourish and guard the children of the Church; and all those duties which private Christians are bound to discharge by the law of love are especially incumbent upon them by divine vocation, and are to be discharged as official duties; they should pray with and for the people; they should be careful and diligent in seeking the fruit of the preached Word among the flock; and should inform the Pastor of cases of sickness, affliction, and awakening, and of all others which may need his special attention. As overseers, Ruling Elders shall also appoint a Treasurer responsible for financial matters of the church and safekeeping of church funds, who shall report to the Session when requested.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-11-the-deacon" title="11. The Deacon">
<header>
<h1 class="chapter-title">11. The Deacon</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch11">
<li class="no-indent"><a id="11"></a>The office of Deacon is set forth in the Scriptures as ordinary and perpetual in the Church. The office is one of sympathy and service, after the example of the Lord Jesus; it expresses also the communion of saints, especially in their helping one another in time of need.</li>
<li class="no-indent">It is the duty of the Deacons to minister to those who are in need, to the sick, to the friendless, and to any who may be in distress. It is their duty also to develop the grace of liberality in the members of the church, to devise effective methods of collecting the gifts of the people, and to distribute these gifts among the objects to which they are contributed. They shall keep in proper repair the church edifice and other buildings and all physical property belonging to the congregation. In the discharge of their duties the Deacons are under the supervision and authority of the Session. In a church in which it is impossible for any reason to secure Deacons, the duties of the office shall devolve upon the Ruling Elders.</li>
<li class="no-indent">To the office of Deacon, which is spiritual in nature, should be chosen men of spiritual character, honest repute, exemplary lives, brotherly spirit, warm sympathies, and sound judgment.</li>
<li class="no-indent">The Deacons of a particular church shall be organized as a Board, of which the Pastor, or an Elder or Pastor of his choosing, shall be an ex officio member. The Board of Deacons shall elect a Chairman to be presented for the approval of the Session. The Board of Deacons shall elect their Secretary. The Board shall meet at least once a quarter, and whenever requested by the Session. The Board of each church shall determine the number necessary for a quorum, subject to the Session’s approval. The Board shall keep a record of its proceedings, and of all funds and their distribution, and shall submit its minutes to the Session once a year, and at other times upon request of the Session. It is desirable that the Session and the Board of Deacons meet in joint session once a year to confer on matters of common interest.</li>
<li class="no-indent">Deacons may properly be appointed by the higher courts to serve on committees, especially as treasurers. It may also be helpful for the Church courts, when devising plans of church finance, to invite wise and consecrated Deacons to their counsels.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-12-church-courts-in-general" title="12. Church Courts—In General">
<header>
<h1 class="chapter-title">12. Church Courts—In General</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch12">
<li class="no-indent"><a id="12"></a>The Church is governed by various courts, in regular gradation; which are all, nevertheless, Presbyteries, as being composed exclusively of Presbyters.</li>
<li class="no-indent">These courts are church Sessions and Presbyteries.</li>
<li class="no-indent">The Pastor is, for prudential reasons, Moderator of the Session. The Moderator of the Presbytery shall be chosen at each stated meeting or for a period of time up to one year; and the Moderator, or, in case of his absence, the last Moderator present, or the oldest Minister in attendance, shall open the next meeting with a sermon, unless it be highly inconvenient, and shall hold the chair until a new Moderator be chosen. Provided, however, that when the Moderator of one of the higher courts is a Ruling Elder, the preaching of the opening sermon, or any other official duty, the performance of which requires the exercise of functions pertaining only to the Teaching Elder, shall be remitted by him for execution to such Minister of the Word, being a member of the court, as he may select.
<p class="no-indent">The Moderator has all authority necessary for the preservation of order and for the proper and expeditious conduct of all business before the court, and for convening and adjourning the court according to its own ruling. In any extraordinary emergency, he may, by an appropriate form of communication, change the time or place, or both, of meetings to which the court stands adjourned, giving reasonable notice thereof.</p>
</li>
<li class="no-indent">It is the duty of the Clerk, besides recording the transactions, to preserve the records carefully, and to grant extracts from them whenever properly required. Such extracts, under the hand of the Clerk, shall be evidence to any ecclesiastical court, and to every part of the Church.</li>
<li class="no-indent">Every meeting of the Presbytery and Session shall be opened and closed with prayer, and in closing the final session a psalm or hymn may be sung and the benediction pronounced.</li>
<li class="no-indent">The expenses of Ministers and Ruling Elders in their attendance on the courts shall be defrayed by the bodies which they respectively represent.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-13-jurisdiction-of-church-courts" title="13. Jurisdiction of Church Courts">
<header>
<h1 class="chapter-title">13. Jurisdiction of Church Courts</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch13">
<li class="no-indent"><a id="13"></a>These assemblies are altogether distinct from the civil magistrate, nor have they any jurisdiction in political or civil affairs. They have no power to inflict temporal pains and penalties, but their authority is in all respects moral or spiritual.</li>
<li class="no-indent">The jurisdiction of Church courts is only ministerial and declarative, and relates to the doctrines and precepts of Christ, to the order of the Church, and to the exercise of discipline. <em>First</em>, They can make no laws binding the conscience; but may frame doctrinal standards, bear testimony against error in doctrine and immorality in practice, within or without the pale of the Church, and decide cases of conscience. <em>Secondly</em>, They have power to establish rules for the government, discipline, worship, and extension of the Church, which must be agreeable to the doctrines relating thereto contained in the Scriptures, the circumstantial details only of these matters being left to the Christian prudence and wisdom of church officers and courts. <em>Thirdly</em>, They possess the right of requiring obedience to the laws of Christ. Hence, they admit those qualified to sealing ordinances and to their respective offices, and they exclude the disobedient and disorderly from their offices or from sacramental privileges; but the highest censure to which their authority extends is to cut off the contumacious and impenitent from the congregation of believers. <em>Moreover</em>, they possess all the administrative authority necessary to give effect to the powers.</li>
<li class="no-indent">All Church courts are one in nature, constituted of the same elements, possessed inherently of the same kinds of rights and powers, and differing only as the Constitution may provide. Yet it is according to scriptural example, and needful to the purity and harmony of the whole Church, that disputed matters of doctrine and order, arising in the lower courts, should be referred to the higher courts for decision.</li>
<li class="no-indent">For the orderly and efficient dispatch of ecclesiastical business, it is necessary that the sphere of action of each court should be distinctly defined. The Session exercises jurisdiction over a single church; the Presbytery over what is common to the Ministers, Sessions, and churches within a prescribed district. The jurisdiction of these courts is limited by the express provisions of the Constitution. Every court has the right to resolve questions of doctrine and discipline seriously and reasonably proposed, and in general to maintain truth and righteousness, condemning erroneous opinions and practices which tend to the injury of the peace, purity, or progress of the Church; and although each court exercises exclusive original jurisdiction over all matters specially belonging to it, the lower courts are subject to the review and control of the higher courts, in regular gradation. Hence, these courts are not separate and independent tribunals; but they have a mutual relation, and every act of jurisdiction is the act of the whole Church performed by it through the appropriate organ.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-14-the-church-session" title="14. The Church Session">
<header>
<h1 class="chapter-title">14. The Church Session</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch14">
<li class="no-indent"><a id="14"></a>The church Session consists of the Pastor and Associate Pastors, if there be any, and the Ruling Elders of a church. If there are three or more Ruling Elders, the Pastor and two Ruling Elders shall constitute a quorum. If there are fewer than three Ruling Elders, the Pastor and one Ruling Elder shall constitute a quorum. When a church has no Pastor, the session shall ask the Presbytery to appoint a pastor to serve as moderator of session. If there are five or more Ruling Elders, three, along with the appointed moderator, shall constitute a quorum; if there are fewer than five Ruling Elders, two, along with the appointed moderator, shall constitute a quorum; if there is only one Ruling Elder, he does not constitute a Session, but he should take spiritual oversight of the church, should represent it at Presbytery, should grant letters of dismissal, and should report to the Presbytery any matter needing the action of a Church court. However, any Session, by a majority vote of its members, may fix its own quorum, provided that it is not smaller than the quorum stated in this paragraph.</li>
<li class="no-indent">The Pastor is, by virtue of his office, the Moderator of the Session. In his absence, if an emergency should arise requiring immediate action, the Session may elect one of its members to preside. In any case where such meeting is required, the pastor must be informed before the meeting is held. Should prudential reasons at any time make it advisable for a Minister other than the Pastor to preside, the Pastor may, with the concurrence of the Session, invite a Minister of the same Presbytery to perform this service.</li>
<li class="no-indent">When a church is without a Pastor, the Moderator of the Session shall be either a Minister appointed for that purpose by the Presbytery, or one invited by the Session to preside on a particular occasion. When it is inconvenient to procure such a Moderator, the Session may elect one of its own members to preside. In judicial cases, the Moderator shall be a Minister of the Presbytery to which the church belongs.</li>
<li class="no-indent"><a id="14.4"></a>In churches where there are two or more Pastors, the Senior Pastor shall preside. An Associate Pastor or Assistant Pastor may substitute for the Senior Pastor as moderator of the Session at the discretion of the Senior Pastor and Session.</li>
<li class="no-indent"><a id="14.5"></a>The church Session is charged with maintaining the spiritual government of the church, for which purpose it has power to inquire into the knowledge, principles, and Christian conduct of the church members under its care; to censure those found delinquent; to see that parents do not neglect to bring up their children in the nurture and admonition of the Lord; to receive members into the communion of the church; to grant letters of dismissal to other churches, which, when given to parents, shall always include the names of their minor children and whether they have been baptized and whether they have been admitted to the Lord’s Table; to examine, ordain, and install Ruling Elders and Deacons on their election by the church, and to require these officers to devote themselves to their work; to examine the records of the proceedings of the Deacons; to oversee, if established, Sunday Schools and all other ministries and discipleship; to order collections for pious uses; to take the oversight of the singing in the public worship of God; to assemble the people for worship when there is no Minister; to admit persons qualified to receive the sacraments and exercise authority concerning the time, place, frequency, and elements of the sacraments; to concert the best measures for promoting the spiritual interests of the church and congregation; to observe and carry out the lawful injunctions of the higher courts; and to appoint representatives to the Presbytery, who shall, on their return, make report of their diligence.</li>
<li class="no-indent">The Session shall hold stated meetings at least quarterly. Moreover, the Pastor has power to convene the Session when he may judge it requisite; and he shall always convene it when requested to do so by any two of the Ruling Elders; and when there is no Pastor, it may be convened by two Ruling Elders. The Session shall also convene when directed so to do by the Presbytery.</li>
<li class="no-indent">Every Session shall keep a fair record of its proceedings, which record shall be at least once in every year submitted to the inspection of the Presbytery.</li>
<li class="no-indent">Every Session shall keep a fair record of baptisms, of those admitted to the Lord&#8217;s table, of non-communing members, and of the births, marriages, deaths, and dismissions of church members and of any baptisms and marriage ceremonies presided over by the pastors of the church outside its bounds.</li>
<li class="no-indent">Meetings of the Session shall be opened and closed with prayer.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-15-the-presbytery" title="15. The Presbytery">
<header>
<h1 class="chapter-title">15. The Presbytery</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch15">
<li class="no-indent"><a id="15"></a><a id="15.1"></a>The Presbytery consists of all the Ministers and churches within its bounds that have been accepted by the Presbytery. All Ministers and Ruling Elders in good standing of Evangel Presbytery shall have floor privileges.
<p class="no-indent">In presbytery votes, in order to promote parity between Ministers and Ruling Elders and to prevent centralization of power in large churches, voting privileges for members of presbytery shall be capped at two Ministers per church. Up to two Ruling Elders from each church may be appointed by their sessions as voting commissioners. A voting Ruling Elder shall be added to each church’s allowed number of voting commissioners for each full one hundred communicant members over fifty members, up to four additional voting Ruling Elders.</p>
<p class="no-indent">The Senior Pastor of each church, if present, shall be a voting member of Presbytery. All other voting members shall be chosen by each church’s session. All Ministers and Ruling Elders may serve as voting members of presbytery committees and commissions.</p>
</li>
<li class="no-indent"><a id="15.2"></a>A Minister shall be required to hold his membership in the Presbytery within whose bounds he resides, unless there are reasons which are satisfactory to his Presbytery why he should not do so. When a minister labors outside the geographical bounds of, or in a work not under the jurisdiction of his Presbytery, at home or abroad, it shall be only with the full concurrence of and under circumstances agreeable to his Presbytery, and to the Presbytery within whose geographical bounds he labors, if one exists. When a minister shall continue on the rolls of his Presbytery without a call to a particular work for a prolonged period, not exceeding three years, the procedure as set forth in BCO <a href="#37.10">37.10</a> shall be followed. A minister without call shall make or file a report to his Presbytery at least once each year.</li>
<li class="no-indent">Every Ruling Elder not known to the Presbytery shall produce a certificate of his regular appointment from the Session of the church which he represents.</li>
<li class="no-indent">Any three Ministers belonging to the Presbytery, together with at least three Ruling Elders, representing at least three churches, being met at the time and place appointed, shall be a quorum competent to proceed to business. However, any Presbytery, by a majority vote of those present at a stated meeting, may fix its own quorum, provided it is not smaller than the quorum stated in this paragraph.</li>
<li class="no-indent">Ministers seeking admission to a Presbytery shall be examined on Christian experience, and also concerning their views in theology, sacraments, and church government. If applicants come from other denominations, the Presbytery shall examine them thoroughly in knowledge and views as required by BCO <a href="#23.4">23.4</a> and require them to answer in the affirmative the questions put to candidates at their ordination. Ordained ministers from other denominations being considered by Presbyteries for reception may come under the extraordinary provisions set forth in BCO <a href="#23.4">23.4</a>. Presbyteries shall also require ordained ministers coming from other denominations to state the specific instances in which they may differ with the Confession of Faith and Catechisms in any of their statements and/or propositions, which differences the court shall judge in accordance with BCO <a href="#23.4.e">23.4, sections e-f</a>. All Ministers shall be required to submit their exceptions to the Constitution of this church BCO <a href="#29.1">29.1</a> in writing to the Presbytery prior to their examination. No exceptions to the Book of Church Order are permitted; however, a Minister may believe a change to the Book of Church Order is necessary and seek that change through the amendment process established therein.</li>
<li class="no-indent">The Presbytery shall cause to be transcribed, in some convenient part of the book of records, the obligations required of Ministers at their ordination, which shall be subscribed by all admitted to membership, in the following or like form, namely: “I, [Name], do sincerely receive and subscribe to the above obligation as a just and true exhibition of my faith and principles, and do resolve and promise to exercise my ministry in conformity thereunto.”</li>
<li class="no-indent"><a id="15.7"></a>The Presbytery, before receiving into its membership any church, shall designate a commission to meet with the church’s ruling elders to make certain that the elders understand and can sincerely adopt the doctrines and polity of Evangel Presbytery as contained in its Constitution. In the presence of the commission, the ruling elders shall be required to answer affirmatively the questions required of officers at their ordination.</li>
<li class="no-indent"><a id="15.8"></a>The Presbytery has power to receive and issue appeals, complaints, and references brought before it in an orderly manner, and in cases in which the Session cannot exercise its authority, shall have power to assume original jurisdiction; to receive under its care candidates for the ministry; to examine and license candidates for the holy ministry; to receive, dismiss, ordain, install, remove, and judge Ministers; to review the record of church Sessions, redress whatever they may have done contrary to order, and take effectual care that they observe the Constitution of the Church; to establish the pastoral relation, and to dissolve it at the request of one or both of the parties, or where the interests of religion imperatively demand it; to set apart Evangelists to their proper work; to require Ministers to devote themselves diligently to their sacred calling and to censure the delinquent; to see that the lawful injunctions of the higher courts are obeyed; to condemn erroneous opinions which injure the purity or peace of the Church; to visit churches for the purpose of inquiring into and redressing the evils that may have arisen in them; to unite or divide churches, at the request of the members thereof; to form and receive new churches; to take special oversight of churches without Pastors; to dissolve churches; to concert measures for the enlargement of the Church within its bounds; in general, to order whatever pertains to the spiritual welfare of the churches under its care. The Presbytery’s power in no way diminishes the absolute right of a church to withdraw or secede from the Presbytery. In doing so, the church retains all right, title, and interest in the church’s real and personal property.</li>
<li class="no-indent"><a id="15.9"></a>The Presbytery shall keep a full and fair record of its proceedings; and all the important changes which may have taken place, such as the licensures, the ordinations, the receiving or dismissing of members, the removal of members by death, the union and the division of churches, and the formation of new ones.</li>
<li class="no-indent">The Presbytery shall meet at least twice a year on its own adjournment. When any emergency shall require a meeting earlier than the time to which the Presbytery stands adjourned, the Moderator shall, at the request, or with the concurrence, of two Ministers and two Ruling Elders of different churches, call a special meeting. Should the Moderator be for any reason unable to act, the Stated Clerk shall, under the same requirements, issue the call. If both Moderator and Stated Clerk are unable to act, any three Ministers and two Ruling Elders of different churches shall have power to call a meeting. Notice of the special meeting shall be sent not less than ten days in advance to each Minister and to the Session of every church without a Pastor. In the notice the purpose of the meeting shall be stated, and no business other than that named in the notice is to be transacted.</li>
<li class="no-indent">Ministers in good standing in other Presbyteries, or in any evangelical Church, being present at any meeting of Presbytery, may be invited to sit as visiting brethren. It is proper for the Moderator to introduce these brethren to the Presbytery. They shall be granted the privilege of the floor, but no voting privileges.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-16-provisions-concerning-baptism" title="16. Provisions Concerning Baptism">
<header>
<h1 class="chapter-title">16. Provisions Concerning Baptism</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch16">
<li class="no-indent"><a id="16"></a>Being diligent to preserve the unity of the Spirit in the bond of peace” (Eph. 4:3), the members and churches of the Presbytery are committed to the formal communion of Christians who hold differing convictions concerning time and mode of baptism. The members and churches of the Presbytery agree to the following:
<ol type="a">
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Both paedo-baptists and credo-baptists recognize the Westminster Standards (Confession of Faith and Larger and Shorter Catechisms) as an excellent summary of the system of doctrine taught in Scripture and believe submission to a single standard best promotes the peaceable government and unity of the Presbytery.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Evangel Presbytery will permit no exceptions to the Westminster Standards’ teaching that all who profess faith in Jesus Christ along with their children are members of the visible Church of Christ and all members of that visible Church are under obligation to love, honor and obey their God and proper subjects of the discipline of the Church.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Exceptions to the Westminster Standards concerning baptism will be granted in the following areas, and such exceptions will be deemed “not out of accord with any fundamental of our system of doctrine because the difference is neither hostile to the system nor strikes at the vitals of religion” (BCO <a href="#23.4.f">23.4.f</a>):</span>
<ol>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Time of baptism: Many God-fearing men and women are of the conviction that though children of believers are members of the visible Church, rightly treated as such by the church, the application of baptism is so tied to the credible profession of faith by the individual that it is properly applied subsequent to that profession.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Mode of baptism: Many God-fearing men and women are also of the conviction that baptism is rightly administered by immersion only rather than by pouring or sprinkling.</span></li>
</ol>
</li>
</ol>
</li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Exceptions to the Westminster Standards’ teaching on baptism may be granted both to churches and to pastors ordained by presbytery. Churches granted an exception may ordain officers whose beliefs are in accord with their exception.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">A church may declare an exception to the Westminster Standards to permit both credo-baptist and paedo-baptist views and practice by officers and pastors. Ordinarily, a church’s bylaws will indicate whether officers must be exclusively credo-baptist, exclusively paedo-baptist, or may be comprised of both.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Exceptions granted to the Westminster Standards’ teaching on baptism are effective in perpetuity and may only be revoked by a process effecting a change to Evangel Presbytery’s constitution.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Churches granted an exception to the Westminster Standards’ teaching on baptism may reverse that exception through a duly-effected process of bylaw change. Churches which enter Evangel Presbytery without claiming an exception in the area of baptism may claim an exception after a duly-effected bylaw change and a majority vote approving the new exception by the presbytery.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Charity will be shown to those holding differing views on the time and mode of baptism in the following ways:</span>
<ol type="a">
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Churches holding exceptions on baptism will honor the baptisms of infants and children who were baptized in accordance with the Westminster Standards.</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">Churches embracing the Westminster Standards’ on time and mode of baptism will:</span>
<ol>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">deny that the “great sin” of “contemning or neglecting” baptism spoken of in WCF 28.5 refers to a principled credo-baptist’s delay of baptism until after a credible profession of faith</span></li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">accept as non-communicant members dedicated and non-dedicated children of members holding credo-baptist views</span></li>
</ol>
</li>
</ol>
</li>
<li class="no-indent"><span style="text-align: initial;font-size: 1em">The children of communing believers are non-communing members, though only in the strict and distinct sense as set forth in BCO <a href="#7">7</a>. A church’s membership roll shall include the children of communing members in a separate list, identifying them as non-communing members. However, such membership shall not be understood to be contrary to the convictions of the church and parents concerning infant baptism. This unity is possible because the church and parents understand the child is a proper recipient of the church’s care, love, discipline, and training, with a view to his embracing Christ and thus possessing personally all the benefits of the covenant.</span></li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-17-ecclesiastical-commissions" title="17. Ecclesiastical Commissions">
<header>
<h1 class="chapter-title">17. Ecclesiastical Commissions</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch17">
<li class="no-indent"><a id="17.1"></a>A Commission differs from an ordinary committee in this, that while a committee is appointed to examine, consider and report, a Commission is authorized to deliberate upon and conclude the business referred to it. It shall keep a full record of its proceedings, which shall be submitted to the court appointing it, entered on its minutes, and regarded and treated as the action of the court.</li>
<li class="no-indent">Among the matters that may be properly executed by Commissions are the taking of testimony in judicial cases, the ordination of Ministers, the installation of Ministers, the visitation of portions of the Church affected with disorder, and the organization of new churches.Every Commission appointed by Presbytery shall consist of at least two Ministers and two Ruling Elders, and the Presbytery at the time of the appointment of the Commission shall determine what the quorum shall be. However, should a Presbytery clothe a Commission with judicial powers and authority to conduct judicial process, or with power to ordain a Minister of the Gospel, the quorum of such Commission shall not be less than two Ministers and two Ruling Elders. When the ordination of a Minister is committed to a Commission, the Presbytery itself shall conduct the previous examination.</li>
<li class="no-indent">The Presbytery may, of its own motion, commit any judicial case coming before it by appeal or complaint to a Commission, and should ordinarily follow this procedure, especially when requested by one or both parties to the case. Such a Commission shall be appointed by the court from its members other than members of the court from which the case comes up. Two-thirds of the Commissioners shall be a quorum to attend to business. The Commission shall try the case in the manner prescribed by the Rules of Discipline; shall submit to the court a full statement of the case and the judgment rendered, all of which shall be entered on the minutes of the court and accepted as its action and judgment in the case.</li>
<li class="no-indent">The Presbytery shall have power to commit the various interests pertaining to the general work of evangelization to one or more Commissions.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-18-church-orders-the-doctrine-of-vocation" title="18. Church Orders—The Doctrine of Vocation">
<header>
<h1 class="chapter-title">18. Church Orders—The Doctrine of Vocation</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch18">
<li class="no-indent"><a id="18"></a>Ordinary vocation to office in the Church is the calling of God by the Spirit, through the inward testimony of a good conscience, the manifest approbation of God&#8217;s people, and the concurring judgment of a lawful court of the Church.</li>
<li class="no-indent">The government of the Church is representative, and the right of God&#8217;s people to elect their officers is inalienable. Therefore no man can be placed over a church in any office without the election, or at least the consent of that church.</li>
<li class="no-indent">Upon those whom God calls to bear office in His Church He bestows suitable gifts for the discharge of their various duties. And it is indispensable that, besides possessing the necessary gifts and abilities, natural and acquired, every one admitted to an office should be sound in the faith, and his life be according to godliness. Wherefore every candidate for office is to be approved by the court by which he is to be ordained.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-19-the-doctrine-of-ordination" title="19. The Doctrine of Ordination">
<header>
<h1 class="chapter-title">19. The Doctrine of Ordination</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch19">
<li class="no-indent"><a id="19"></a>Those who have been called to office in the Church are to be inducted by the ordination of a court.</li>
<li class="no-indent">Ordination is the authoritative admission of one duly called to an office in the Church of God, accompanied with fasting, prayer, and the laying on of hands, to which it is proper to add the giving of the right hand of fellowship.</li>
<li class="no-indent">As every ecclesiastical office, according to the Scriptures, is a special charge, no man shall be ordained unless it be to the performance of a definite work. In other words, a man cannot be ordained without a call.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-20-candidates-for-the-gospel-ministry" title="20. Candidates for the Gospel Ministry">
<header>
<h1 class="chapter-title">20. Candidates for the Gospel Ministry</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch20">
<li class="no-indent"><a id="20"></a>A candidate for the ministry is a member of the Church in full communion who, believing himself to be called to preach the Gospel, submits himself to the care and guidance of the Presbytery in his course of study and of practical training to prepare himself for this office.</li>
<li class="no-indent"><a id="20.2"></a>It is recommended that every candidate for the ministry should put himself under the care of a Presbytery, which should ordinarily be the Presbytery that has jurisdiction of the church of which he is a member. He should be encouraged by the Session to do this; and upon his request, the Session should furnish him with a certificate of his membership, and with testimonials of its judgment regarding his Christian character and promise of usefulness in the ministry, to be laid before the Presbytery. Every applicant for care shall be a member of the congregation whose session provides an endorsement for at least six months before filing his application, except in those cases deemed extraordinary by the Presbytery.</li>
<li class="no-indent">In making application to be taken under the care of the Presbytery, the candidate for the ministry, in addition to presenting testimonials from his church Session, shall be examined by the Presbytery in person on his Christian experience and on his motives for seeking the ministry.
<p class="no-indent">If the testimonials and the examination prove satisfactory, the Presbytery shall receive him under its care after the following manner:</p>
<p class="no-indent">The Moderator shall propose to the candidate these questions:</p>
<ol type="a">
<li>
<p class="no-indent">Do you promise in reliance upon the grace of God to maintain a becoming Christian character, and to be diligent and faithful in making full preparation for the sacred ministry?</p>
</li>
<li>
<p class="no-indent">Do you promise to submit yourself to the proper supervision of the Presbytery in matters that concern your preparation for the ministry?</p>
</li>
</ol>
<p class="no-indent">If these questions be answered in the affirmative, the Moderator, or some one appointed by him, shall give the candidate a brief charge; and the proceedings shall close with prayer. The name of the candidate is then to be recorded on the Presbytery’s Roll of Candidates for the Ministry.</p>
</li>
<li class="no-indent">The candidate continues to be a private member of the church and subject to the jurisdiction of the Session, but as respects his preparatory training for the ministry, he is under the oversight of the Presbytery. It shall be the duty of the Presbytery to show a kindly and sympathetic interest in him, and to give him counsel and guidance in regard to his studies, his practical training, and the institutions of learning he should attend. In no case may a candidate omit from his course of study any of the subjects prescribed in the Form of Government as tests for licensure and ordination without obtaining the consent of Presbytery; and where such consent is given the Presbytery shall record the fact and the reasons therefor.</li>
<li class="no-indent">For the development of his Christian character, for the service he can render, and for his more effective training, the candidate, when entering on his theological studies, should be authorized and encouraged by the Presbytery to conduct public worship, to expound the Scriptures to the people, and to engage in other forms of Christian work. These forms of service should be rendered under the direction of Presbytery, and also with the sanction and under the guidance of the candidate’s instructors during the time of his being under their instruction. A candidate should not undertake to serve statedly a church which is without a pastor unless he has the approval of the Presbytery having jurisdiction of the church.</li>
<li class="no-indent">The Presbytery shall require every candidate for the ministry under its care to make a report to it at least once a year; and it shall secure from his instructors an annual report upon his deportment, diligence, and progress in study.</li>
<li class="no-indent">The Presbytery may, upon application of the candidate, give him a certificate of dismissal to another Presbytery; and a candidate may, at his request, be allowed to withdraw from the care of the Presbytery. The Presbytery may also, for sufficient reasons, remove the name of a candidate from its roll of candidates; but in such case it shall report its action and the reasons therefor to the candidate and to the Session of his church.</li>
<li class="no-indent">An applicant coming as a candidate from another denomination must present testimonials of his standing in that body and must become a member of a congregation in Evangel Presbytery. He shall then fulfill the requirements of applicants listed under BCO <a href="#20.2">20.2</a>, as well as requirements placed upon those desiring to be licensed or to become an intern as set forth in BCO <a href="#21">21</a>.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-21-the-licensure-of-candidates-for-the-gospel-ministry" title="21. The Licensure of Candidates for the Gospel Ministry">
<header>
<h1 class="chapter-title">21. The Licensure of Candidates for the Gospel Ministry</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch21">
<li class="no-indent"><a id="21"></a><a id="21.1"></a>To preserve the purity of the preaching of the Gospel, no man is permitted to preach in the pulpits of Evangel Presbytery on a regular basis without proper licensure from the Presbytery having jurisdiction where he will preach. This license shall immediately become void if the Presbytery administers against him a censure of suspension from office or the sacraments, or deposition from office, or of excommunication. A ruling elder, a candidate for the ministry, a minister from some other denomination, or some other man may be licensed for the purpose of regularly providing the preaching of the Word upon his giving satisfaction to the Presbytery of his gifts and passing the licensure examination. (See also BCO <a href="#24.5">24.5</a> and BCO <a href="#24.6">24.6</a>.)</li>
<li class="no-indent"><a id="21.2"></a>The examination for licensure shall be as follows:
<ol type="a">
<li class="no-indent">The candidate shall give a statement of his Christian experience and inward call to preach the Gospel in written form and/or orally before the Presbytery (at the discretion of the Presbytery).</li>
<li class="no-indent">The candidate shall be tested with a written and/or oral examination by the Presbytery (at the discretion of the Presbytery) for his:
<ol type="i">
<li class="no-indent">basic knowledge of biblical doctrine as outlined in the Confession of Faith and Larger and Shorter Catechisms.</li>
<li class="no-indent">practical knowledge of Bible content.</li>
<li class="no-indent">basic knowledge of the government of the church as defined in the Book of Church Order.</li>
</ol>
</li>
<li class="no-indent">The candidate shall be examined orally before Presbytery for his views in the areas outlined in part b above.</li>
<li class="no-indent">The candidate shall provide his written sermon on an assigned passage of Scripture embodying both explanation and application, and present orally his sermon or exhortation before Presbytery or before a committee of Presbytery.</li>
<li class="no-indent">While our Constitution does not require the applicant’s affirmation of every statement and/or proposition of doctrine in our Confession of Faith and Catechisms, it is the right and responsibility of the Presbytery to determine if the applicant is out of accord with any of the fundamentals of these doctrinal standards and, as a consequence, may not be able in good faith sincerely to receive and adopt the Confession of Faith and Catechisms of this church as the system of doctrine taught in the Holy Scriptures.</li>
<li class="no-indent">Therefore, in examining an applicant for licensure, the Presbytery shall inquire not only into the candidate’s knowledge and views in the areas specified above, but also shall require the candidate to state the specific instances in which he may differ with the Confession of Faith and Catechisms in any of their statements and/or propositions. The court may grant an exception to any difference of doctrine only if in the court’s judgment the applicant’s declared difference is not out of accord with any fundamental of our system of doctrine because the difference is neither hostile to the system nor strikes at the vitals of religion.</li>
</ol>
<p class="no-indent">No Presbytery shall omit any of these parts of examination except in extraordinary cases; and whenever a Presbytery shall omit any of these parts, it shall always make a record of the reasons therefor, and of the trial parts omitted.</p>
</li>
<li class="no-indent">If the Presbytery be satisfied with the trials of the applicant, it shall then proceed to license him in the following manner. The moderator shall propose to him the following questions:
<ol type="a">
<li class="no-indent">Do you believe the Scriptures of the Old and New Testaments, as originally given, to be the infallible Word of God, which is the only infallible rule of faith and practice?</li>
<li class="no-indent">Do you sincerely receive and adopt the Confession of Faith and the Catechisms of this Church as the system of doctrine taught in the Holy Scripture?</li>
<li class="no-indent">Do you promise to strive for the purity, peace, unity and edification of the Church?</li>
<li class="no-indent">Do you promise to submit yourself, in the Lord, to the government of this Presbytery?</li>
</ol>
</li>
<li class="no-indent">The applicant having answered these questions in the affirmative, the moderator shall offer a prayer suitable for the occasion, and shall address the applicant as follows:<br />
<blockquote>
<p>In the name of the Lord Jesus Christ, and by that authority which He has given to the Church for its edification, we do license you to preach the Gospel in this Presbytery wherever God in His providence may call you; and for this purpose may the blessing of God rest upon you, and the Spirit of Christ fill your heart. Amen.</p>
</blockquote>
<p class="no-indent">Record shall be made of the licensure in the following or like form:</p>
<blockquote>
<p>At_____________, the __________day of_______________, the ____________________Presbytery, having received testimonials commending _________________________, proceeded to submit him to the prescribed examination for licensure, which was met to the approval of the Presbytery. Having satisfactorily answered the questions for licensure, _____________________ was licensed by the Presbytery to preach the Gospel within the bounds of this Presbytery.</p>
</blockquote>
</li>
<li class="no-indent">The license to preach the Gospel shall expire at the end of four years. The Presbytery may, if it thinks proper, renew it without further examination. The licentiate must apply for renewal prior to expiration. If the license expires, the stated clerk shall report the expiration to the Presbytery and to the individual’s Session, and such action shall be recorded in the minutes. The procedures of BCO <a href="#21.2">21.2</a> must be followed for re-licensure and such fact shall be recorded in the minutes. The license may be terminated at any time by a simple majority vote of the Presbytery. The Presbytery shall always record its reasons for this action in its minutes.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-22-the-election-of-pastors" title="22. The Election of Pastors">
<header>
<h1 class="chapter-title">22. The Election of Pastors</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch22">
<li class="no-indent"><a id="22"></a><a id="22.1"></a>Before a candidate, or licentiate, can be ordained to the office of the ministry, he must receive a call to a definite work. Ordinarily the call must come from a church or the Presbytery. If the call comes from another source, the Presbytery shall always make a record of the reasons why it considers the work to be a valid Christian ministry.
<p class="no-indent">A proper call must be written and in the hands of the Presbytery prior to being acted upon by the Presbytery. It must include financial arrangements (such as salary, vacation, insurance, retirement, etc.) between those calling and the one called, and assurance that the definite work will afford the liberty to proclaim and practice fully and freely the whole counsel of God, as set forth in the Scriptures and understood in the Westminster Confession of Faith.</p>
</li>
<li class="no-indent">Every church should be under the pastoral oversight of a minister, and when a church has no Senior Pastor it should seek to secure one without delay.
<p class="no-indent">A church shall proceed to elect a senior pastor in the following manner: The Session shall appoint a pulpit committee which may be composed of male members from the congregation at large or the Session, or a mixture of Session members and male members at large. The pulpit committee shall, after consultation and deliberation, recommend to the session a pastoral candidate who, in its judgment, fulfills the Constitutional requirements of that office and is most suited to be profitable to the spiritual interests of the congregation.&nbsp;The Session, once it receives the candidate recommended by the pulpit committee, shall order a congregational meeting to convene to vote on the presented candidate.</p>
<p>The Session shall order a congregational meeting to convene to vote on the presented candidate according to the rules and procedures set forth in BCO <a href="#27">27</a>.</p>
</li>
<li class="no-indent">When a congregation is convened for the election of a pastor it is important that they should elect a minister or ruling elder of Evangel Presbytery to preside, but if this be not feasible, they may elect any male member of that church.</li>
<li class="no-indent">Method of voting: The voters being convened, and prayer for divine guidance having been offered, the moderator shall put the question:<br />
<blockquote>
<p>“Are you ready to proceed to the election of a pastor?”</p>
</blockquote>
<p>If they declare themselves ready, the moderator shall call for nominations, or the election may proceed by ballot without nominations. In every case a majority of all the votes cast shall be required to elect.</p>
</li>
<li class="no-indent">On the election of a pastor, if it appears that a large minority of the voters are averse to the candidate who has received a majority of votes, and cannot be induced to concur in the call, the moderator shall endeavor to dissuade the majority from prosecuting it further; but if the electors be nearly or quite unanimous, or if the majority shall insist upon their right to call a pastor, the moderator shall proceed to draft a call in due form, and to have it subscribed by them, certifying at the same time in writing the number of those who do not concur in the call, and any facts of importance, all of which proceedings shall be laid before the Presbytery, together with the call.</li>
<li class="no-indent"><a id="22.6"></a>Form of call: The terms of the call shall be approved by the congregation in the following or like form:<br />
<blockquote>
<p class="no-indent">The ____________________ Church being on sufficient grounds well satisfied of the ministerial qualifications of you, ____________, and having good hopes from our knowledge of your labors that your ministrations in the Gospel will be profitable to our spiritual interests, do earnestly call you to undertake the pastoral office in said congregation, promising you, in the discharge of your duty, all proper support, encouragement and obedience in the Lord. That you may be free from worldly cares and avocations, we hereby promise and oblige ourselves to pay you the sum of $___________ a year in regular payments, and other benefits, such as, housing allowance, retirement, insurance, vacations, moving expenses etc., during the time of your being and continuing the regular pastor of this church.</p>
<p class="no-indent">In testimony whereof we have respectively subscribed our names this ___________day of____________________, A.D.________.</p>
<p class="no-indent">Attest: I, having moderated the congregational meeting which extended a call to ______________ for his ministerial services, do certify that the call has been made in all respects according to the rules laid down in the Book of Church Order, and that the persons who signed the foregoing call were authorized to do so by vote of the congregation.</p>
<p class="no-indent">_________________________________<br />
Moderator of the Meeting</p>
</blockquote>
</li>
<li class="no-indent">If any church shall choose to designate its ruling elders and deacons, or a committee to sign its call, it shall be at liberty to do so. But it shall, in such case, be fully certified to the Presbytery by the minister or other person who presided, that the persons signing have been appointed for that purpose by a public vote of the church, and that the call has been in all other respects prepared as above directed.</li>
<li class="no-indent">Prosecution of call: One or more commissioners shall be appointed by the church to present and prosecute the call before their Presbytery.</li>
<li class="no-indent">A congregation desiring to call a pastor from his charge, shall, by its commissioners to the Presbytery, prosecute the call before its Presbytery. The Presbytery, having heard all the parties, may, upon viewing the whole case, either recommend them to desist from prosecuting the call; or may order it to be delivered to the minister to whom it is addressed, with or without advice; or may decline to place the call in his hands; as it shall appear most beneficial for the peace, unity, and edification of the Church at large. No pastor shall be transferred without his own consent; if the parties are not ready to have the matter decided at the meeting then in progress, a written citation shall be given the minister and his church to appear before the Presbytery at its next meeting, which citation shall be read from the pulpit during a regular service, at least two weeks before the intended meeting.</li>
<li class="no-indent">A candidate or licentiate found fit and called for missionary service by a missionary agency or Presbytery shall be examined by Presbytery for ordination. If approved the Presbytery shall proceed to his ordination.</li>
<li class="no-indent">A missionary who is an ordained teaching elder in another denomination found fit and called for missionary service by a missionary agency or Presbytery shall be examined by Presbytery for admission to Presbytery. If approved he shall be enrolled as a member of Presbytery.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-23-the-ordination-and-installation-of-ministers" title="23. The Ordination and Installation of Ministers">
<header>
<h1 class="chapter-title">23. The Ordination and Installation of Ministers</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch23">
<li class="no-indent"><a id="23"></a>No Minister or licentiate or candidate shall receive a call from a church but by the permission of his Presbytery. When a call has been presented to the Presbytery, if found in order and the Presbytery deem it for the good of the Church, they shall place it in the hands of the person to whom it is addressed. Ordinarily a candidate or licentiate may not be granted permission by the Presbytery to move on to the field to which he has been called, prior to his examination for licensure or ordination. Likewise an ordained minister from another denomination, ordinarily shall not move on to the field to which he has been called until examined and received by Presbytery.</li>
<li class="no-indent">When a call for the pastoral services of a licentiate has been accepted by him, the Presbytery shall take immediate steps for his ordination.</li>
<li class="no-indent">No Presbytery shall ordain any licentiate or candidate to the office of the Gospel ministry, with reference to his laboring within the bounds of another Presbytery, but shall furnish him with the necessary testimonials, and require him to repair to the Presbytery within whose bounds he expects to labor, that he may submit himself to its authority, according to the Constitution of the Church.</li>
<li class="no-indent"><a id="23.4"></a><strong>Ordination Requirements and Procedures</strong>
<ol type="a">
<li class="no-indent">A candidate applying for ordination shall be required to present at least a diploma of Bachelor of Divinity from some approved pastoral training institution or authentic testimonials of having completed a regular course of theological studies. No Presbytery shall omit any of these educational requirements except in extraordinary cases, and then only with a three-fourths (¾) approval of the Presbytery. Whenever a Presbytery shall omit any of these educational requirements, it shall always make a record of the reasons for such omission and the parts omitted. The candidate shall also present satisfactory testimonials as to the completion and approval of an internship in the practice of the ministry.</li>
<li class="no-indent">Every candidate for ordination shall ordinarily have met the requirements of the Presbytery’s approved curriculum. Ordinarily, the candidate shall have been examined in most of the following trials when he was licensed. If the Presbytery previously approved all parts of the licensure examination, it need not re-examine the candidate in those areas at this time. If there were areas of weakness, which the Presbytery noted, or if any member of the Presbytery desires to do so, the candidate may be examined on particular points again. Additionally, the candidate shall be examined on any parts required for ordination which were not covered in his examination for licensure. In all cases, he should be asked to indicate whether he has changed his previous views concerning any points in the Confession of Faith, Catechisms, and Book of Church Order.</li>
<li class="no-indent">A candidate shall undergo the following ordination trials:
<ol type="i">
<li class="no-indent">He shall be given a careful examination in the following areas:
<ol>
<li class="no-indent">his Christian experience, especially his personal character and family management (based on the qualifications set out in 1 Timothy 3:1-7, and Titus 1:6-9),</li>
<li class="no-indent">his knowledge of the biblical Greek and Hebrew languages,</li>
<li class="no-indent">Bible content,</li>
<li class="no-indent">theology,</li>
<li class="no-indent">the Sacraments,</li>
<li class="no-indent">Church history,</li>
<li class="no-indent">the principles and rules of the government and discipline of the church.
<p class="no-indent">A Presbytery may accept a seminary degree which includes study in the original languages in lieu of an examination in the original languages.</p>
</li>
</ol>
</li>
<li class="no-indent">He shall prepare a thesis on some theological topic assigned by Presbytery.</li>
<li class="no-indent">The candidate shall prepare an exegesis on an assigned portion of Scripture, requiring the use of the original language or languages.</li>
<li class="no-indent">Upon a three-fourths (¾) vote of the Presbytery, he shall further be required to preach a sermon before the Presbytery or committee thereof.</li>
</ol>
<p class="no-indent" style="padding-left: 60px">No Presbytery shall omit any of these parts of trial for ordination except in extraordinary cases, and then only with three-fourths (¾) approval of Presbytery.</p>
</li>
<li class="no-indent">Whenever a Presbytery shall omit any of these parts, it shall always make a record of the reasons for such omissions and of the trial parts omitted.</li>
<li class="no-indent"><a id="23.4.e"></a>While our Constitution does not require the candidate’s affirmation of every statement and/or proposition of doctrine in our Confession of Faith and Catechisms, it is the right and responsibility of the Presbytery to determine if the candidate is out of accord with any of the fundamentals of these doctrinal standards and, as a consequence, may not be able in good faith sincerely to receive and adopt the Confession of Faith and Catechisms of this Church as containing the system of doctrine taught in the Holy Scriptures.</li>
<li class="no-indent"><a id="23.4.f"></a>Therefore, in examining a candidate for ordination, the Presbytery shall inquire not only into the candidate’s knowledge and views in the areas specified above, but also shall require the candidate to state the specific instances in which he may differ with the Confession of Faith and Catechisms in any of their statements and/or propositions. The court may grant an exception to any difference of doctrine only if in the court’s judgment the candidate’s declared difference is not out of accord with any fundamental of our system of doctrine because the difference is neither hostile to the system nor strikes at the vitals of religion.</li>
<li class="no-indent">The Presbytery, being fully satisfied of his qualifications for the sacred office, shall appoint a day for his ordination, which ought, if practicable, to be in that church of which he is to be the pastor.</li>
<li class="no-indent">The extraordinary clauses should be limited to extraordinary circumstances of the church or proven extraordinary gifts of the man. Presbyteries should exercise diligence and care in the use of these provisions in order that they not prevent the ordination of a candidate for whom there are truly exceptional circumstances, nor ordain (nor receive from other denominations) a person who is inadequately prepared for the ministry.</li>
</ol>
</li>
<li class="no-indent">The day appointed for the ordination having come, and the Presbytery, or a commission thereof, being convened, a member of the Presbytery, previously appointed to that duty, shall preach a sermon adapted to the occasion. The same, or another member appointed to preside, shall afterwards briefly recite from the pulpit the proceedings of the Presbytery preparatory to the ordination; he shall point out the nature and importance of the ordinance, and endeavor to impress the audience with a proper sense of the solemnity of the transaction.</li>
<li class="no-indent"><strong>Questions for Ordination</strong>
<p class="no-indent">Then addressing himself to the candidate, he shall propose to him the following questions:</p>
<ol type="a">
<li class="no-indent">Do you believe the Scriptures of the Old and New Testaments, as originally given, to be the infallible Word of God, which is the only infallible rule of faith and practice?</li>
<li class="no-indent">Do you sincerely receive and adopt the Confession of Faith and the Catechisms of this Church, as the system of doctrine taught in the Holy Scriptures; and do you further promise that if at any time you find yourself out of accord with any of the fundamentals of this system of doctrine, you will on your own initiative, make known to your Presbytery the change which has taken place in your views since the assumption of this ordination vow?</li>
<li class="no-indent"><a id="23.6.c"></a>Do you approve of the government and discipline of Evangel Presbytery, as being in conformity with the general principles of biblical polity?</li>
<li class="no-indent">Do you promise subjection to your brethren in the Lord?</li>
<li class="no-indent">Have you been induced, as far as you know your own heart, to seek the office of the holy ministry from love to God and a sincere desire to promote His glory in the Gospel of His Son?</li>
<li class="no-indent">Do you promise to be zealous and faithful in maintaining the truths of the Gospel and the purity and peace and unity of the Church, whatever persecution or opposition may arise unto you on that account?</li>
<li class="no-indent">Do you engage to be faithful and diligent in the exercise of all your duties as a Christian and a Minister of the Gospel, whether personal or relational, private or public; and to endeavor by the grace of God to adorn the profession of the Gospel in your manner of life, and to walk with exemplary piety before the flock of which God shall make you overseer?</li>
<li class="no-indent">Are you now willing to take the charge of this church, agreeably to your declaration when accepting their call? And do you, relying upon God for strength, promise to discharge to it the duties of a Pastor?<span data-type="footnote" class="footnote">For an assistant pastor, the following vow shall be used: ‘Are you now willing to serve this church, agreeably to your declaration when accepting the call of the session? And do you, relying upon God for strength, promise to discharge to it the duties of an Assistant Pastor?</span></li>
</ol>
</li>
<li class="no-indent"><strong>Questions to Congregation</strong>
<p class="no-indent">The candidate having answered these questions in the affirmative, the presiding Minister shall propose to the church the following questions:</p>
<ol type="a">
<li class="no-indent">Do you, the people of this congregation, continue to profess your readiness to receive ________________, whom you have called to be your Pastor?<span data-type="footnote" class="footnote">For an assistant pastor, the following vow shall be used: ‘Do you, the people of this congregation, profess your readiness to receive ______, whom the session has called to be your assistant pastor?</span></li>
<li class="no-indent">Do you promise to receive the word of truth from his mouth with meekness and love, and to submit to him in the due exercise of discipline?</li>
<li class="no-indent">Do you promise to encourage him in his labors, and to assist his endeavors for your instruction and spiritual edification?</li>
<li class="no-indent">And do you engage to continue to him while he is your Pastor that competent worldly maintenance which you have promised, and to furnish him with whatever you may see needful for the honor of religion and for his comfort among you?</li>
</ol>
</li>
<li class="no-indent">The people having answered these questions in the affirmative, the candidate shall kneel, and the presiding Minister shall, with prayer and the laying on of the hands of the Presbytery, according to the apostolic example, solemnly set him apart to the holy office of the Gospel ministry. Prayer being ended, he shall rise from his knees; and the Minister who presides shall first, and afterwards all the members of the Presbytery in their order, take him by the right hand, saying, in words to this effect: &#8220;We give you the right hand of fellowship, to take part in this ministry with us.&#8221; The presiding Minister shall then say: &#8220;I now pronounce and declare that [Name] has been regularly elected, ordained, and installed Pastor of this congregation, agreeably to the Word of God, and according to the Constitution of Evangel Presbytery; and that as such he is entitled to all support, encouragement, honor, and obedience in the Lord: In the name of the Father, and of the Son, and of the Holy Spirit. Amen.&#8221; After which the Minister presiding, or some other Minister or Ruling Elder appointed for the purpose, shall give a solemn charge to the Pastor and to the congregation, to persevere in the discharge of their reciprocal duties, and then after prayer and the singing of a psalm, or hymn, the congregation shall be dismissed with the benediction. And the Presbytery shall duly record its proceedings.<span data-type="footnote" class="footnote">For assistant pastor, add the word "assistant" before “pastor."</span></li>
<li class="no-indent">After the installation, the heads of families of the congregation then present, or at least the Ruling Elders and Deacons, should come forward to their Pastor, and give him their right hand and the holy kiss of Christian fellowship, in token of cordial reception and affectionate regard.</li>
<li class="no-indent"><a id="23.10"></a><strong>Questions for Installation</strong>
<p class="no-indent">In the installation of an ordained Minister, the following questions are to be substituted for those addressed to a candidate for ordination, namely:</p>
<ol type="a">
<li class="no-indent">Are you now willing to take charge of this congregation as their Pastor, agreeably to your declaration in accepting its call?<span data-type="footnote" class="footnote">For an assistant pastor, the following vow shall be used: ‘Are you now willing to serve this congregation as their Assistant Pastor, agreeably to your declaration in accepting the call of its session?’</span></li>
<li class="no-indent">Do you conscientiously believe and declare, as far as you know your own heart, that, in taking upon you this charge, you are influenced by a sincere desire to promote the glory of God and the good of the Church?</li>
<li class="no-indent">Do you solemnly promise that, by the assistance of the grace of God, you will endeavor faithfully to discharge all the duties of a Pastor to this congregation, and will be careful to maintain a deportment in all respects becoming a Minister of the Gospel of Christ, agreeably to your ordination engagements?<span data-type="footnote" class="footnote">For assistant pastor, add the word ‘assistant’ before ‘pastor.</span></li>
</ol>
</li>
<li class="no-indent"><strong>Questions to the Congregation</strong>
<p class="no-indent">The candidate having answered these questions in the affirmative, the presiding minister shall propose to the church the following questions:</p>
<ol type="a">
<li class="no-indent">Do you, the people of this congregation, continue to profess your readiness to receive______, whom you have called to be your pastor?<span data-type="footnote" class="footnote">For an assistant pastor, the following vow shall be used: ‘Do you, the people of this congregation, profess your readiness to receive ______, whom the session has called to be your assistant pastor?</span></li>
<li class="no-indent">Do you promise to receive the word of truth from his mouth with meekness and love, and to submit to him in the due exercise of discipline?</li>
<li class="no-indent">Do you promise to encourage him in his labors, and to assist his endeavors for your instruction and spiritual edification?</li>
<li class="no-indent">Do you engage to continue to him while he is your pastor that competent worldly maintenance which you have promised, and to furnish him with whatever you may see needful for the honor of religion and for his comfort among you?</li>
</ol>
</li>
<li class="no-indent">In the ordination of candidates or licentiates as Evangelists the same questions are to be propounded as in the ordination of Pastors, with the exception of the eighth, for which the following shall be substituted:<br />
<blockquote>
<p>&#8220;Do you now undertake the work of an Evangelist, and do you promise, in reliance on God for strength, to be faithful in the discharge of all the duties incumbent on you as a Minister of the Gospel of the Lord Jesus Christ?&#8221;</p>
</blockquote>
</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-24-the-pastoral-relations" title="24. The Pastoral Relations">
<header>
<h1 class="chapter-title">24. The Pastoral Relations</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch24">
<li class="no-indent"><a id="24"></a>The various pastoral relations are pastor, associate pastor, and assistant pastor.</li>
<li class="no-indent">The pastor and associate pastor are elected by the congregation using the form of call in BCO <a href="#22.6">22.6</a>. Being elected by the congregation, they become members of the Session.</li>
<li class="no-indent"><a id="24.3"></a>An assistant pastor is called by the Session, by the permission and approval of Presbytery, under the provisions of BCO <a href="#22.1">22.1</a> and BCO <a href="#15.2">15.2</a>, with Presbytery membership being governed by the same provisions that apply to pastors. He is not a member of the Session, but may be appointed on special occasions to moderate the Session under the provisions of BCO <a href="#14.4">14.4</a>. A man may serve as an assistant pastor for a term not to exceed two years after which his term may be renewed by the session to continue as an assistant pastor or the congregation may vote to call him as an associate pastor.</li>
<li class="no-indent">The relationship of the associate pastor to the church is determined by the congregation. The relationship of the assistant pastor to the church is determined by the Session. The dissolution of an associate pastor is governed by the provisions of BCO <a href="#25">25</a>. The dissolution of the relationship of an assistant pastor is governed by the provisions of BCO <a href="#24.3">24.3</a> and BCO <a href="#25">25</a>.</li>
<li class="no-indent"><a id="24.5"></a>In order to provide necessary changes in pastorates, a temporary relation may be established between a church and a minister called Stated Supply. If a church is unable to secure a regular pastor or a Stated Supply, then the Session with approval of Presbytery may establish a temporary relation between the church and a licentiate called Student Supply or Ruling Elder Supply.</li>
<li class="no-indent"><a id="24.6"></a>Such temporary relationships can take place at the invitation of the church Session to the minister of the Word, the licentiate, or the ruling elder. The length of the relationship will be determined by the Session and the minister, the licentiate, or the ruling elder, with the approval of the Presbytery. Stated supply, student supply, or ruling elder supply relationships will be for no longer than one year, renewable at the request of the Session and at the review of the Presbytery. (See also BCO <a href="#21.1">21.1</a>).</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-25-the-dissolution-of-the-pastoral-relation" title="25. The Dissolution of the Pastoral Relation">
<header>
<h1 class="chapter-title">25. The Dissolution of the Pastoral Relation</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch25">
<li class="no-indent"><a id="25"></a>When any Minister shall tender the resignation of his pastoral charge to his Presbytery, the Presbytery shall cite the church to appear by its commissioners, or the church may so appear upon its own motion, to show cause, if it has any, why the Presbytery should not accept the resignation. If the church fail to appear, or if its reasons for retaining its Pastor be deemed insufficient, his resignation shall be accepted, and the pastoral relation dissolved. If any church desires to be relieved of its Pastor, a similar procedure shall be observed. But whether the Minister or the church initiate proceedings for a dissolution of the relation, there shall always be a meeting of the congregation called and conducted precisely in the same manner as when the call of a Pastor is to be made out. The pastoral relation of the assistant pastor may be dissolved by the Session; the presbytery shall be informed of their action.
<p>Upon dissolution of the pastoral relationship of the senior pastor, the Presbytery must determine if the dissolution of the pastoral relationship of the senior pastor was brought about in Christian love and good order on the part of the parties concerned. The Presbytery must review the call of any new senior pastor and the continuation of existing pastoral relationships, which calls are subject to the Presbytery’s approval by majority vote.</p>
</li>
<li class="no-indent">The Presbytery may designate a minister as honorably retired when the minister by reason of age wishes to be retired, or as medically disabled when by reason of infirmity is no longer able to serve the church in the active ministry of the Gospel. A minister medically disabled or honorably retired shall continue to hold membership in his Presbytery. He may serve on committees or commissions if so elected or appointed.</li>
<li class="no-indent">In order to provide necessary changes in pastorates, a temporary relation may be established between a church and a minister called Stated Supply. If a church is unable to secure a regular pastor or a Stated Supply, then the Session with approval of Presbytery may establish a temporary relation between the church and a licentiate called Student Supply or Ruling Elder Supply.</li>
<li class="no-indent">Such temporary relationships can take place at the invitation of the church Session to the minister of the Word, the licentiate, or the ruling elder. The length of the relationship will be determined by the Session and the minister, the licentiate, or the ruling elder, with the approval of the Presbytery. Stated supply, student supply, or ruling elder supply relationships will be for no longer than one year, renewable at the request of the Session and at the review of the Presbytery (cf. BCO <a href="#21.1">21.1</a>).</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-26-election-ordination-and-installation-of-ruling-elders-and-deacons" title="26. Election, Ordination, and Installation of Ruling Elders and Deacons">
<header>
<h1 class="chapter-title">26. Election, Ordination, and Installation of Ruling Elders and Deacons</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<h2><a id="26"></a>Election</h2>
<ol class="ch26">
<li class="no-indent">Every church shall elect men to the offices of ruling elder and deacon in the following manner: At such times as determined by the Session, voting members of the congregation may submit names to the Session, keeping in mind that each prospective officer should be an active male member who meets the qualifications set forth in 1 Timothy 3 and Titus 1. After the close of the nomination period those nominees for the office of ruling elder and/or deacon approved by the Session shall receive instruction in the qualifications and work of the office. Each nominee shall then be examined in:
<ol type="a">
<li class="no-indent">his Christian experience, especially his personal character and family management (based on the qualifications set out in 1 Timothy 3:1-7 and Titus 1:6-9),</li>
<li class="no-indent">his knowledge of Bible content,</li>
<li class="no-indent">his knowledge of the system of doctrine, government, discipline contained in the Constitution of Evangel Presbytery BCO <a href="#29.1">29.1</a>,</li>
<li class="no-indent">the duties of the office to which he has been nominated, and</li>
<li class="no-indent">his willingness to give assent to the questions required for ordination. BCO <a href="#26.4">26.4</a></li>
</ol>
<p>If the nominee is married, his wife shall be interviewed regarding the above criteria.</p>
<p>If there are candidates eligible for the election, the Session shall report to the congregation those eligible, giving at least thirty (30) days prior notice of the time and place of a congregational meeting for elections.</p>
<p>If one-fourth (1/4) of the persons entitled to vote shall at any time request the Session to call a congregational meeting for the purpose of electing additional officers, it shall be the duty of the Session to call such a meeting on the above procedure. The number of officers to be elected shall be determined by the congregation after hearing the Session’s recommendation.</p>
</li>
<li class="no-indent">A two-thirds majority of votes cast is required for election.</li>
<li class="no-indent">The voters being convened, the moderator shall explain the purpose of the meeting and then put the question:Are you now ready to proceed to the election of additional ruling elders (or deacons) from the slate presented?If they declare themselves ready, the election may proceed by private ballot without nomination. In every case a two-thirds majority of all the votes cast shall be required to elect.</li>
</ol>
<h2 class="no-indent">Ordination and Installation</h2>
<ol class="ch26-contd">
<li class="no-indent"><a id="26.4"></a>The day having arrived, and the Session being convened in the presence of the congregation, a sermon shall be preached after which the presiding minister shall state in a concise manner the warrant and nature of the office of ruling elder, or deacon, together with the character proper to be sustained and the duties to be fulfilled. Having done this, he shall propose to the candidate, in the presence of the church, the following questions, namely:
<ol type="a">
<li class="no-indent">Do you believe the Scriptures of the Old and New Testaments, as originally given, to be the infallible Word of God, which is the only infallible rule of faith and practice?</li>
<li class="no-indent">Do you sincerely receive and adopt the Confession of Faith and the Catechisms of this Church, as the system of doctrine taught in the Holy Scriptures; and do you further promise that if at any time you find yourself out of accord with any of the fundamentals of this system of doctrine, you will on your own initiative, make known to your Presbytery the change which has taken place in your views since the assumption of this ordination vow?</li>
<li class="no-indent">Do you approve of the government and discipline of Evangel Presbytery, as being in conformity with the general principles of biblical polity?</li>
<li class="no-indent">Do you accept the office of ruling elder (or deacon, as the case may be) in this church, and promise faithfully to perform all the duties thereof, and to endeavor by the grace of God to adorn the profession of the Gospel in your life, and to set a worthy example before the Church of which God has made you an officer?</li>
<li class="no-indent">Do you promise subjection to your brethren in the Lord?</li>
<li class="no-indent">Do you promise to strive for the purity, peace, unity and edification of the Church?</li>
</ol>
<p class="no-indent">The ruling elder or deacon elect having answered in the affirmative, the minister shall address to the members of the church the following question:</p>
<blockquote>
<p>Do you, the members of this church, acknowledge and receive this brother as a ruling elder (or deacon), and do you promise to yield him all that honor, encouragement and obedience in the Lord to which his office, according to the Word of God and the Constitution of this Church, entitles him?</p>
</blockquote>
<p class="no-indent">The members of the church having answered this question in the affirmative, the candidate shall then be set apart, with prayer by the minister or any other Session member and the laying on of the hands of the Session, to the office of ruling elder (or deacon). Prayer being ended, the members of the Session (and the deacons, if the case be that of a deacon) shall greet the newly ordained officer with a holy kiss and take him by the hand, saying in words to this effect:</p>
<blockquote>
<p>We give you the right hand of fellowship, to take part in this office with us.</p>
</blockquote>
<p class="no-indent">The minister shall then say:</p>
<blockquote>
<p>I now pronounce and declare that ____________________ has been regularly elected, ordained and installed a ruling elder (or deacon) in this church, agreeable to the Word of God, and according to the Constitution of Evangel Presbytery; and that as such he is entitled to all encouragement, honor and obedience in the Lord: In the name of the Father, and of the Son, and of the Holy Spirit. Amen.</p>
</blockquote>
<p class="no-indent">After which the minister or any other member of the Session shall give to the ruling elder (or deacon) and to the church an exhortation suited to the occasion.</p>
</li>
<li class="no-indent"><a id="26.5"></a>Ordination to the offices of ruling elder or deacon is perpetual; nor can such offices be laid aside at pleasure; nor can any person be degraded from either office but by deposition after regular trial; yet a ruling elder or deacon may have reasons which he deems valid for being released from the active duties of his office. In such a case the Session, after conference with him and careful consideration of the matter, may, if it thinks proper, accept his resignation and dissolve the official relationship which exists between him and the church.The ruling elder or deacon, though chargeable with neither heresy nor immorality, may become unacceptable in his official capacity to a majority of the church which he serves. In such a case the church may take the initiative by a majority vote at a regularly called congregational meeting, and request the Session to dissolve the official relationship between the church and the officer without censure. The Session, after conference with the ruling elder or deacon, and after careful consideration, may use its discretion as to dissolving the official relationship. In either case the Session shall report its action to the congregation. If the Session fails or refuses to report to the congregation within sixty (60) days from the date of the congregational meeting or if the Session reports to the congregation that it declined to dissolve such relationship, then any member or members in good standing may file a complaint against the Session in accordance with the provisions of BCO <a href="#46">46</a>.</li>
<li class="no-indent">When a ruling elder or deacon who has been released from his official relation is again elected to his office in the same or another church, he shall be installed after the above form with the omission of ordination.</li>
<li class="no-indent">When a ruling elder or deacon cannot or does not for a period of one year perform the duties of his office, his official relationship shall be dissolved by the Session and the action reported to the congregation.</li>
<li class="no-indent">When a deacon or ruling elder by reason of age or infirmity desires to be released from the active duties of the office, he may at his request and with the approval of the Session be designated deacon or elder emeritus. When so designated, he is no longer required to perform the regular duties of his office, but may continue to perform certain of these duties on a voluntary basis, if requested by the Session or a higher court. He may attend Diaconate or Session meetings, if he so desires, and may participate fully in the discussion of any issues, but may not vote.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-27-congregational-meetings" title="27. Congregational Meetings">
<header>
<h1 class="chapter-title">27. Congregational Meetings</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch27">
<li class="no-indent"><a id="27"></a> The congregation shall consist of both communing and non-communing members of a particular church. Voting privileges shall be limited to communing members in good standing at that particular church. Any additional voting requirements and procedures are subject to the Bylaws of the particular church which must always be in accord with the Evangel Presbytery Book of Church Order.</li>
<li class="no-indent">Whenever it may seem for the best interests of the church that a congregational meeting should be held, the Session shall call such meeting and give public notice two weeks in advance, and no business shall be transacted at such meeting except what is stated in the notice. The Session shall always call a congregational meeting when requested in writing to do so by one-fourth of the voting members of the church.
<p class="no-indent">Upon such a proper request, if the Session cannot act, fails to act or refuses to act, to call such a congregational meeting within thirty (30) days from the receipt of such a request, then any member or members in good standing may file a complaint in accordance with the provisions of BCO <a href="#46">46</a>.</p>
</li>
<li class="no-indent">A quorum of the congregational meeting shall consist of one-fourth of the voting members of the church.</li>
<li class="no-indent">The Pastor shall be the Moderator of congregational meetings by virtue of his office. If it should be not feasible or inexpedient for him to preside, or if there is no Pastor, the Session shall appoint one of their number to call the meeting to order and to preside until the congregation shall elect their presiding officer, who may be a Minister of Evangel Presbytery or any male member of that particular church.</li>
<li class="no-indent">A Clerk shall be elected by the congregation to serve at that meeting or for a definite period, whose duty shall be to keep correct minutes of the proceedings and of all business transacted and to preserve these minutes in a permanent form, after they have been attested by the Moderator and the Clerk of the meeting. He shall also send a copy of these minutes to the Session of the church.</li>
<li class="no-indent">When a particular church is incorporated, its meetings for the transaction of the business of the corporation will be provided for in its charter and bylaws, which must always be in accord with Evangel Presbytery, and must not infringe upon the powers or duties of the Session or of the Board of Deacons.</li>
<li class="no-indent">The corporation of a particular church, through its duly elected trustees or corporation officers, (or, if unincorporated, through those who are entitled to represent the particular church in matters related to real property) shall have sole title to its property, real, personal, or mixed, tangible or intangible, and shall be sole owner of any equity in any real estate, or any fund or property of any kind held by or belonging to any particular church, or any board, society, committee, Sunday school class or branch thereof. The superior courts of the Church may receive monies or properties from a local church only by free and voluntary action of the latter.</li>
<li class="no-indent">All particular churches shall be entitled to hold, own and enjoy their own local properties, without any right of reversion whatsoever to any Presbytery, General Assembly or any other courts hereafter created, trustees or other officers of such courts.</li>
<li class="no-indent">The provisions of this BCO 27 are to be construed as a solemn covenant whereby the Church as a whole promises never to attempt to secure possession of the property of any congregation against its will, whether or not such congregation remains within or chooses to withdraw from this body. All officers and courts of the Church are hereby prohibited from making any such attempt.</li>
<li class="no-indent">While a congregation consists of all the communing members of a particular church, and in matters ecclesiastical the actions of such local congregation or church shall be in conformity with the provisions of this Book of Church Order, nevertheless, in matters pertaining to the subject matters referred to in this BCO 27, including specifically the right to affiliate with or become a member of this Presbytery and the right to withdraw from or to sever any affiliation of connection with this Presbytery hereof, action may be taken by such local congregation or local church in accordance with the civil laws applicable to such local congregation or local church; and as long as such action is taken in compliance with such applicable civil laws, then such shall be the action of the local congregation or local church.
<p class="no-indent">It is expressly recognized that each local congregation or local church shall be competent to function and to take actions covering the matters set forth herein as long as such action is in compliance with the civil laws with which said local congregation or local church must comply, and this right shall never be taken from said local congregation or local church without the express consent of and affirmative action of such local church or congregation.</p>
<p class="no-indent">Particular churches need remain in association with any court of this body only so long as they themselves so desire. The relationship is voluntary, based upon mutual love and confidence, and is in no sense to be maintained by the exercise of any force or coercion whatsoever. A particular church may withdraw from any court of this body at any time for reasons which seem to it sufficient.</p>
</li>
<li class="no-indent">If a church shall be dissolved by the Presbytery, or otherwise cease to exist, and no disposition has been made of its property by those who hold the title to the property within six months after such dissolution, then those who held the title to the property at the time of such dissolution shall, if requested by the Presbytery, deliver, convey, and transfer to the Presbytery of which the church was a member, or to the authorized agents of the Presbytery, all property of the church; and the receipt and acquittance of the Presbytery, or its proper representatives, shall be a full and complete discharge of all liabilities of such persons holding the property of the church. The Presbytery receiving such property shall apply the same or the proceeds thereof at its discretion.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-28-declaration-of-doctrine-and-policies-concerning-sexuality" title="28. Declaration of Doctrine and Policies Concerning Sexuality">
<header>
<h1 class="chapter-title">28. Declaration of Doctrine and Policies Concerning Sexuality</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<p class="no-indent"><a id="28"></a><strong>Introduction.</strong> Since the mid-twentieth century, rebellion against God’s divine pattern of sex within the loving union of lifelong, monogamous, heterosexual marriage has become widespread, and those attacks are increasingly perpetrated in concert with the civil magistrate. Thus for the protection of the Christian church’s conscience and the purity of the Faith once for all delivered to the saints, it has become necessary for Christians to declare our Scriptural convictions and commitments concerning sexuality and marriage. These convictions and commitments are testified to by God’s natural revelation and they are explicitly commanded by God’s special revelation of Holy Scripture. Prior generations of Christians and non-Christians alike lived under the beneficial constraints of laws written to protect civil society from sexual relations outside these commands of Scripture. Western law reinforced God’s law concerning sexual relations and His Order of Creation of Adam first, then Eve. For this reason, the church had no need to adopt doctrinal creeds or statements concerning sexuality. Now though, with the heathens’ attack growing ever more intense and becoming institutionalized by the power of civil authority, the time has come for the church to declare her allegiance to God’s law of male and female, and to do so specifically, forthrightly, and with confidence in the wisdom and kindness of God. He is the One who made us. We did not make ourselves. He is the One who created us male and female, pronouncing His creation “very good” only after He had made man and woman.</p>
<ol class="ch28">
<li class="no-indent">“In the day when God created man, He made him in the likeness of God. God created them male and female, and He blessed them and named them Man in the day when they were created.”<span data-type="footnote" class="footnote">Genesis 5:2. Unless otherwise indicated, all Scripture references are to the New American Standard Bible (1995).</span> God formed the first male, Adam, from the dust of the ground. He made the first female, Eve, from Adam’s rib<span data-type="footnote" class="footnote">“However, in the Lord, neither is woman independent of man, nor is man independent of woman. For as the woman originates from the man, so also the man <em>has his birth</em> through the woman; and all things originate from God.” 1 Corinthians 11:11–12.</span> and presented her to Adam to be his helpmeet. Adam called his wife “Woman, because she was taken out of Man.”<span data-type="footnote" class="footnote">Genesis 2:23.</span> God named the race adam after the first man Adam.<span data-type="footnote" class="footnote">See Hebrew word translated as “man” in Genesis 1:27, and throughout the Old Testament.</span></li>
<li class="no-indent">From the beginning, God gave Adam authority over Eve and responsibility for her. This authority and responsibility are inseparably joined together. Eve was created to be a “help meet” for Adam,<span data-type="footnote" class="footnote">Genesis 2:18 (KJV).</span> that is, a help fitting for Adam. God’s decree of father-rule is the necessary outworking of the authority over Eve and responsibility for her that He placed on Adam. Man is to love and take responsibility for woman by leading her and laying down his life for her, providing a living illustration of Christ’s sacrificial leadership of His Bride, the Church. This estate of male responsibility and authority is not a consequence of the Fall, but was ordained by God in the beginning: “But I do not allow a woman to teach or exercise authority over a man, but to remain quiet. For it was Adam who was first created, and then Eve. And it was not Adam who was deceived, but the woman being deceived, fell into transgression.”<span data-type="footnote" class="footnote">1 Timothy 2:12–14.</span> God’s subordination of the woman to man in no way diminishes the woman’s perfect equality with man in essence, worth, and honor.</li>
<li class="no-indent">God’s bifurcation of mankind into two and only two sexes, male and female, is an act of His creative will and power and continues through the generations since Adam, our first father.</li>
<li class="no-indent">God forms each person in his mother’s womb and creates the unborn child male or female.<span data-type="footnote" class="footnote">See Psalm 139:13–16; Genesis 5:2.</span> From the moment of conception,<span data-type="footnote" class="footnote">Because all truth is God’s truth and God is not a man that He should lie, what God reveals through His Creation never contradicts what He reveals in His Word. Thus, genetics and other scientific disciplines, when not abused or corrupted for sinful purposes, can declare truth. It is proper then to recognize that a man conceived and born a man is genetically male, and a woman conceived and born a woman is genetically female.</span> males are distinct from females, and females are distinct from males.<span data-type="footnote" class="footnote">This is not to address the extremely rare case of intersex children born with a variety of conditions, including: Not XX and Not XY, Hypospadias, Androgen Insensitivity Syndrome, Ovotestes, etc. “Intersex” is a medical diagnosis of atypical male or female anatomies not to be confused with those born with typical male or female anatomies who claim a “transgender” or “transsexual” identity. The suffering of those born with physical anomalies must not be used to justify the rebellion of those who repudiate the sex God made them. All such abnormalities and genetic deformities (e.g., deafness, blindness, etc.) along with illness of any kind, pain, suffering, and death itself, are a result of the Fall as described in Genesis 3, and pass through God’s sovereign hand as He gives to each man both good and adversity. Exodus 4:11; Job 2:9–10.</span></li>
<li class="no-indent">What God has decreed as each one’s sex at the moment of conception, either male or female, is His gift and must be received with gratitude, each man living out his manhood and each woman her womanhood, in humble reliance upon God’s grace.</li>
<li class="no-indent">God’s created order of man and woman was established while man was in a state of perfection before the Fall. God’s creation of Adam first, then Eve, is the origin of Scripture’s condemnation of woman exercising authority over man and is further delineated by Scripture’s declaration that man is the glory of God, but woman is the glory of man.<span data-type="footnote" class="footnote">“For a man ought not to have his head covered, since he is the image and glory of God; but the woman is the glory of man. For man does not originate from woman, but woman from man; for indeed man was not created for the woman’s sake, but woman for the man’s sake.” 1 Corinthians 11:7–9.</span> This order of creation, then, is a universal truth for all mankind.</li>
<li class="no-indent"><a id="28.7"></a>The proper conception of “sexual identity” is a matter of being and obeying the genetic sex God made us, either male or female. Genetic sex and sexual identity cannot be separated, and they remain bound together throughout one’s life. Sexuality does not admit of gradations. You are either male or female, not part male and part female. Nor are there a great multitude of sexual identities. There are only two, male and female. Any attempt of a man to play the woman or a woman to play the man violates God’s decree, attacks His created order, and constitutes sin so serious that God Himself pronounces it an “abomination.”<span data-type="footnote" class="footnote">Deuteronomy 22:5. See also 1 Corinthians 6:9–10.</span></li>
<li class="no-indent">This sin includes transvestitism and any efforts, including chemical or surgical, as well as behavioral (e.g., effeminacy), to reject and efface one’s sex and to adopt characteristics of the opposite sex.</li>
<li class="no-indent">This sin also includes the conscription of woman as a military combatant or the placing of woman in harm’s way as a law enforcement officer. Following the example of Christ Jesus who gave up His life for His Bride, the Church, man is to lay down his life in defense of woman.<span data-type="footnote" class="footnote">See Ephesians 5:25.</span> As life-giver,<span data-type="footnote" class="footnote">See Genesis 3:20.</span> woman has always been honored by man’s defense of her and her children. A civil magistrate defaces woman’s sexuality by placing her in the uniform of a combatant<span data-type="footnote" class="footnote">See Deuteronomy 22:5. In the text, “that which pertaineth to a man” (KJV) refers to the clothing and weapons worn by men for combat.</span> and commanding her to take up arms. Further, given woman’s comparative physical weakness in the face of male enemies, such magistrates place their homeland at unnecessary risk. Finally, female military combatants of childbearing age often (whether known or unknown) place at risk unborn children, which is an act contrary to the just war principle of avoiding needless loss of life. Therefore, Evangel Presbytery condemns the use of women as military combatants, the conscription of women into the armed forces, and any requirement for her to register for conscription into military service.<span data-type="footnote" class="footnote">See Constitution and Bylaws of Trinity Presbyterian Church (PCA) (Spartanburg, SC), art. XIII (“Selective Service”) (updated May 28, 2017). See also “Man’s Duty to Protect Woman,” Majority Report of the Presbyterian Church in America’s General Assembly Ad Interim Study Committee on Women in the Military, 2001, <a href="https://www.pcahistory.org/pca/digest/studies/01-278.html">https://www.pcahistory­.org­/pca­/digest­/studies­/01­-278­.html</a>.</span></li>
<li class="no-indent">All the sins mentioned above are violations of the separate nature and callings of Adam and Eve, man and woman. Through repentance and faith in Jesus Christ, there is full forgiveness for each of these sins.</li>
<li class="no-indent">It is a particularly necessary and vital ministry of the church today to proclaim this forgiveness and to teach and help those who repent of these sins to live faithfully as the man or woman God made them.</li>
<li class="no-indent">As the household of faith, the church is privileged to assist parents in training boys to be men and girls to be women. This training is not simply Christian discipleship but is also part of the Church’s proclamation of the Gospel for the salvation of mankind.</li>
<li class="no-indent">Being committed to such evangelism and discipleship, Evangel Presbytery limits participation in any program or activity that is limited to men (e.g., a men’s Bible study or a men’s retreat) exclusively to males.</li>
<li class="no-indent">Participation in any program or activity of Evangel Presbytery that is limited to women (e.g., a women’s Bible study or a women’s retreat) is exclusively limited to females.</li>
<li class="no-indent">Access to facilities of Evangel Presbytery that are designated for use by men (e.g., a men’s restroom) is exclusively limited to males.</li>
<li class="no-indent">Access to facilities of Evangel Presbytery that are designated for use by women (e.g., a women’s restroom or nursing/cry room, etc.) is exclusively limited to females.</li>
<li class="no-indent">Recognizing the church’s own sins and failures in obeying God’s commands of sexuality and recognizing that sinners on the road of repentance and faith in Jesus Christ often enter the church bound in deep patterns of sexual sin, it is not our expectation that sinners will respond to the preaching of the Law and the proclamation of the Gospel with immediate and full repentance. For this reason, wise and compassionate pastoral discretion is necessary to apply the rules set forth in this Declaration, especially concerning access to facilities. In certain instances the higher law of love will preclude swift and rigid enforcement of rules. For example, if a female has transitioned to a male in appearance, it may be best that she not use the bathroom of her birth sex until she has been presented with pastoral counsel concerning God’s calling of manhood and womanhood and she begins to learn of Jesus’ Lordship over her sexuality and the implications it has for her sexual identity and its public expression. In this case, the female would be asked not to use the men’s restroom, but instead a single-stall restroom available to either sex.</li>
<li class="no-indent">Marriage is instituted by God as the union of one male and one female,<span data-type="footnote" class="footnote">“FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER, AND THE TWO SHALL BECOME ONE FLESH; so they are no longer two, but one flesh. What therefore God has joined together, let no man separate.” Mark 10:7–9.“Or do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived; neither fornicators, nor idolaters, nor adulterers, nor effeminate, nor homosexuals, nor thieves, nor the covetous, nor drunkards, nor revilers, nor swindlers, will inherit the kingdom of God.” 1 Corinthians 6:9–10.</span> which union is intended to be monogamous<span data-type="footnote" class="footnote">“You shall not commit adultery.” Exodus 20:14.</span> and lifelong.<span data-type="footnote" class="footnote">“So then, if while her husband is living she is joined to another man, she shall be called an adulteress; but if her husband dies, she is free from the law, so that she is not an adulteress though she is joined to another man.” Romans 7:3.</span> This relationship, with these limitations, was established while man was in a state of perfection before the Fall<span data-type="footnote" class="footnote">See Genesis 2:18–24.</span> and is established for all members of the human race. Marriage is an honorable estate that God Himself made, and it symbolizes to us the mystical union which is between Christ and His Church.<span data-type="footnote" class="footnote">“Husbands, love your wives, just as Christ also loved the church and gave Himself up for her, so that He might sanctify her, having cleansed her by the washing of water with the word, that He might present to Himself the church in all her glory, having no spot or wrinkle or any such thing; but that she would be holy and blameless. So husbands ought also to love their own wives as their own bodies. He who loves his own wife loves himself; for no one ever hated his own flesh, but nourishes and cherishes it, just as Christ also does the church, because we are members of His body. FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER AND SHALL BE JOINED TO HIS WIFE, AND THE TWO SHALL BECOME ONE FLESH. This mystery is great; but I am speaking with reference to Christ and the church.” Ephesians 5:25–32.</span> For centuries, Christians have recognized the following vital purposes of marriage: “Marriage was ordained for the mutual help of husband and wife, for the increase of mankind with a legitimate issue, and of the Church with an holy seed; and for preventing of uncleanness.”<span data-type="footnote" class="footnote">Westminster Confession of Faith, ch. 24 (“Of Marriage and Divorce”), para. 2. Westminster Confession of Faith hereinafter abbreviated as “WCF.”</span> This holy estate Christ made beautiful by His presence and first miracle at a wedding in Cana of Galilee.<span data-type="footnote" class="footnote">See John 2:1–11.</span></li>
<li class="no-indent">When sin entered the race, marriage was sorely affected.<span data-type="footnote" class="footnote">“When the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was desirable to make <em>one</em> wise, she took from its fruit and ate; and she gave also to her husband with her, and he ate. Then the eyes of both of them were opened, and they knew that they were naked; and they sewed fig leaves together and made themselves loin coverings. They heard the sound of the LORD God walking in the garden in the cool of the day, and the man and his wife hid themselves from the presence of the LORD God among the trees of the garden. Then the LORD God called to the man, and said to him, ‘Where are you?’ He said, ‘I heard the sound of You in the garden, and I was afraid because I was naked; so I hid myself.’ And He said, ‘Who told you that you were naked? Have you eaten from the tree of which I commanded you not to eat?’” Genesis 3:6–11.</span> God therefore created laws to govern the violation of His established pattern, while not changing the pattern.<span data-type="footnote" class="footnote">“He said to them, ‘Because of your hardness of heart Moses permitted you to divorce your wives; but from the beginning it has not been this way.’” Matthew 19:8.“For truly I say to you, until heaven and earth pass away, not the smallest letter or stroke shall pass from the Law until all is accomplished.” Matthew 5:18.</span> Since marriage is a lifelong and monogamous union, God forbids divorce except in two circumstances: (1) when one spouse abandons the other,<span data-type="footnote" class="footnote">Abandonment or “wilful desertion” (WCF 24.6) is not limited only to cases of one spouse’s unjustified departure and refusal to be reconciled to the abandoned or injured spouse. A state of willful desertion also exists if the offending party’s conduct is so egregious that the injured party is forced to leave the marital home and reconciliation is impossible due to the nature or seriousness of the sin and the offending party’s persistent impenitence. As in any other case involving the Scriptural permissibility of divorce, the board of elders will judge whether the offending party’s sin justifies the injured party in separating and seeking dissolution of the marital bond. Two resources we commend in considering cases of divorce are: “Marriage, Singleness, Divorce, and Remarriage,” statement adopted by the session of Trinity Reformed Church of Bloomington, Indiana, June 2, 1999, available at <a href="https://evangelpresbytery.com/wp-content/uploads/2019/10/Divorce-Policy-FINAL-2000.pdf" target="_blank" rel="noopener noreferrer">https://evangelpresbytery.com/divorce-policy-final-2000/</a>; and “Divorce and Remarriage,” Report of the Ad-Interim Study Committee on Marriage and Divorce to the Twentieth General Assembly of the Presbyterian Church in America, 1992, <a href="https://pcahistory.org/pca/digest/studies/divorce-remarriage.pdf">https://pcahistory.org/pca/digest/studies/divorce-remarriage.pdf</a>.</span> and (2) when a spouse engages in sexual immorality—what Jesus referred to as the sin of <em>porneia</em>.<span data-type="footnote" class="footnote">See “Marriage, Singleness, Divorce, and Remarriage,” pp. 3–4. See also WCF 24.6.</span></li>
<li class="no-indent">More broadly, in His Law God forbids any deviation from the established pattern of marriage and from His gift of sexual union to be enjoyed by a married couple. These forbidden deviations include lust for anyone but one’s spouse, pornography,<span data-type="footnote" class="footnote">“But I say to you that everyone who looks at a woman with lust for her has already committed adultery with her in his heart.” Matthew 5:28.</span> masturbation (including simulated copulation with any inanimate object no matter how lifelike),<span data-type="footnote" class="footnote">“Finally then, brethren, we request and exhort you in the Lord Jesus, that as you received from us <em>instruction</em> as to how you ought to walk and please God (just as you actually do walk), that you excel still more. For you know what commandments we gave you by <em>the authority</em> of the Lord Jesus. For this is the will of God, your sanctification; <em>that is</em>, that you abstain from sexual immorality; that each of you know how to possess his own vessel in sanctification and honor, not in lustful passion, like the Gentiles who do not know God; <em>and</em> that no man transgress and defraud his brother in the matter because the Lord is <em>the</em> avenger in all these things, just as we also told you before and solemnly warned <em>you</em>. For God has not called us for the purpose of impurity, but in sanctification. So, he who rejects <em>this</em> is not rejecting man but the God who gives His Holy Spirit to you.” 1 Thessalonians 4:1–8.“But I say, walk by the Spirit, and you will not carry out the desire of the flesh.” Galatians 5:16.</span> fornication,<span data-type="footnote" class="footnote">“Marriage is to be held in honor among all, and the marriage bed is to be undefiled; for fornicators and adulterers God will judge.” Hebrews 13:4.</span> adultery,<span data-type="footnote" class="footnote">“You shall not commit adultery.” Exodus 20:14.</span> polygamy,<span data-type="footnote" class="footnote">“And He answered and said, ‘Have you not read that He who created them from the beginning MADE THEM MALE AND FEMALE, and said, “FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER AND BE JOINED TO HIS WIFE, AND THE TWO SHALL BECOME ONE FLESH”? So they are no longer two, but one flesh. What therefore God has joined together, let no man separate.’” Matthew 19:4–6. “An overseer, then, must be above reproach, the husband of one wife . . .” 1 Timothy 3:2.</span> incest,<span data-type="footnote" class="footnote">“If there is a man who lies with his daughter-in-law, both of them shall surely be put to death; they have committed incest, their bloodguiltiness is upon them.” Leviticus 20:12. See also all of Leviticus 20.</span> pedophilia,<span data-type="footnote" class="footnote">“He said to His disciples, ‘It is inevitable that stumbling blocks come, but woe to him through whom they come! It would be better for him if a millstone were hung around his neck and he were thrown into the sea, than that he would cause one of these little ones to stumble.’” Luke 17:1–2.</span> homosexuality,<span data-type="footnote" class="footnote">“You shall not lie with a male as one lies with a female; it is an abomination.” Leviticus 18:22.</span> and bestiality.<span data-type="footnote" class="footnote">“Also you shall not have intercourse with any animal to be defiled with it, nor shall any woman stand before an animal to mate with it; it is a perversion.” Leviticus 18:23.</span> Because the heart of man is deceitful above all things and desperately wicked, it is impossible to catalogue fully all forms of sexual immorality and degradation.</li>
<li class="no-indent">God offers the free gift of forgiveness for these sins through repentance and faith in Jesus, and He has called the Church to proclaim that repentance and forgiveness, seeking the healing of those harmed by these sins.<span data-type="footnote" class="footnote">“Such were some of you; but you were washed, but you were sanctified, but you were justified in the name of the Lord Jesus Christ and in the Spirit of our God.” 1 Corinthians 6:11.“The Spirit of the LORD God is upon me,<br />
 Because the LORD has anointed me<br />
 To bring good news to the afflicted;<br />
 He has sent me to bind up the brokenhearted,<br />
 To proclaim liberty to captives<br />
 And freedom to prisoners.”<br />
 Isaiah 61:1. “A BATTERED REED HE WILL NOT BREAK OFF,<br />
 AND A SMOLDERING WICK HE WILL NOT PUT OUT,<br />
 UNTIL HE LEADS JUSTICE TO VICTORY.”<br />
 Matthew 12:20.</span></li>
<li class="no-indent">Presently, there is widespread disregard, even scorn, for the divine standard of sexuality and marriage as revealed in Scripture. This disregard, which is found both in the world and in many churches, endangers the family (our basic social unit) and causes much suffering to the innocent, especially children. When found in the Church, it brings shame to the name of Christ.<span data-type="footnote" class="footnote">“However, because by this deed you have given occasion to the enemies of the LORD to blaspheme, the child also that is born to you shall surely die.” 2 Samuel 12:14. This text demonstrates dishonor coming to God’s holy name and suffering coming to the members of a man’s family—both caused by the sin of the father. “For ‘THE NAME OF GOD IS BLASPHEMED AMONG THE GENTILES BECAUSE OF YOU,’ just as it is written.” Romans 2:24.</span></li>
<li class="no-indent">A pastor, officer, leader, teacher, employee, or member of Evangel Presbytery shall not solemnize a marriage or officiate at a wedding in any place or under any circumstances that violate God’s Law or His established pattern of marriage between one male and one female, which union is intended to be monogamous and lifelong. Recognizing the universal application of God’s Order of Creation and the resultant Scriptural command that wives submit to their husbands, any wedding solemnized by a pastor of Evangel Presbytery will include in the wife’s vows her promise to “obey” her husband. This promise to “obey” will also be required in any wedding permitted by Evangel Presbytery’s Board of Elders to be held on church property or in a church facility but officiated by a pastor unaffiliated with this congregation.</li>
<li class="no-indent">The property or any facility of Evangel Presbytery shall not be used for a marriage ceremony, wedding, or related event that violates God’s Law or His established pattern of marriage between one male and one female, which union is intended to be monogamous and lifelong.</li>
<li class="no-indent">All ministries of Evangel Presbytery, including educational ministries for youth, shall adhere to and abide by this Declaration.</li>
<li class="no-indent">The Scriptures of the Old and New Testaments are the only infallible rule of faith and practice and the only authority that may bind the conscience.</li>
<li class="no-indent">This Declaration does not exhaust the extent of our beliefs and practices. The Bible itself, as the inspired and infallible Word of God that speaks with final authority concerning truth, morality, and the proper conduct of mankind, is the sole and final source of authority for all that we believe and do. For purposes of Evangel Presbytery’s faith, doctrine, practice, policy, and discipline, the membership of the Presbytery (as constituted under BCO <a href="#15.1">15.1</a>) is the Presbytery’s final interpretive authority on the Bible’s meaning and application, including for any purpose under BCO <a href="#15.8">15.8</a>.</li>
</ol>
</section>
<section data-type="chapter" class="chapter introduction" id="chapter-slug-29-amending-the-constitution-of-the-church" title="29. Amending the Constitution of the Church">
<header>
<h1 class="chapter-title">29. Amending the Constitution of the Church</h1>
<p data-type="subtitle" class="chapter-number"></p>
</header>
<ol class="ch29">
<li class="no-indent"><a id="29"></a><a id="29.1"></a>The Constitution of Evangel Presbytery, which is subject to and subordinate to the Scriptures of the Old and New Testaments, the infallible Word of God, consists of its doctrinal standards set forth in the <em>Westminster Confession of Faith</em><span data-type="footnote" class="footnote">American revisions as adopted by the Orthodox Presbyterian Church in 1936, https://evangelpresbytery.com/westminster-confession-of-faith.</span>, together with the <em>Larger</em><span data-type="footnote" class="footnote">https://evangelpresbytery.com/westminster-larger-catechism.</span> and <em>Shorter Catechisms</em><span data-type="footnote" class="footnote">https://evangelpresbytery.com/westminster-shorter-catechism.</span>; the Book of Church Order, which comprises the Form of Government, the Rules of Discipline, and the Directory for the Worship of God; and the Apostles’ Creed, Nicene Creed, Chalcedonian Creed, and Athanasian Creed; all as adopted by the Presbytery.</li>
<li class="no-indent">Amendments to the Book of Church Order may be made only in the following manner:
<ol type="a">
<li class="no-indent">Approval of the proposed amendment by the Presbytery and its recommendation to the Sessions.</li>
<li class="no-indent">The advice and consent of a majority of the Sessions.</li>
<li class="no-indent">The approval and enactment at a subsequent Presbytery meeting.</li>
</ol>
</li>
<li class="no-indent">Amendments to the Confession of Faith and Catechisms of this Church may be made only in the following manner:
<ol type="a">
<li class="no-indent">The approval of the proposed amendment by the Presbytery and its recommendation to the Sessions.</li>
<li class="no-indent">The advice and consent of three fourths of the Sessions.</li>
<li class="no-indent">The approval and enactment at a subsequent Presbytery meeting.</li>
</ol>
<p>This paragraph can be amended only by the same method as it prescribes for the amendment of the Confession of Faith and Catechisms of the Church.</p>
</li>
<li class="no-indent">Full organic union and consolidation of Evangel Presbytery with any other ecclesiastical body can be effected only in the following manner:
<ol type="a">
<li class="no-indent">The approval of the proposed union by the Presbytery and its recommendation to the Sessions.</li>
<li class="no-indent">The advice and consent of three fourths of the Sessions.</li>
<li class="no-indent">The approval and consummation at a subsequent Presbytery meeting.</li>
</ol>
<p class="no-indent">This paragraph can be amended only by the same method which is prescribed for the amendment of the Confession of Faith and Catechisms of the Church.</p>
</li>
<li class="no-indent">If by reason of the failure of a number of Sessions to act, or to report action, on any proposed amendment to the Standards, the response of the Sessions is not satisfactory to the succeeding Presbytery meeting, it may defer action for six months. In that event the Presbytery shall urge the delinquent Sessions to report their judgment to the next Presbytery meeting, which shall take final action on the proposed amendment.</li>
</ol>

<!--chapter:end:02-Form-of-Government.Rmd-->

